// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BatchCreateResult {
    "created": number;
    "skipped": number;
    "failed": number;
    "plans": ReviewPlan[];

    /** Creates a new BatchCreateResult instance. */
    constructor($$source: Partial<BatchCreateResult> = {}) {
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("plans" in $$source)) {
            this["plans"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchCreateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchCreateResult {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plans" in $$parsedSource) {
            $$parsedSource["plans"] = $$createField3_0($$parsedSource["plans"]);
        }
        return new BatchCreateResult($$parsedSource as Partial<BatchCreateResult>);
    }
}

export class CalendarHeatmapData {
    "date": string;
    "count": number;
    "passed": number;
    "failed": number;

    /** Creates a new CalendarHeatmapData instance. */
    constructor($$source: Partial<CalendarHeatmapData> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("passed" in $$source)) {
            this["passed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalendarHeatmapData instance from a string or object.
     */
    static createFrom($$source: any = {}): CalendarHeatmapData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalendarHeatmapData($$parsedSource as Partial<CalendarHeatmapData>);
    }
}

export class DueReviewsFilter {
    "exam_id"?: string | null;
    "until_date"?: string | null;
    "status"?: string[];
    "difficult_only"?: boolean | null;
    "limit"?: number | null;
    "offset"?: number | null;

    /** Creates a new DueReviewsFilter instance. */
    constructor($$source: Partial<DueReviewsFilter> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DueReviewsFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): DueReviewsFilter {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField2_0($$parsedSource["status"]);
        }
        return new DueReviewsFilter($$parsedSource as Partial<DueReviewsFilter>);
    }
}

export class DueReviewsResult {
    "plans": ReviewPlan[];
    "total": number;
    "has_more": boolean;

    /** Creates a new DueReviewsResult instance. */
    constructor($$source: Partial<DueReviewsResult> = {}) {
        if (!("plans" in $$source)) {
            this["plans"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DueReviewsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DueReviewsResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plans" in $$parsedSource) {
            $$parsedSource["plans"] = $$createField0_0($$parsedSource["plans"]);
        }
        return new DueReviewsResult($$parsedSource as Partial<DueReviewsResult>);
    }
}

export class ProcessReviewResult {
    "plan": ReviewPlan;
    "passed": boolean;
    "new_interval": number;
    "next_review_date": string;
    "history": ReviewHistory;

    /** Creates a new ProcessReviewResult instance. */
    constructor($$source: Partial<ProcessReviewResult> = {}) {
        if (!("plan" in $$source)) {
            this["plan"] = (new ReviewPlan());
        }
        if (!("passed" in $$source)) {
            this["passed"] = false;
        }
        if (!("new_interval" in $$source)) {
            this["new_interval"] = 0;
        }
        if (!("next_review_date" in $$source)) {
            this["next_review_date"] = "";
        }
        if (!("history" in $$source)) {
            this["history"] = (new ReviewHistory());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessReviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessReviewResult {
        const $$createField0_0 = $$createType0;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField0_0($$parsedSource["plan"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField4_0($$parsedSource["history"]);
        }
        return new ProcessReviewResult($$parsedSource as Partial<ProcessReviewResult>);
    }
}

export class ReviewHistory {
    "id": string;
    "plan_id": string;
    "question_id": string;
    "quality": number;
    "passed": boolean;
    "ease_factor_before": number;
    "ease_factor_after": number;
    "interval_before": number;
    "interval_after": number;
    "repetitions_before": number;
    "repetitions_after": number;
    "reviewed_at": string;
    "user_answer": string | null;
    "time_spent_seconds": number | null;

    /** Creates a new ReviewHistory instance. */
    constructor($$source: Partial<ReviewHistory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("plan_id" in $$source)) {
            this["plan_id"] = "";
        }
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("quality" in $$source)) {
            this["quality"] = 0;
        }
        if (!("passed" in $$source)) {
            this["passed"] = false;
        }
        if (!("ease_factor_before" in $$source)) {
            this["ease_factor_before"] = 0;
        }
        if (!("ease_factor_after" in $$source)) {
            this["ease_factor_after"] = 0;
        }
        if (!("interval_before" in $$source)) {
            this["interval_before"] = 0;
        }
        if (!("interval_after" in $$source)) {
            this["interval_after"] = 0;
        }
        if (!("repetitions_before" in $$source)) {
            this["repetitions_before"] = 0;
        }
        if (!("repetitions_after" in $$source)) {
            this["repetitions_after"] = 0;
        }
        if (!("reviewed_at" in $$source)) {
            this["reviewed_at"] = "";
        }
        if (!("user_answer" in $$source)) {
            this["user_answer"] = null;
        }
        if (!("time_spent_seconds" in $$source)) {
            this["time_spent_seconds"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewHistory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviewHistory($$parsedSource as Partial<ReviewHistory>);
    }
}

export class ReviewPlan {
    "id": string;
    "question_id": string;
    "exam_id": string;
    "ease_factor": number;
    "interval_days": number;
    "repetitions": number;
    "next_review_date": string;
    "last_review_date": string | null;
    "status": string;
    "total_reviews": number;
    "total_correct": number;
    "consecutive_failures": number;
    "is_difficult": boolean;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ReviewPlan instance. */
    constructor($$source: Partial<ReviewPlan> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("ease_factor" in $$source)) {
            this["ease_factor"] = 0;
        }
        if (!("interval_days" in $$source)) {
            this["interval_days"] = 0;
        }
        if (!("repetitions" in $$source)) {
            this["repetitions"] = 0;
        }
        if (!("next_review_date" in $$source)) {
            this["next_review_date"] = "";
        }
        if (!("last_review_date" in $$source)) {
            this["last_review_date"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("total_reviews" in $$source)) {
            this["total_reviews"] = 0;
        }
        if (!("total_correct" in $$source)) {
            this["total_correct"] = 0;
        }
        if (!("consecutive_failures" in $$source)) {
            this["consecutive_failures"] = 0;
        }
        if (!("is_difficult" in $$source)) {
            this["is_difficult"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewPlan {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviewPlan($$parsedSource as Partial<ReviewPlan>);
    }
}

export class ReviewStats {
    "exam_id": string | null;
    "total_plans": number;
    "new_count": number;
    "learning_count": number;
    "reviewing_count": number;
    "graduated_count": number;
    "suspended_count": number;
    "due_today": number;
    "overdue_count": number;
    "difficult_count": number;
    "total_reviews": number;
    "total_correct": number;
    "avg_correct_rate": number;
    "avg_ease_factor": number;
    "updated_at": string;

    /** Creates a new ReviewStats instance. */
    constructor($$source: Partial<ReviewStats> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = null;
        }
        if (!("total_plans" in $$source)) {
            this["total_plans"] = 0;
        }
        if (!("new_count" in $$source)) {
            this["new_count"] = 0;
        }
        if (!("learning_count" in $$source)) {
            this["learning_count"] = 0;
        }
        if (!("reviewing_count" in $$source)) {
            this["reviewing_count"] = 0;
        }
        if (!("graduated_count" in $$source)) {
            this["graduated_count"] = 0;
        }
        if (!("suspended_count" in $$source)) {
            this["suspended_count"] = 0;
        }
        if (!("due_today" in $$source)) {
            this["due_today"] = 0;
        }
        if (!("overdue_count" in $$source)) {
            this["overdue_count"] = 0;
        }
        if (!("difficult_count" in $$source)) {
            this["difficult_count"] = 0;
        }
        if (!("total_reviews" in $$source)) {
            this["total_reviews"] = 0;
        }
        if (!("total_correct" in $$source)) {
            this["total_correct"] = 0;
        }
        if (!("avg_correct_rate" in $$source)) {
            this["avg_correct_rate"] = 0;
        }
        if (!("avg_ease_factor" in $$source)) {
            this["avg_ease_factor"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviewStats($$parsedSource as Partial<ReviewStats>);
    }
}

// Private type creation functions
const $$createType0 = ReviewPlan.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ReviewHistory.createFrom;
