// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Block {
    "id": string;
    "messageId": string;
    "type": string;
    "status": string;
    "content"?: string;
    "toolName"?: string | null;
    "toolCallId"?: string | null;
    "toolInput"?: any;
    "toolOutput"?: any;
    "citations"?: any[];
    "error"?: string | null;
    "startedAt"?: number | null;
    "endedAt"?: number | null;
    "firstChunkAt"?: number | null;

    /** Creates a new Block instance. */
    constructor($$source: Partial<Block> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Block instance from a string or object.
     */
    static createFrom($$source: any = {}): Block {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("citations" in $$parsedSource) {
            $$parsedSource["citations"] = $$createField9_0($$parsedSource["citations"]);
        }
        return new Block($$parsedSource as Partial<Block>);
    }
}

export class CallerTypeSummary {
    "callerType": string;
    "displayName": string;
    "requestCount": number;
    "totalTokens": number;
    "estimatedCostUsd"?: number | null;
    "percentage"?: number | null;

    /** Creates a new CallerTypeSummary instance. */
    constructor($$source: Partial<CallerTypeSummary> = {}) {
        if (!("callerType" in $$source)) {
            this["callerType"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("requestCount" in $$source)) {
            this["requestCount"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CallerTypeSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): CallerTypeSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CallerTypeSummary($$parsedSource as Partial<CallerTypeSummary>);
    }
}

export class CreateGroupRequest {
    "name": string;
    "description"?: string | null;
    "icon"?: string | null;
    "color"?: string | null;
    "systemPrompt"?: string | null;
    "defaultSkillIds"?: string[];
    "pinnedResourceIds"?: string[];
    "workspaceId"?: string | null;

    /** Creates a new CreateGroupRequest instance. */
    constructor($$source: Partial<CreateGroupRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateGroupRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateGroupRequest {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultSkillIds" in $$parsedSource) {
            $$parsedSource["defaultSkillIds"] = $$createField5_0($$parsedSource["defaultSkillIds"]);
        }
        if ("pinnedResourceIds" in $$parsedSource) {
            $$parsedSource["pinnedResourceIds"] = $$createField6_0($$parsedSource["pinnedResourceIds"]);
        }
        return new CreateGroupRequest($$parsedSource as Partial<CreateGroupRequest>);
    }
}

export class DailySummary {
    "dateKey": string;
    "model": string;
    "callerType": string;
    "callCount": number;
    "totalPromptTokens": number;
    "totalCompletionTokens": number;
    "totalTokens": number;
    "successCount": number;
    "errorCount": number;
    "totalCostEstimate"?: number | null;

    /** Creates a new DailySummary instance. */
    constructor($$source: Partial<DailySummary> = {}) {
        if (!("dateKey" in $$source)) {
            this["dateKey"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("callerType" in $$source)) {
            this["callerType"] = "";
        }
        if (!("callCount" in $$source)) {
            this["callCount"] = 0;
        }
        if (!("totalPromptTokens" in $$source)) {
            this["totalPromptTokens"] = 0;
        }
        if (!("totalCompletionTokens" in $$source)) {
            this["totalCompletionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("errorCount" in $$source)) {
            this["errorCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): DailySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailySummary($$parsedSource as Partial<DailySummary>);
    }
}

export class EditAndResendRequest {
    "sessionId": string;
    "messageId": string;
    "newContent": string;
    "assistantMessageId"?: string | null;
    "newContextRefs"?: any[];
    "newPathMap"?: { [_ in string]?: string };
    "options"?: { [_ in string]?: any };

    /** Creates a new EditAndResendRequest instance. */
    constructor($$source: Partial<EditAndResendRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("newContent" in $$source)) {
            this["newContent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditAndResendRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EditAndResendRequest {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("newContextRefs" in $$parsedSource) {
            $$parsedSource["newContextRefs"] = $$createField4_0($$parsedSource["newContextRefs"]);
        }
        if ("newPathMap" in $$parsedSource) {
            $$parsedSource["newPathMap"] = $$createField5_0($$parsedSource["newPathMap"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new EditAndResendRequest($$parsedSource as Partial<EditAndResendRequest>);
    }
}

export class EditAndResendResponse {
    "new_message_id": string;
    "deleted_message_ids"?: string[];
    "new_variant_id"?: string | null;

    /** Creates a new EditAndResendResponse instance. */
    constructor($$source: Partial<EditAndResendResponse> = {}) {
        if (!("new_message_id" in $$source)) {
            this["new_message_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditAndResendResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): EditAndResendResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deleted_message_ids" in $$parsedSource) {
            $$parsedSource["deleted_message_ids"] = $$createField1_0($$parsedSource["deleted_message_ids"]);
        }
        return new EditAndResendResponse($$parsedSource as Partial<EditAndResendResponse>);
    }
}

export class Group {
    "id": string;
    "name": string;
    "description"?: string | null;
    "icon"?: string | null;
    "color"?: string | null;
    "systemPrompt"?: string | null;
    "defaultSkillIds": string[];
    "pinnedResourceIds": string[];
    "workspaceId"?: string | null;
    "sortOrder": number;
    "persistStatus": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("defaultSkillIds" in $$source)) {
            this["defaultSkillIds"] = [];
        }
        if (!("pinnedResourceIds" in $$source)) {
            this["pinnedResourceIds"] = [];
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("persistStatus" in $$source)) {
            this["persistStatus"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultSkillIds" in $$parsedSource) {
            $$parsedSource["defaultSkillIds"] = $$createField6_0($$parsedSource["defaultSkillIds"]);
        }
        if ("pinnedResourceIds" in $$parsedSource) {
            $$parsedSource["pinnedResourceIds"] = $$createField7_0($$parsedSource["pinnedResourceIds"]);
        }
        return new Group($$parsedSource as Partial<Group>);
    }
}

export class LoadSessionResponse {
    "session": Session;
    "messages": Message[];
    "blocks": Block[];
    "state"?: SessionState;

    /** Creates a new LoadSessionResponse instance. */
    constructor($$source: Partial<LoadSessionResponse> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new Session());
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadSessionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadSessionResponse {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField1_0($$parsedSource["messages"]);
        }
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField2_0($$parsedSource["blocks"]);
        }
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField3_0($$parsedSource["state"]);
        }
        return new LoadSessionResponse($$parsedSource as Partial<LoadSessionResponse>);
    }
}

export class Message {
    "id": string;
    "sessionId": string;
    "role": string;
    "blockIds": string[];
    "timestamp": number;
    "persistentStableId"?: string | null;
    "parentId"?: string | null;
    "supersedes"?: string | null;
    "_meta"?: { [_ in string]?: any };
    "attachments"?: any[];

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("blockIds" in $$source)) {
            this["blockIds"] = [];
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField3_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockIds" in $$parsedSource) {
            $$parsedSource["blockIds"] = $$createField3_0($$parsedSource["blockIds"]);
        }
        if ("_meta" in $$parsedSource) {
            $$parsedSource["_meta"] = $$createField8_0($$parsedSource["_meta"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField9_0($$parsedSource["attachments"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class MessageSummary {
    "total_messages": number;
    "user_messages": number;
    "assistant_messages": number;
    "sessions_with_messages": number;

    /** Creates a new MessageSummary instance. */
    constructor($$source: Partial<MessageSummary> = {}) {
        if (!("total_messages" in $$source)) {
            this["total_messages"] = 0;
        }
        if (!("user_messages" in $$source)) {
            this["user_messages"] = 0;
        }
        if (!("assistant_messages" in $$source)) {
            this["assistant_messages"] = 0;
        }
        if (!("sessions_with_messages" in $$source)) {
            this["sessions_with_messages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageSummary($$parsedSource as Partial<MessageSummary>);
    }
}

export class ModelSummary {
    "modelId": string;
    "requestCount": number;
    "totalTokens": number;
    "promptTokens": number;
    "completionTokens": number;
    "estimatedCostUsd"?: number | null;
    "percentage"?: number | null;
    "avgTokensPerRequest"?: number | null;

    /** Creates a new ModelSummary instance. */
    constructor($$source: Partial<ModelSummary> = {}) {
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("requestCount" in $$source)) {
            this["requestCount"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelSummary($$parsedSource as Partial<ModelSummary>);
    }
}

export class RetryMessageResponse {
    "message_id": string;
    "deleted_message_ids"?: string[];
    "deleted_variant_ids"?: string[];
    "new_variant_id"?: string | null;

    /** Creates a new RetryMessageResponse instance. */
    constructor($$source: Partial<RetryMessageResponse> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetryMessageResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): RetryMessageResponse {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deleted_message_ids" in $$parsedSource) {
            $$parsedSource["deleted_message_ids"] = $$createField1_0($$parsedSource["deleted_message_ids"]);
        }
        if ("deleted_variant_ids" in $$parsedSource) {
            $$parsedSource["deleted_variant_ids"] = $$createField2_0($$parsedSource["deleted_variant_ids"]);
        }
        return new RetryMessageResponse($$parsedSource as Partial<RetryMessageResponse>);
    }
}

export class SendMessageRequest {
    "sessionId": string;
    "content": string;
    "options"?: { [_ in string]?: any };
    "userMessageId"?: string | null;
    "assistantMessageId"?: string | null;
    "userContextRefs"?: any[];
    "pathMap"?: { [_ in string]?: string };
    "workspaceId"?: string | null;

    /** Creates a new SendMessageRequest instance. */
    constructor($$source: Partial<SendMessageRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendMessageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SendMessageRequest {
        const $$createField2_0 = $$createType3;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        if ("userContextRefs" in $$parsedSource) {
            $$parsedSource["userContextRefs"] = $$createField5_0($$parsedSource["userContextRefs"]);
        }
        if ("pathMap" in $$parsedSource) {
            $$parsedSource["pathMap"] = $$createField6_0($$parsedSource["pathMap"]);
        }
        return new SendMessageRequest($$parsedSource as Partial<SendMessageRequest>);
    }
}

export class Session {
    "id": string;
    "mode": string;
    "title"?: string | null;
    "description"?: string | null;
    "titleLocked"?: boolean;
    "persistStatus": string;
    "createdAt": string;
    "updatedAt": string;
    "groupId"?: string | null;
    "metadata"?: { [_ in string]?: any };

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("persistStatus" in $$source)) {
            this["persistStatus"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField9_0($$parsedSource["metadata"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionSettings {
    "title"?: string | null;
    "description"?: string | null;
    "metadata"?: { [_ in string]?: any };
    "groupId"?: string | null;

    /** Creates a new SessionSettings instance. */
    constructor($$source: Partial<SessionSettings> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSettings {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField2_0($$parsedSource["metadata"]);
        }
        return new SessionSettings($$parsedSource as Partial<SessionSettings>);
    }
}

export type SessionState = { [_ in string]?: any };

export class UpdateGroupRequest {
    "name"?: string | null;
    "description"?: string | null;
    "icon"?: string | null;
    "color"?: string | null;
    "systemPrompt"?: string | null;
    "defaultSkillIds"?: string[];
    "pinnedResourceIds"?: string[];
    "workspaceId"?: string | null;
    "sortOrder"?: number | null;
    "persistStatus"?: string | null;

    /** Creates a new UpdateGroupRequest instance. */
    constructor($$source: Partial<UpdateGroupRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateGroupRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateGroupRequest {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultSkillIds" in $$parsedSource) {
            $$parsedSource["defaultSkillIds"] = $$createField5_0($$parsedSource["defaultSkillIds"]);
        }
        if ("pinnedResourceIds" in $$parsedSource) {
            $$parsedSource["pinnedResourceIds"] = $$createField6_0($$parsedSource["pinnedResourceIds"]);
        }
        return new UpdateGroupRequest($$parsedSource as Partial<UpdateGroupRequest>);
    }
}

export class UsageRecord {
    "id": string;
    "callerType": string;
    "callerId"?: string | null;
    "modelId": string;
    "configId"?: string | null;
    "providerId"?: string | null;
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "reasoningTokens"?: number | null;
    "cachedTokens"?: number | null;
    "estimatedCostUsd"?: number | null;
    "durationMs"?: number | null;
    "success": boolean;
    "errorMessage"?: string | null;
    "createdAt": string;
    "workspaceId"?: string | null;

    /** Creates a new UsageRecord instance. */
    constructor($$source: Partial<UsageRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("callerType" in $$source)) {
            this["callerType"] = "";
        }
        if (!("modelId" in $$source)) {
            this["modelId"] = "";
        }
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageRecord($$parsedSource as Partial<UsageRecord>);
    }
}

export class UsageSummary {
    "startDate": string;
    "endDate": string;
    "totalRequests": number;
    "successRequests": number;
    "errorRequests": number;
    "totalPromptTokens": number;
    "totalCompletionTokens": number;
    "totalTokens": number;
    "totalReasoningTokens"?: number | null;
    "totalCachedTokens"?: number | null;
    "totalEstimatedCostUsd"?: number | null;
    "avgTokensPerRequest"?: number | null;
    "avgDurationMs"?: number | null;
    "byCallerType"?: CallerTypeSummary[];
    "byModel"?: ModelSummary[];
    "trendPoints"?: UsageTrendPoint[];

    /** Creates a new UsageSummary instance. */
    constructor($$source: Partial<UsageSummary> = {}) {
        if (!("startDate" in $$source)) {
            this["startDate"] = "";
        }
        if (!("endDate" in $$source)) {
            this["endDate"] = "";
        }
        if (!("totalRequests" in $$source)) {
            this["totalRequests"] = 0;
        }
        if (!("successRequests" in $$source)) {
            this["successRequests"] = 0;
        }
        if (!("errorRequests" in $$source)) {
            this["errorRequests"] = 0;
        }
        if (!("totalPromptTokens" in $$source)) {
            this["totalPromptTokens"] = 0;
        }
        if (!("totalCompletionTokens" in $$source)) {
            this["totalCompletionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageSummary {
        const $$createField13_0 = $$createType11;
        const $$createField14_0 = $$createType13;
        const $$createField15_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("byCallerType" in $$parsedSource) {
            $$parsedSource["byCallerType"] = $$createField13_0($$parsedSource["byCallerType"]);
        }
        if ("byModel" in $$parsedSource) {
            $$parsedSource["byModel"] = $$createField14_0($$parsedSource["byModel"]);
        }
        if ("trendPoints" in $$parsedSource) {
            $$parsedSource["trendPoints"] = $$createField15_0($$parsedSource["trendPoints"]);
        }
        return new UsageSummary($$parsedSource as Partial<UsageSummary>);
    }
}

export class UsageTrendPoint {
    "timeLabel": string;
    "timestamp": number;
    "totalTokens": number;
    "promptTokens": number;
    "completionTokens": number;
    "requestCount": number;
    "estimatedCostUsd"?: number | null;
    "successRate"?: number | null;

    /** Creates a new UsageTrendPoint instance. */
    constructor($$source: Partial<UsageTrendPoint> = {}) {
        if (!("timeLabel" in $$source)) {
            this["timeLabel"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("requestCount" in $$source)) {
            this["requestCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageTrendPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageTrendPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageTrendPoint($$parsedSource as Partial<UsageTrendPoint>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = Session.createFrom;
const $$createType5 = Message.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Block.createFrom;
const $$createType8 = $Create.Array($$createType7);
var $$createType9 = (function $$initCreateType9(...args: any[]): any {
    if ($$createType9 === $$initCreateType9) {
        $$createType9 = $$createType3;
    }
    return $$createType9(...args);
});
const $$createType10 = CallerTypeSummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ModelSummary.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = UsageTrendPoint.createFrom;
const $$createType15 = $Create.Array($$createType14);
