// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class APIConfigStatus {
    "config_count": number;
    "enabled_count": number;
    "has_assignments": boolean;
    "needs_recovery": boolean;

    /** Creates a new APIConfigStatus instance. */
    constructor($$source: Partial<APIConfigStatus> = {}) {
        if (!("config_count" in $$source)) {
            this["config_count"] = 0;
        }
        if (!("enabled_count" in $$source)) {
            this["enabled_count"] = 0;
        }
        if (!("has_assignments" in $$source)) {
            this["has_assignments"] = false;
        }
        if (!("needs_recovery" in $$source)) {
            this["needs_recovery"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIConfigStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): APIConfigStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIConfigStatus($$parsedSource as Partial<APIConfigStatus>);
    }
}

export class ApiConfig {
    "id": string;
    "name": string;
    "vendorId"?: string | null;
    "vendorName"?: string | null;
    "providerType"?: string | null;
    "providerScope"?: string | null;
    "apiProtocol"?: string | null;
    "supportsOpenAIResponses"?: boolean | null;
    "apiKey": string;
    "baseUrl": string;
    "model": string;
    "isMultimodal": boolean;
    "isReasoning": boolean;
    "isEmbedding": boolean;
    "isReranker": boolean;
    "isImageGeneration"?: boolean;
    "enabled": boolean;
    "modelAdapter": string;
    "maxOutputTokens"?: number;
    "temperature"?: number;
    "supportsTools"?: boolean;
    "geminiApiVersion"?: string;
    "isBuiltin"?: boolean;
    "isReadOnly"?: boolean;
    "reasoningEffort"?: string | null;
    "thinkingEnabled"?: boolean;
    "thinkingBudget"?: number | null;
    "includeThoughts"?: boolean;
    "minP"?: number | null;
    "topK"?: number | null;
    "enableThinking"?: boolean | null;
    "supportsReasoning"?: boolean;
    "headers"?: { [_ in string]?: string };
    "topPOverride"?: number | null;
    "frequencyPenaltyOverride"?: number | null;
    "presencePenaltyOverride"?: number | null;
    "repetitionPenalty"?: number | null;
    "reasoningSplit"?: boolean | null;
    "effort"?: string | null;
    "verbosity"?: string | null;
    "isFavorite"?: boolean;
    "maxTokensLimit"?: number | null;
    "contextWindow"?: number | null;
    "isAudioTranscription"?: boolean;

    /** Creates a new ApiConfig instance. */
    constructor($$source: Partial<ApiConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("isMultimodal" in $$source)) {
            this["isMultimodal"] = false;
        }
        if (!("isReasoning" in $$source)) {
            this["isReasoning"] = false;
        }
        if (!("isEmbedding" in $$source)) {
            this["isEmbedding"] = false;
        }
        if (!("isReranker" in $$source)) {
            this["isReranker"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("modelAdapter" in $$source)) {
            this["modelAdapter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApiConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ApiConfig {
        const $$createField32_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField32_0($$parsedSource["headers"]);
        }
        return new ApiConfig($$parsedSource as Partial<ApiConfig>);
    }
}

export class AttachmentConfig {
    "attachmentRootFolderId": string | null;
    "attachmentRootFolderTitle": string | null;

    /** Creates a new AttachmentConfig instance. */
    constructor($$source: Partial<AttachmentConfig> = {}) {
        if (!("attachmentRootFolderId" in $$source)) {
            this["attachmentRootFolderId"] = null;
        }
        if (!("attachmentRootFolderTitle" in $$source)) {
            this["attachmentRootFolderTitle"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentConfig($$parsedSource as Partial<AttachmentConfig>);
    }
}

export class AvailableOCRModel {
    "configId": string;
    "model": string;
    "engineType": string;
    "name": string;
    "isFree": boolean;
    "description"?: string | null;
    "supportsGrounding": boolean;
    "enabled": boolean;
    "priority": number;

    /** Creates a new AvailableOCRModel instance. */
    constructor($$source: Partial<AvailableOCRModel> = {}) {
        if (!("configId" in $$source)) {
            this["configId"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("engineType" in $$source)) {
            this["engineType"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isFree" in $$source)) {
            this["isFree"] = false;
        }
        if (!("supportsGrounding" in $$source)) {
            this["supportsGrounding"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableOCRModel instance from a string or object.
     */
    static createFrom($$source: any = {}): AvailableOCRModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailableOCRModel($$parsedSource as Partial<AvailableOCRModel>);
    }
}

export class BackupConfig {
    "backupDirectory": string | null;
    "autoBackupEnabled": boolean;
    "autoBackupIntervalHours": number;
    "maxBackupCount": number | null;
    "slimBackup": boolean;
    "backupTiers"?: string[];

    /** Creates a new BackupConfig instance. */
    constructor($$source: Partial<BackupConfig> = {}) {
        if (!("backupDirectory" in $$source)) {
            this["backupDirectory"] = null;
        }
        if (!("autoBackupEnabled" in $$source)) {
            this["autoBackupEnabled"] = false;
        }
        if (!("autoBackupIntervalHours" in $$source)) {
            this["autoBackupIntervalHours"] = 0;
        }
        if (!("maxBackupCount" in $$source)) {
            this["maxBackupCount"] = null;
        }
        if (!("slimBackup" in $$source)) {
            this["slimBackup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupConfig {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backupTiers" in $$parsedSource) {
            $$parsedSource["backupTiers"] = $$createField5_0($$parsedSource["backupTiers"]);
        }
        return new BackupConfig($$parsedSource as Partial<BackupConfig>);
    }
}

export class BasicStatistics {
    "total_mistakes": number;
    "total_reviews": number;
    "type_stats": { [_ in string]?: number };
    "tag_stats": { [_ in string]?: number };
    "recent_mistakes": any[];

    /** Creates a new BasicStatistics instance. */
    constructor($$source: Partial<BasicStatistics> = {}) {
        if (!("total_mistakes" in $$source)) {
            this["total_mistakes"] = 0;
        }
        if (!("total_reviews" in $$source)) {
            this["total_reviews"] = 0;
        }
        if (!("type_stats" in $$source)) {
            this["type_stats"] = {};
        }
        if (!("tag_stats" in $$source)) {
            this["tag_stats"] = {};
        }
        if (!("recent_mistakes" in $$source)) {
            this["recent_mistakes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BasicStatistics instance from a string or object.
     */
    static createFrom($$source: any = {}): BasicStatistics {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("type_stats" in $$parsedSource) {
            $$parsedSource["type_stats"] = $$createField2_0($$parsedSource["type_stats"]);
        }
        if ("tag_stats" in $$parsedSource) {
            $$parsedSource["tag_stats"] = $$createField3_0($$parsedSource["tag_stats"]);
        }
        if ("recent_mistakes" in $$parsedSource) {
            $$parsedSource["recent_mistakes"] = $$createField4_0($$parsedSource["recent_mistakes"]);
        }
        return new BasicStatistics($$parsedSource as Partial<BasicStatistics>);
    }
}

export class CNWhitelistConfigResult {
    "default_sites": string[];
    "user_config": CNWhitelistUserConfig;

    /** Creates a new CNWhitelistConfigResult instance. */
    constructor($$source: Partial<CNWhitelistConfigResult> = {}) {
        if (!("default_sites" in $$source)) {
            this["default_sites"] = [];
        }
        if (!("user_config" in $$source)) {
            this["user_config"] = (new CNWhitelistUserConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CNWhitelistConfigResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CNWhitelistConfigResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default_sites" in $$parsedSource) {
            $$parsedSource["default_sites"] = $$createField0_0($$parsedSource["default_sites"]);
        }
        if ("user_config" in $$parsedSource) {
            $$parsedSource["user_config"] = $$createField1_0($$parsedSource["user_config"]);
        }
        return new CNWhitelistConfigResult($$parsedSource as Partial<CNWhitelistConfigResult>);
    }
}

export class CNWhitelistUserConfig {
    "enabled": boolean;
    "use_default_list": boolean;
    "custom_sites": string[];

    /** Creates a new CNWhitelistUserConfig instance. */
    constructor($$source: Partial<CNWhitelistUserConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("use_default_list" in $$source)) {
            this["use_default_list"] = false;
        }
        if (!("custom_sites" in $$source)) {
            this["custom_sites"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CNWhitelistUserConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): CNWhitelistUserConfig {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("custom_sites" in $$parsedSource) {
            $$parsedSource["custom_sites"] = $$createField2_0($$parsedSource["custom_sites"]);
        }
        return new CNWhitelistUserConfig($$parsedSource as Partial<CNWhitelistUserConfig>);
    }
}

export class EnhancedStatistics {
    "basic_stats": BasicStatistics;
    "image_stats": ImageStatistics;
    "recent_additions": number;
    "quality_score": number;
    "monthly_trend": any[];
    "timestamp": string;

    /** Creates a new EnhancedStatistics instance. */
    constructor($$source: Partial<EnhancedStatistics> = {}) {
        if (!("basic_stats" in $$source)) {
            this["basic_stats"] = (new BasicStatistics());
        }
        if (!("image_stats" in $$source)) {
            this["image_stats"] = (new ImageStatistics());
        }
        if (!("recent_additions" in $$source)) {
            this["recent_additions"] = 0;
        }
        if (!("quality_score" in $$source)) {
            this["quality_score"] = 0;
        }
        if (!("monthly_trend" in $$source)) {
            this["monthly_trend"] = [];
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnhancedStatistics instance from a string or object.
     */
    static createFrom($$source: any = {}): EnhancedStatistics {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("basic_stats" in $$parsedSource) {
            $$parsedSource["basic_stats"] = $$createField0_0($$parsedSource["basic_stats"]);
        }
        if ("image_stats" in $$parsedSource) {
            $$parsedSource["image_stats"] = $$createField1_0($$parsedSource["image_stats"]);
        }
        if ("monthly_trend" in $$parsedSource) {
            $$parsedSource["monthly_trend"] = $$createField4_0($$parsedSource["monthly_trend"]);
        }
        return new EnhancedStatistics($$parsedSource as Partial<EnhancedStatistics>);
    }
}

export class ImageStatistics {
    "total_files": number;
    "total_size_bytes": number;

    /** Creates a new ImageStatistics instance. */
    constructor($$source: Partial<ImageStatistics> = {}) {
        if (!("total_files" in $$source)) {
            this["total_files"] = 0;
        }
        if (!("total_size_bytes" in $$source)) {
            this["total_size_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageStatistics instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageStatistics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageStatistics($$parsedSource as Partial<ImageStatistics>);
    }
}

export class MCPCacheState {
    "ttl_ms": number;
    "last_built_at": string | null;

    /** Creates a new MCPCacheState instance. */
    constructor($$source: Partial<MCPCacheState> = {}) {
        if (!("ttl_ms" in $$source)) {
            this["ttl_ms"] = 0;
        }
        if (!("last_built_at" in $$source)) {
            this["last_built_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPCacheState instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPCacheState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPCacheState($$parsedSource as Partial<MCPCacheState>);
    }
}

export class MCPPreheatResult {
    "ok": boolean;
    "count": number;

    /** Creates a new MCPPreheatResult instance. */
    constructor($$source: Partial<MCPPreheatResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPPreheatResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPPreheatResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPPreheatResult($$parsedSource as Partial<MCPPreheatResult>);
    }
}

export class MCPReloadResult {
    "success": boolean;
    "message"?: string;
    "error"?: string | null;

    /** Creates a new MCPReloadResult instance. */
    constructor($$source: Partial<MCPReloadResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPReloadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPReloadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPReloadResult($$parsedSource as Partial<MCPReloadResult>);
    }
}

export class MCPStatus {
    "available": boolean;
    "enabled": boolean;
    "connected": boolean;
    "enabled_reason": string | null;
    "server_info": any;
    "tools_count": number;
    "last_error": string;
    "namespace_prefix": string;
    "conflict_resolution": string;
    "cache_state": MCPCacheState;

    /** Creates a new MCPStatus instance. */
    constructor($$source: Partial<MCPStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("enabled_reason" in $$source)) {
            this["enabled_reason"] = null;
        }
        if (!("server_info" in $$source)) {
            this["server_info"] = null;
        }
        if (!("tools_count" in $$source)) {
            this["tools_count"] = 0;
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }
        if (!("namespace_prefix" in $$source)) {
            this["namespace_prefix"] = "";
        }
        if (!("conflict_resolution" in $$source)) {
            this["conflict_resolution"] = "";
        }
        if (!("cache_state" in $$source)) {
            this["cache_state"] = (new MCPCacheState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPStatus {
        const $$createField9_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cache_state" in $$parsedSource) {
            $$parsedSource["cache_state"] = $$createField9_0($$parsedSource["cache_state"]);
        }
        return new MCPStatus($$parsedSource as Partial<MCPStatus>);
    }
}

export class MCPToolInfo {
    "name": string;
    "description"?: string;
    "input_schema"?: any;

    /** Creates a new MCPToolInfo instance. */
    constructor($$source: Partial<MCPToolInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPToolInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPToolInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPToolInfo($$parsedSource as Partial<MCPToolInfo>);
    }
}

export class MemoryConfig {
    "memoryRootFolderId": string | null;
    "memoryRootFolderTitle": string | null;
    "autoCreateSubfolders": boolean;
    "defaultCategory": string;
    "privacyMode": boolean;
    "autoExtractFrequency": string;

    /** Creates a new MemoryConfig instance. */
    constructor($$source: Partial<MemoryConfig> = {}) {
        if (!("memoryRootFolderId" in $$source)) {
            this["memoryRootFolderId"] = null;
        }
        if (!("memoryRootFolderTitle" in $$source)) {
            this["memoryRootFolderTitle"] = null;
        }
        if (!("autoCreateSubfolders" in $$source)) {
            this["autoCreateSubfolders"] = false;
        }
        if (!("defaultCategory" in $$source)) {
            this["defaultCategory"] = "";
        }
        if (!("privacyMode" in $$source)) {
            this["privacyMode"] = false;
        }
        if (!("autoExtractFrequency" in $$source)) {
            this["autoExtractFrequency"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryConfig($$parsedSource as Partial<MemoryConfig>);
    }
}

export class ModelAdapterOption {
    "value": string;
    "label": string;
    "description"?: string;
    "is_default": boolean;

    /** Creates a new ModelAdapterOption instance. */
    constructor($$source: Partial<ModelAdapterOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelAdapterOption instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelAdapterOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelAdapterOption($$parsedSource as Partial<ModelAdapterOption>);
    }
}

export class ModelAssignments {
    "model2_config_id": string | null;
    "review_analysis_model_config_id": string | null;
    "anki_card_model_config_id": string | null;
    "qbank_ai_grading_model_config_id": string | null;
    "embedding_model_config_id": string | null;
    "reranker_model_config_id": string | null;
    "chat_title_model_config_id": string | null;
    "exam_sheet_ocr_model_config_id": string | null;
    "translation_model_config_id": string | null;
    "vl_embedding_model_config_id": string | null;
    "vl_reranker_model_config_id": string | null;
    "memory_decision_model_config_id": string | null;
    "voice_input_asr_model_config_id": string | null;
    "image_generation_model_config_id": string | null;
    "translation_display_mode": string | null;

    /** Creates a new ModelAssignments instance. */
    constructor($$source: Partial<ModelAssignments> = {}) {
        if (!("model2_config_id" in $$source)) {
            this["model2_config_id"] = null;
        }
        if (!("review_analysis_model_config_id" in $$source)) {
            this["review_analysis_model_config_id"] = null;
        }
        if (!("anki_card_model_config_id" in $$source)) {
            this["anki_card_model_config_id"] = null;
        }
        if (!("qbank_ai_grading_model_config_id" in $$source)) {
            this["qbank_ai_grading_model_config_id"] = null;
        }
        if (!("embedding_model_config_id" in $$source)) {
            this["embedding_model_config_id"] = null;
        }
        if (!("reranker_model_config_id" in $$source)) {
            this["reranker_model_config_id"] = null;
        }
        if (!("chat_title_model_config_id" in $$source)) {
            this["chat_title_model_config_id"] = null;
        }
        if (!("exam_sheet_ocr_model_config_id" in $$source)) {
            this["exam_sheet_ocr_model_config_id"] = null;
        }
        if (!("translation_model_config_id" in $$source)) {
            this["translation_model_config_id"] = null;
        }
        if (!("vl_embedding_model_config_id" in $$source)) {
            this["vl_embedding_model_config_id"] = null;
        }
        if (!("vl_reranker_model_config_id" in $$source)) {
            this["vl_reranker_model_config_id"] = null;
        }
        if (!("memory_decision_model_config_id" in $$source)) {
            this["memory_decision_model_config_id"] = null;
        }
        if (!("voice_input_asr_model_config_id" in $$source)) {
            this["voice_input_asr_model_config_id"] = null;
        }
        if (!("image_generation_model_config_id" in $$source)) {
            this["image_generation_model_config_id"] = null;
        }
        if (!("translation_display_mode" in $$source)) {
            this["translation_display_mode"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelAssignments instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelAssignments {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelAssignments($$parsedSource as Partial<ModelAssignments>);
    }
}

export class ModelProfile {
    "id": string;
    "vendorId": string;
    "label": string;
    "model": string;
    "providerScope"?: string | null;
    "apiProtocol"?: string | null;
    "modelAdapter": string;
    "isMultimodal": boolean;
    "isReasoning": boolean;
    "isEmbedding": boolean;
    "isReranker": boolean;
    "isImageGeneration"?: boolean;
    "supportsTools"?: boolean;
    "supportsReasoning"?: boolean;
    "status"?: string;
    "enabled": boolean;
    "maxOutputTokens"?: number;
    "temperature"?: number;
    "reasoningEffort"?: string | null;
    "thinkingEnabled"?: boolean;
    "thinkingBudget"?: number | null;
    "includeThoughts"?: boolean;
    "enableThinking"?: boolean | null;
    "minP"?: number | null;
    "topK"?: number | null;
    "geminiApiVersion"?: string | null;
    "isBuiltin"?: boolean;
    "repetitionPenalty"?: number | null;
    "reasoningSplit"?: boolean | null;
    "effort"?: string | null;
    "verbosity"?: string | null;
    "isFavorite"?: boolean;
    "maxTokensLimit"?: number | null;
    "contextWindow"?: number | null;

    /** Creates a new ModelProfile instance. */
    constructor($$source: Partial<ModelProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("vendorId" in $$source)) {
            this["vendorId"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("modelAdapter" in $$source)) {
            this["modelAdapter"] = "";
        }
        if (!("isMultimodal" in $$source)) {
            this["isMultimodal"] = false;
        }
        if (!("isReasoning" in $$source)) {
            this["isReasoning"] = false;
        }
        if (!("isEmbedding" in $$source)) {
            this["isEmbedding"] = false;
        }
        if (!("isReranker" in $$source)) {
            this["isReranker"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelProfile($$parsedSource as Partial<ModelProfile>);
    }
}

export class OCREngineInfo {
    "engineType": string;
    "name": string;
    "description": string;
    "recommendedModel": string;
    "supportsGrounding": boolean;
    "isFree": boolean;

    /** Creates a new OCREngineInfo instance. */
    constructor($$source: Partial<OCREngineInfo> = {}) {
        if (!("engineType" in $$source)) {
            this["engineType"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("recommendedModel" in $$source)) {
            this["recommendedModel"] = "";
        }
        if (!("supportsGrounding" in $$source)) {
            this["supportsGrounding"] = false;
        }
        if (!("isFree" in $$source)) {
            this["isFree"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OCREngineInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): OCREngineInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OCREngineInfo($$parsedSource as Partial<OCREngineInfo>);
    }
}

export class OCRTestRegion {
    "text": string;
    "bbox": number[] | null;
    "label": string | null;

    /** Creates a new OCRTestRegion instance. */
    constructor($$source: Partial<OCRTestRegion> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("bbox" in $$source)) {
            this["bbox"] = null;
        }
        if (!("label" in $$source)) {
            this["label"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OCRTestRegion instance from a string or object.
     */
    static createFrom($$source: any = {}): OCRTestRegion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OCRTestRegion($$parsedSource as Partial<OCRTestRegion>);
    }
}

export class OCRTestRequest {
    "imageBase64": string;
    "engineType": string;
    "configId"?: string | null;

    /** Creates a new OCRTestRequest instance. */
    constructor($$source: Partial<OCRTestRequest> = {}) {
        if (!("imageBase64" in $$source)) {
            this["imageBase64"] = "";
        }
        if (!("engineType" in $$source)) {
            this["engineType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OCRTestRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OCRTestRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OCRTestRequest($$parsedSource as Partial<OCRTestRequest>);
    }
}

export class OCRTestResponse {
    "engineType": string;
    "engineName": string;
    "text": string;
    "regions": OCRTestRegion[];
    "elapsedMs": number;
    "success": boolean;
    "error": string | null;

    /** Creates a new OCRTestResponse instance. */
    constructor($$source: Partial<OCRTestResponse> = {}) {
        if (!("engineType" in $$source)) {
            this["engineType"] = "";
        }
        if (!("engineName" in $$source)) {
            this["engineName"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("regions" in $$source)) {
            this["regions"] = [];
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OCRTestResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): OCRTestResponse {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("regions" in $$parsedSource) {
            $$parsedSource["regions"] = $$createField3_0($$parsedSource["regions"]);
        }
        return new OCRTestResponse($$parsedSource as Partial<OCRTestResponse>);
    }
}

export class ProviderSpecialHandling {
    "handle_429_retry_after": boolean;
    "exponential_backoff_on_5xx": boolean;
    "circuit_breaker_enabled": boolean;
    "circuit_breaker_failure_threshold"?: number | null;
    "circuit_breaker_recovery_timeout_ms"?: number | null;

    /** Creates a new ProviderSpecialHandling instance. */
    constructor($$source: Partial<ProviderSpecialHandling> = {}) {
        if (!("handle_429_retry_after" in $$source)) {
            this["handle_429_retry_after"] = false;
        }
        if (!("exponential_backoff_on_5xx" in $$source)) {
            this["exponential_backoff_on_5xx"] = false;
        }
        if (!("circuit_breaker_enabled" in $$source)) {
            this["circuit_breaker_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderSpecialHandling instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderSpecialHandling {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderSpecialHandling($$parsedSource as Partial<ProviderSpecialHandling>);
    }
}

export class ProviderStrategies {
    "default": ProviderStrategy;
    "google_cse"?: ProviderStrategy | null;
    "serpapi"?: ProviderStrategy | null;
    "tavily"?: ProviderStrategy | null;
    "brave"?: ProviderStrategy | null;
    "searxng"?: ProviderStrategy | null;
    "zhipu"?: ProviderStrategy | null;
    "bocha"?: ProviderStrategy | null;

    /** Creates a new ProviderStrategies instance. */
    constructor($$source: Partial<ProviderStrategies> = {}) {
        if (!("default" in $$source)) {
            this["default"] = (new ProviderStrategy());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderStrategies instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderStrategies {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType11;
        const $$createField5_0 = $$createType11;
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default" in $$parsedSource) {
            $$parsedSource["default"] = $$createField0_0($$parsedSource["default"]);
        }
        if ("google_cse" in $$parsedSource) {
            $$parsedSource["google_cse"] = $$createField1_0($$parsedSource["google_cse"]);
        }
        if ("serpapi" in $$parsedSource) {
            $$parsedSource["serpapi"] = $$createField2_0($$parsedSource["serpapi"]);
        }
        if ("tavily" in $$parsedSource) {
            $$parsedSource["tavily"] = $$createField3_0($$parsedSource["tavily"]);
        }
        if ("brave" in $$parsedSource) {
            $$parsedSource["brave"] = $$createField4_0($$parsedSource["brave"]);
        }
        if ("searxng" in $$parsedSource) {
            $$parsedSource["searxng"] = $$createField5_0($$parsedSource["searxng"]);
        }
        if ("zhipu" in $$parsedSource) {
            $$parsedSource["zhipu"] = $$createField6_0($$parsedSource["zhipu"]);
        }
        if ("bocha" in $$parsedSource) {
            $$parsedSource["bocha"] = $$createField7_0($$parsedSource["bocha"]);
        }
        return new ProviderStrategies($$parsedSource as Partial<ProviderStrategies>);
    }
}

export class ProviderStrategiesConfigResult {
    "provider_strategies": ProviderStrategies;
    "config_keys": { [_ in string]?: string };

    /** Creates a new ProviderStrategiesConfigResult instance. */
    constructor($$source: Partial<ProviderStrategiesConfigResult> = {}) {
        if (!("provider_strategies" in $$source)) {
            this["provider_strategies"] = (new ProviderStrategies());
        }
        if (!("config_keys" in $$source)) {
            this["config_keys"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderStrategiesConfigResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderStrategiesConfigResult {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provider_strategies" in $$parsedSource) {
            $$parsedSource["provider_strategies"] = $$createField0_0($$parsedSource["provider_strategies"]);
        }
        if ("config_keys" in $$parsedSource) {
            $$parsedSource["config_keys"] = $$createField1_0($$parsedSource["config_keys"]);
        }
        return new ProviderStrategiesConfigResult($$parsedSource as Partial<ProviderStrategiesConfigResult>);
    }
}

export class ProviderStrategy {
    "timeout_ms"?: number | null;
    "max_retries"?: number | null;
    "initial_retry_delay_ms"?: number | null;
    "max_retry_delay_ms"?: number | null;
    "backoff_multiplier"?: number | null;
    "max_concurrent_requests"?: number | null;
    "rate_limit_per_minute"?: number | null;
    "cache_enabled"?: boolean | null;
    "cache_ttl_seconds"?: number | null;
    "cache_max_entries"?: number | null;
    "special_handling"?: ProviderSpecialHandling | null;

    /** Creates a new ProviderStrategy instance. */
    constructor($$source: Partial<ProviderStrategy> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderStrategy instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderStrategy {
        const $$createField10_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("special_handling" in $$parsedSource) {
            $$parsedSource["special_handling"] = $$createField10_0($$parsedSource["special_handling"]);
        }
        return new ProviderStrategy($$parsedSource as Partial<ProviderStrategy>);
    }
}

export class SaveOCRModelRequest {
    "configId": string;
    "model": string;
    "engineType": string;
    "name": string;
    "isFree": boolean;
    "enabled"?: boolean | null;
    "priority"?: number | null;

    /** Creates a new SaveOCRModelRequest instance. */
    constructor($$source: Partial<SaveOCRModelRequest> = {}) {
        if (!("configId" in $$source)) {
            this["configId"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("engineType" in $$source)) {
            this["engineType"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isFree" in $$source)) {
            this["isFree"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveOCRModelRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveOCRModelRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveOCRModelRequest($$parsedSource as Partial<SaveOCRModelRequest>);
    }
}

export class SearchEngineHealthReport {
    "results": { [_ in string]?: SearchEngineHealthStatus };
    "summary": SearchEngineHealthSummary;
    "timestamp": string;

    /** Creates a new SearchEngineHealthReport instance. */
    constructor($$source: Partial<SearchEngineHealthReport> = {}) {
        if (!("results" in $$source)) {
            this["results"] = {};
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new SearchEngineHealthSummary());
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchEngineHealthReport instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchEngineHealthReport {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField1_0($$parsedSource["summary"]);
        }
        return new SearchEngineHealthReport($$parsedSource as Partial<SearchEngineHealthReport>);
    }
}

export class SearchEngineHealthStatus {
    "name": string;
    "status": string;
    "message": string;
    "elapsed_ms": number;
    "results_count"?: number | null;

    /** Creates a new SearchEngineHealthStatus instance. */
    constructor($$source: Partial<SearchEngineHealthStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("elapsed_ms" in $$source)) {
            this["elapsed_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchEngineHealthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchEngineHealthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchEngineHealthStatus($$parsedSource as Partial<SearchEngineHealthStatus>);
    }
}

export class SearchEngineHealthSummary {
    "total": number;
    "configured": number;
    "success": number;
    "failed": number;

    /** Creates a new SearchEngineHealthSummary instance. */
    constructor($$source: Partial<SearchEngineHealthSummary> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("configured" in $$source)) {
            this["configured"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchEngineHealthSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchEngineHealthSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchEngineHealthSummary($$parsedSource as Partial<SearchEngineHealthSummary>);
    }
}

export class SearchEngineTestResult {
    "ok": boolean;
    "message": string;
    "response_time"?: number;
    "test_query"?: string;
    "error_details"?: string | null;
    "results_count"?: number | null;

    /** Creates a new SearchEngineTestResult instance. */
    constructor($$source: Partial<SearchEngineTestResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchEngineTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchEngineTestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchEngineTestResult($$parsedSource as Partial<SearchEngineTestResult>);
    }
}

export class UpdateOCRPriorityItem {
    "configId": string;
    "enabled": boolean;

    /** Creates a new UpdateOCRPriorityItem instance. */
    constructor($$source: Partial<UpdateOCRPriorityItem> = {}) {
        if (!("configId" in $$source)) {
            this["configId"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateOCRPriorityItem instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateOCRPriorityItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateOCRPriorityItem($$parsedSource as Partial<UpdateOCRPriorityItem>);
    }
}

export class VendorConfig {
    "id": string;
    "name": string;
    "providerType": string;
    "apiProtocol"?: string | null;
    "supportsOpenAIResponses"?: boolean | null;
    "baseUrl": string;
    "apiKey": string;
    "headers"?: { [_ in string]?: string };
    "rateLimitPerMinute"?: number | null;
    "defaultTimeoutMs"?: number | null;
    "notes"?: string | null;
    "isBuiltin"?: boolean;
    "isReadOnly"?: boolean;
    "sortOrder"?: number | null;
    "maxTokensLimit"?: number | null;
    "websiteUrl"?: string | null;

    /** Creates a new VendorConfig instance. */
    constructor($$source: Partial<VendorConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("providerType" in $$source)) {
            this["providerType"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VendorConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): VendorConfig {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField7_0($$parsedSource["headers"]);
        }
        return new VendorConfig($$parsedSource as Partial<VendorConfig>);
    }
}

export class WebSearchConnectivityResult {
    "success": boolean;
    "usage"?: { [_ in string]?: any };
    "detail"?: SearchEngineTestResult;

    /** Creates a new WebSearchConnectivityResult instance. */
    constructor($$source: Partial<WebSearchConnectivityResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebSearchConnectivityResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WebSearchConnectivityResult {
        const $$createField1_0 = $$createType18;
        const $$createField2_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField1_0($$parsedSource["usage"]);
        }
        if ("detail" in $$parsedSource) {
            $$parsedSource["detail"] = $$createField2_0($$parsedSource["detail"]);
        }
        return new WebSearchConnectivityResult($$parsedSource as Partial<WebSearchConnectivityResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = CNWhitelistUserConfig.createFrom;
const $$createType5 = BasicStatistics.createFrom;
const $$createType6 = ImageStatistics.createFrom;
const $$createType7 = MCPCacheState.createFrom;
const $$createType8 = OCRTestRegion.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = ProviderStrategy.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = ProviderStrategies.createFrom;
const $$createType13 = ProviderSpecialHandling.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = SearchEngineHealthStatus.createFrom;
const $$createType16 = $Create.Map($Create.Any, $$createType15);
const $$createType17 = SearchEngineHealthSummary.createFrom;
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = SearchEngineTestResult.createFrom;
