// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DirectoryEntry {
    "name": string;
    "path": string;

    /** Creates a new DirectoryEntry instance. */
    constructor($$source: Partial<DirectoryEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DirectoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirectoryEntry($$parsedSource as Partial<DirectoryEntry>);
    }
}

export class FileContent {
    "content": string;
    "path": string;

    /** Creates a new FileContent instance. */
    constructor($$source: Partial<FileContent> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent($$parsedSource as Partial<FileContent>);
    }
}
