// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AddTextbooksRequest {
    "sources": string[];
    "folderId"?: string | null;

    /** Creates a new AddTextbooksRequest instance. */
    constructor($$source: Partial<AddTextbooksRequest> = {}) {
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddTextbooksRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AddTextbooksRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField0_0($$parsedSource["sources"]);
        }
        return new AddTextbooksRequest($$parsedSource as Partial<AddTextbooksRequest>);
    }
}

export class BatchMoveRequest {
    "itemIds": string[];
    "targetFolderId": string | null;

    /** Creates a new BatchMoveRequest instance. */
    constructor($$source: Partial<BatchMoveRequest> = {}) {
        if (!("itemIds" in $$source)) {
            this["itemIds"] = [];
        }
        if (!("targetFolderId" in $$source)) {
            this["targetFolderId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchMoveRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchMoveRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("itemIds" in $$parsedSource) {
            $$parsedSource["itemIds"] = $$createField0_0($$parsedSource["itemIds"]);
        }
        return new BatchMoveRequest($$parsedSource as Partial<BatchMoveRequest>);
    }
}

export class BatchMoveResult {
    "successes": ResourceLocation[];
    "failedItems": FailedMoveItem[];
    "totalCount": number;

    /** Creates a new BatchMoveResult instance. */
    constructor($$source: Partial<BatchMoveResult> = {}) {
        if (!("successes" in $$source)) {
            this["successes"] = [];
        }
        if (!("failedItems" in $$source)) {
            this["failedItems"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchMoveResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchMoveResult {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("successes" in $$parsedSource) {
            $$parsedSource["successes"] = $$createField0_0($$parsedSource["successes"]);
        }
        if ("failedItems" in $$parsedSource) {
            $$parsedSource["failedItems"] = $$createField1_0($$parsedSource["failedItems"]);
        }
        return new BatchMoveResult($$parsedSource as Partial<BatchMoveResult>);
    }
}

export class BreadcrumbItem {
    "id": string;
    "name": string;

    /** Creates a new BreadcrumbItem instance. */
    constructor($$source: Partial<BreadcrumbItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BreadcrumbItem instance from a string or object.
     */
    static createFrom($$source: any = {}): BreadcrumbItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BreadcrumbItem($$parsedSource as Partial<BreadcrumbItem>);
    }
}

export class CreateOptions {
    "type": string;
    "name": string;
    "content"?: string | null;
    "fileBase64"?: string | null;
    "metadata"?: { [_ in string]?: any };

    /** Creates a new CreateOptions instance. */
    constructor($$source: Partial<CreateOptions> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateOptions {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField4_0($$parsedSource["metadata"]);
        }
        return new CreateOptions($$parsedSource as Partial<CreateOptions>);
    }
}

export class FailedMoveItem {
    "itemId": string;
    "error": string;

    /** Creates a new FailedMoveItem instance. */
    constructor($$source: Partial<FailedMoveItem> = {}) {
        if (!("itemId" in $$source)) {
            this["itemId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FailedMoveItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FailedMoveItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FailedMoveItem($$parsedSource as Partial<FailedMoveItem>);
    }
}

export class FolderResourceInfo {
    "itemType": string;
    "itemId": string;
    "resourceId"?: string | null;
    "title": string;
    "path": string;
    "content"?: string | null;

    /** Creates a new FolderResourceInfo instance. */
    constructor($$source: Partial<FolderResourceInfo> = {}) {
        if (!("itemType" in $$source)) {
            this["itemType"] = "";
        }
        if (!("itemId" in $$source)) {
            this["itemId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderResourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderResourceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderResourceInfo($$parsedSource as Partial<FolderResourceInfo>);
    }
}

export class FolderResourcesResult {
    "folderId": string;
    "folderTitle": string;
    "path": string;
    "totalCount": number;
    "resources": FolderResourceInfo[];

    /** Creates a new FolderResourcesResult instance. */
    constructor($$source: Partial<FolderResourcesResult> = {}) {
        if (!("folderId" in $$source)) {
            this["folderId"] = "";
        }
        if (!("folderTitle" in $$source)) {
            this["folderTitle"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("resources" in $$source)) {
            this["resources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderResourcesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderResourcesResult {
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField4_0($$parsedSource["resources"]);
        }
        return new FolderResourcesResult($$parsedSource as Partial<FolderResourcesResult>);
    }
}

export class FolderTreeNode {
    "folder": VfsFolder;
    "children": FolderTreeNode[];
    "items": VfsFolderItem[];

    /** Creates a new FolderTreeNode instance. */
    constructor($$source: Partial<FolderTreeNode> = {}) {
        if (!("folder" in $$source)) {
            this["folder"] = (new VfsFolder());
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderTreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderTreeNode {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folder" in $$parsedSource) {
            $$parsedSource["folder"] = $$createField0_0($$parsedSource["folder"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        return new FolderTreeNode($$parsedSource as Partial<FolderTreeNode>);
    }
}

export class ImportMarkdownBatchFailure {
    "file_path": string;
    "message": string;

    /** Creates a new ImportMarkdownBatchFailure instance. */
    constructor($$source: Partial<ImportMarkdownBatchFailure> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMarkdownBatchFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMarkdownBatchFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportMarkdownBatchFailure($$parsedSource as Partial<ImportMarkdownBatchFailure>);
    }
}

export class ImportMarkdownBatchItem {
    "filePath": string;
    "titleHint"?: string | null;

    /** Creates a new ImportMarkdownBatchItem instance. */
    constructor($$source: Partial<ImportMarkdownBatchItem> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMarkdownBatchItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMarkdownBatchItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportMarkdownBatchItem($$parsedSource as Partial<ImportMarkdownBatchItem>);
    }
}

export class ImportMarkdownBatchRequest {
    "items": ImportMarkdownBatchItem[];
    "folderId"?: string | null;

    /** Creates a new ImportMarkdownBatchRequest instance. */
    constructor($$source: Partial<ImportMarkdownBatchRequest> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMarkdownBatchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMarkdownBatchRequest {
        const $$createField0_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ImportMarkdownBatchRequest($$parsedSource as Partial<ImportMarkdownBatchRequest>);
    }
}

export class ImportMarkdownBatchResponse {
    "imported": Node[];
    "failed": ImportMarkdownBatchFailure[];

    /** Creates a new ImportMarkdownBatchResponse instance. */
    constructor($$source: Partial<ImportMarkdownBatchResponse> = {}) {
        if (!("imported" in $$source)) {
            this["imported"] = [];
        }
        if (!("failed" in $$source)) {
            this["failed"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMarkdownBatchResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMarkdownBatchResponse {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("imported" in $$parsedSource) {
            $$parsedSource["imported"] = $$createField0_0($$parsedSource["imported"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new ImportMarkdownBatchResponse($$parsedSource as Partial<ImportMarkdownBatchResponse>);
    }
}

export class ImportMarkdownRequest {
    "filePath": string;
    "titleHint"?: string | null;
    "folderId"?: string | null;

    /** Creates a new ImportMarkdownRequest instance. */
    constructor($$source: Partial<ImportMarkdownRequest> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportMarkdownRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportMarkdownRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportMarkdownRequest($$parsedSource as Partial<ImportMarkdownRequest>);
    }
}

export class ListOptions {
    "folderId"?: string | null;
    "typeFilter"?: string | null;
    "isFavorite"?: boolean | null;
    "recursive"?: boolean | null;
    "types"?: string[];
    "search"?: string | null;
    "tags"?: string[];
    "sortBy"?: string | null;
    "sortOrder"?: string | null;
    "limit"?: number | null;
    "offset"?: number | null;

    /** Creates a new ListOptions instance. */
    constructor($$source: Partial<ListOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ListOptions {
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField4_0($$parsedSource["types"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new ListOptions($$parsedSource as Partial<ListOptions>);
    }
}

export class Node {
    "id": string;
    "path": string;
    "name": string;
    "type": string;
    "size"?: number;
    "createdAt": number;
    "updatedAt": number;
    "resourceId"?: string;
    "sourceId": string;
    "resourceHash"?: string;
    "previewType"?: string;
    "metadata"?: { [_ in string]?: any };

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField11_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField11_0($$parsedSource["metadata"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

export class NotesSearchHit {
    "id": string;
    "title": string;
    "snippet"?: string | null;

    /** Creates a new NotesSearchHit instance. */
    constructor($$source: Partial<NotesSearchHit> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotesSearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): NotesSearchHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotesSearchHit($$parsedSource as Partial<NotesSearchHit>);
    }
}

export class ParsedPath {
    "fullPath": string;
    "folderPath": string | null;
    "resourceId": string | null;
    "id": string | null;
    "resourceType": string | null;
    "isRoot": boolean;
    "isVirtual": boolean;
    "virtualType"?: string | null;

    /** Creates a new ParsedPath instance. */
    constructor($$source: Partial<ParsedPath> = {}) {
        if (!("fullPath" in $$source)) {
            this["fullPath"] = "";
        }
        if (!("folderPath" in $$source)) {
            this["folderPath"] = null;
        }
        if (!("resourceId" in $$source)) {
            this["resourceId"] = null;
        }
        if (!("id" in $$source)) {
            this["id"] = null;
        }
        if (!("resourceType" in $$source)) {
            this["resourceType"] = null;
        }
        if (!("isRoot" in $$source)) {
            this["isRoot"] = false;
        }
        if (!("isVirtual" in $$source)) {
            this["isVirtual"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParsedPath instance from a string or object.
     */
    static createFrom($$source: any = {}): ParsedPath {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParsedPath($$parsedSource as Partial<ParsedPath>);
    }
}

export class ResourceLocation {
    "id": string;
    "resourceType": string;
    "folderId": string | null;
    "folderPath": string;
    "fullPath": string;
    "hash"?: string | null;

    /** Creates a new ResourceLocation instance. */
    constructor($$source: Partial<ResourceLocation> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("resourceType" in $$source)) {
            this["resourceType"] = "";
        }
        if (!("folderId" in $$source)) {
            this["folderId"] = null;
        }
        if (!("folderPath" in $$source)) {
            this["folderPath"] = "";
        }
        if (!("fullPath" in $$source)) {
            this["fullPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceLocation instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceLocation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceLocation($$parsedSource as Partial<ResourceLocation>);
    }
}

export class TextbookRecord {
    "id": string;
    "sha256": string;
    "file_name": string;
    "file_path": string;
    "size": number;
    "page_count"?: number | null;
    "tags_json": string;
    "favorite": number;
    "last_opened_at"?: string | null;
    "last_page"?: number | null;
    "bookmarks_json": string;
    "cover_key"?: string | null;
    "origin_json"?: string | null;
    "status": string;
    "created_at": string;
    "updated_at": string;
    "resource_id"?: string;
    "resource_hash"?: string;
    "preview_type"?: string;
    "metadata"?: { [_ in string]?: any };

    /** Creates a new TextbookRecord instance. */
    constructor($$source: Partial<TextbookRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("tags_json" in $$source)) {
            this["tags_json"] = "";
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = 0;
        }
        if (!("bookmarks_json" in $$source)) {
            this["bookmarks_json"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextbookRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): TextbookRecord {
        const $$createField19_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField19_0($$parsedSource["metadata"]);
        }
        return new TextbookRecord($$parsedSource as Partial<TextbookRecord>);
    }
}

export class VfsFolder {
    "id": string;
    "parentId": string | null;
    "title": string;
    "icon"?: string | null;
    "color"?: string | null;
    "isExpanded": boolean;
    "sortOrder": number;
    "isBuiltin"?: boolean;
    "builtinType"?: string | null;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new VfsFolder instance. */
    constructor($$source: Partial<VfsFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = null;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("isExpanded" in $$source)) {
            this["isExpanded"] = false;
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VfsFolder($$parsedSource as Partial<VfsFolder>);
    }
}

export class VfsFolderItem {
    "id": string;
    "folderId": string | null;
    "itemType": string;
    "itemId": string;
    "sortOrder": number;
    "createdAt": number;
    "updatedAt"?: number;
    "cachedPath"?: string | null;

    /** Creates a new VfsFolderItem instance. */
    constructor($$source: Partial<VfsFolderItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("folderId" in $$source)) {
            this["folderId"] = null;
        }
        if (!("itemType" in $$source)) {
            this["itemType"] = "";
        }
        if (!("itemId" in $$source)) {
            this["itemId"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsFolderItem instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsFolderItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VfsFolderItem($$parsedSource as Partial<VfsFolderItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ResourceLocation.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FailedMoveItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = FolderResourceInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = VfsFolder.createFrom;
const $$createType9 = FolderTreeNode.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = VfsFolderItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ImportMarkdownBatchItem.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Node.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = ImportMarkdownBatchFailure.createFrom;
const $$createType18 = $Create.Array($$createType17);
