// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DocumentProcessingState {
    "status": string;
    "total_tasks": number;
    "completed_tasks": number;
    "failed_tasks": number;
    "paused_tasks": number;

    /** Creates a new DocumentProcessingState instance. */
    constructor($$source: Partial<DocumentProcessingState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("total_tasks" in $$source)) {
            this["total_tasks"] = 0;
        }
        if (!("completed_tasks" in $$source)) {
            this["completed_tasks"] = 0;
        }
        if (!("failed_tasks" in $$source)) {
            this["failed_tasks"] = 0;
        }
        if (!("paused_tasks" in $$source)) {
            this["paused_tasks"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentProcessingState instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentProcessingState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentProcessingState($$parsedSource as Partial<DocumentProcessingState>);
    }
}

export class DocumentTask {
    "id": string;
    "task_id"?: string;
    "document_id": string;
    "original_document_name": string;
    "segment_index": number;
    "content_segment": string;
    "status": string;
    "created_at": string;
    "updated_at": string;
    "error_message"?: string | null;
    "anki_generation_options_json": string;
    "cards_generated"?: number;
    "is_retry"?: boolean;

    /** Creates a new DocumentTask instance. */
    constructor($$source: Partial<DocumentTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("document_id" in $$source)) {
            this["document_id"] = "";
        }
        if (!("original_document_name" in $$source)) {
            this["original_document_name"] = "";
        }
        if (!("segment_index" in $$source)) {
            this["segment_index"] = 0;
        }
        if (!("content_segment" in $$source)) {
            this["content_segment"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("anki_generation_options_json" in $$source)) {
            this["anki_generation_options_json"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentTask instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentTask($$parsedSource as Partial<DocumentTask>);
    }
}

export class DocumentTaskCounts {
    "total": number;
    "pending": number;
    "processing": number;
    "streaming": number;
    "paused": number;
    "completed": number;
    "failed": number;
    "truncated": number;
    "cancelled": number;

    /** Creates a new DocumentTaskCounts instance. */
    constructor($$source: Partial<DocumentTaskCounts> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("processing" in $$source)) {
            this["processing"] = 0;
        }
        if (!("streaming" in $$source)) {
            this["streaming"] = 0;
        }
        if (!("paused" in $$source)) {
            this["paused"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = 0;
        }
        if (!("cancelled" in $$source)) {
            this["cancelled"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentTaskCounts instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentTaskCounts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentTaskCounts($$parsedSource as Partial<DocumentTaskCounts>);
    }
}

export class SaveAnkiCardPayload {
    "id"?: string | null;
    "front"?: string | null;
    "back"?: string | null;
    "text"?: string | null;
    "tags"?: string[];
    "images"?: string[];
    "fields"?: { [_ in string]?: string };
    "extra_fields"?: { [_ in string]?: string };
    "template_id"?: string | null;

    /** Creates a new SaveAnkiCardPayload instance. */
    constructor($$source: Partial<SaveAnkiCardPayload> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveAnkiCardPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveAnkiCardPayload {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField5_0($$parsedSource["images"]);
        }
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField6_0($$parsedSource["fields"]);
        }
        if ("extra_fields" in $$parsedSource) {
            $$parsedSource["extra_fields"] = $$createField7_0($$parsedSource["extra_fields"]);
        }
        return new SaveAnkiCardPayload($$parsedSource as Partial<SaveAnkiCardPayload>);
    }
}

export class SaveAnkiCardsRequest {
    "document_id"?: string | null;
    "business_session_id"?: string | null;
    "message_stable_id"?: string | null;
    "block_id"?: string | null;
    "template_id"?: string | null;
    "cards": SaveAnkiCardPayload[];
    "options"?: { [_ in string]?: any };

    /** Creates a new SaveAnkiCardsRequest instance. */
    constructor($$source: Partial<SaveAnkiCardsRequest> = {}) {
        if (!("cards" in $$source)) {
            this["cards"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveAnkiCardsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveAnkiCardsRequest {
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cards" in $$parsedSource) {
            $$parsedSource["cards"] = $$createField5_0($$parsedSource["cards"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new SaveAnkiCardsRequest($$parsedSource as Partial<SaveAnkiCardsRequest>);
    }
}

export class SaveAnkiCardsResponse {
    "saved_ids": string[];
    "task_id": string;

    /** Creates a new SaveAnkiCardsResponse instance. */
    constructor($$source: Partial<SaveAnkiCardsResponse> = {}) {
        if (!("saved_ids" in $$source)) {
            this["saved_ids"] = [];
        }
        if (!("task_id" in $$source)) {
            this["task_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveAnkiCardsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveAnkiCardsResponse {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("saved_ids" in $$parsedSource) {
            $$parsedSource["saved_ids"] = $$createField0_0($$parsedSource["saved_ids"]);
        }
        return new SaveAnkiCardsResponse($$parsedSource as Partial<SaveAnkiCardsResponse>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = SaveAnkiCardPayload.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
