// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActivityHeatmapPoint {
    "date": string;
    "count": number;
    "correct_count": number;
    "level": number;

    /** Creates a new ActivityHeatmapPoint instance. */
    constructor($$source: Partial<ActivityHeatmapPoint> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityHeatmapPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): ActivityHeatmapPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityHeatmapPoint($$parsedSource as Partial<ActivityHeatmapPoint>);
    }
}

export class AnswerSubmission {
    "id": string;
    "question_id": string;
    "user_answer": string;
    "is_correct": boolean | null;
    "client_request_id"?: string | null;
    "created_at": string;

    /** Creates a new AnswerSubmission instance. */
    constructor($$source: Partial<AnswerSubmission> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("user_answer" in $$source)) {
            this["user_answer"] = "";
        }
        if (!("is_correct" in $$source)) {
            this["is_correct"] = null;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnswerSubmission instance from a string or object.
     */
    static createFrom($$source: any = {}): AnswerSubmission {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnswerSubmission($$parsedSource as Partial<AnswerSubmission>);
    }
}

export class BatchResult {
    "success_count": number;
    "failed_count": number;
    "errors": string[];

    /** Creates a new BatchResult instance. */
    constructor($$source: Partial<BatchResult> = {}) {
        if (!("success_count" in $$source)) {
            this["success_count"] = 0;
        }
        if (!("failed_count" in $$source)) {
            this["failed_count"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField2_0($$parsedSource["errors"]);
        }
        return new BatchResult($$parsedSource as Partial<BatchResult>);
    }
}

export class CheckInCalendar {
    "year": number;
    "month": number;
    "days": DailyCheckIn[];
    "streak_days": number;
    "month_check_in_days": number;
    "month_total_questions": number;

    /** Creates a new CheckInCalendar instance. */
    constructor($$source: Partial<CheckInCalendar> = {}) {
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("month" in $$source)) {
            this["month"] = 0;
        }
        if (!("days" in $$source)) {
            this["days"] = [];
        }
        if (!("streak_days" in $$source)) {
            this["streak_days"] = 0;
        }
        if (!("month_check_in_days" in $$source)) {
            this["month_check_in_days"] = 0;
        }
        if (!("month_total_questions" in $$source)) {
            this["month_total_questions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckInCalendar instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckInCalendar {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("days" in $$parsedSource) {
            $$parsedSource["days"] = $$createField2_0($$parsedSource["days"]);
        }
        return new CheckInCalendar($$parsedSource as Partial<CheckInCalendar>);
    }
}

export class CreateQuestionParams {
    "exam_id": string;
    "content": string;
    "question_type"?: string | null;
    "options"?: QuestionOption[];
    "answer"?: string | null;
    "explanation"?: string | null;
    "difficulty"?: string | null;
    "tags"?: string[];
    "question_label"?: string | null;
    "card_id"?: string | null;
    "source_type"?: string | null;
    "source_ref"?: string | null;
    "images"?: QuestionImage[];
    "parent_id"?: string | null;

    /** Creates a new CreateQuestionParams instance. */
    constructor($$source: Partial<CreateQuestionParams> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateQuestionParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateQuestionParams {
        const $$createField3_0 = $$createType4;
        const $$createField7_0 = $$createType0;
        const $$createField12_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField12_0($$parsedSource["images"]);
        }
        return new CreateQuestionParams($$parsedSource as Partial<CreateQuestionParams>);
    }
}

export enum CsvDuplicateStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CsvDuplicateSkip = "skip",
    CsvDuplicateOverwrite = "overwrite",
    CsvDuplicateMerge = "merge",
};

export class CsvExportRequest {
    "exam_id": string;
    "file_path": string;
    "fields"?: string[];
    "filters"?: QuestionFilters | null;
    "include_answers"?: boolean;
    "encoding"?: string;

    /** Creates a new CsvExportRequest instance. */
    constructor($$source: Partial<CsvExportRequest> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvExportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvExportRequest {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField3_0($$parsedSource["filters"]);
        }
        return new CsvExportRequest($$parsedSource as Partial<CsvExportRequest>);
    }
}

export class CsvExportResult {
    "exported_count": number;
    "file_path": string;
    "file_size": number;

    /** Creates a new CsvExportResult instance. */
    constructor($$source: Partial<CsvExportResult> = {}) {
        if (!("exported_count" in $$source)) {
            this["exported_count"] = 0;
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CsvExportResult($$parsedSource as Partial<CsvExportResult>);
    }
}

export class CsvImportError {
    "row": number;
    "message": string;
    "raw_data"?: string | null;

    /** Creates a new CsvImportError instance. */
    constructor($$source: Partial<CsvImportError> = {}) {
        if (!("row" in $$source)) {
            this["row"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvImportError instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvImportError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CsvImportError($$parsedSource as Partial<CsvImportError>);
    }
}

export class CsvImportRequest {
    "file_path": string;
    "exam_id": string;
    "field_mapping": { [_ in string]?: string };
    "duplicate_strategy"?: CsvDuplicateStrategy;
    "folder_id"?: string | null;
    "exam_name"?: string | null;

    /** Creates a new CsvImportRequest instance. */
    constructor($$source: Partial<CsvImportRequest> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("field_mapping" in $$source)) {
            this["field_mapping"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvImportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvImportRequest {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("field_mapping" in $$parsedSource) {
            $$parsedSource["field_mapping"] = $$createField2_0($$parsedSource["field_mapping"]);
        }
        return new CsvImportRequest($$parsedSource as Partial<CsvImportRequest>);
    }
}

export class CsvImportResult {
    "success_count": number;
    "skipped_count": number;
    "failed_count": number;
    "errors": CsvImportError[];
    "exam_id": string;
    "total_rows": number;

    /** Creates a new CsvImportResult instance. */
    constructor($$source: Partial<CsvImportResult> = {}) {
        if (!("success_count" in $$source)) {
            this["success_count"] = 0;
        }
        if (!("skipped_count" in $$source)) {
            this["skipped_count"] = 0;
        }
        if (!("failed_count" in $$source)) {
            this["failed_count"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("total_rows" in $$source)) {
            this["total_rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvImportResult {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new CsvImportResult($$parsedSource as Partial<CsvImportResult>);
    }
}

export class CsvPreviewResult {
    "headers": string[];
    "rows": string[][];
    "total_rows": number;
    "encoding": string;

    /** Creates a new CsvPreviewResult instance. */
    constructor($$source: Partial<CsvPreviewResult> = {}) {
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("total_rows" in $$source)) {
            this["total_rows"] = 0;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CsvPreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CsvPreviewResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField0_0($$parsedSource["headers"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new CsvPreviewResult($$parsedSource as Partial<CsvPreviewResult>);
    }
}

export class DailyCheckIn {
    "date": string;
    "exam_id"?: string | null;
    "question_count": number;
    "correct_count": number;
    "study_duration_seconds": number;
    "target_achieved": boolean;

    /** Creates a new DailyCheckIn instance. */
    constructor($$source: Partial<DailyCheckIn> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("question_count" in $$source)) {
            this["question_count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("study_duration_seconds" in $$source)) {
            this["study_duration_seconds"] = 0;
        }
        if (!("target_achieved" in $$source)) {
            this["target_achieved"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyCheckIn instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyCheckIn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyCheckIn($$parsedSource as Partial<DailyCheckIn>);
    }
}

export class DailyPracticeResult {
    "date": string;
    "exam_id": string;
    "question_ids": string[];
    "daily_target": number;
    "completed_count": number;
    "correct_count": number;
    "source_distribution": DailySourceDistribution;
    "is_completed": boolean;

    /** Creates a new DailyPracticeResult instance. */
    constructor($$source: Partial<DailyPracticeResult> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("question_ids" in $$source)) {
            this["question_ids"] = [];
        }
        if (!("daily_target" in $$source)) {
            this["daily_target"] = 0;
        }
        if (!("completed_count" in $$source)) {
            this["completed_count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("source_distribution" in $$source)) {
            this["source_distribution"] = (new DailySourceDistribution());
        }
        if (!("is_completed" in $$source)) {
            this["is_completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyPracticeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyPracticeResult {
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("question_ids" in $$parsedSource) {
            $$parsedSource["question_ids"] = $$createField2_0($$parsedSource["question_ids"]);
        }
        if ("source_distribution" in $$parsedSource) {
            $$parsedSource["source_distribution"] = $$createField6_0($$parsedSource["source_distribution"]);
        }
        return new DailyPracticeResult($$parsedSource as Partial<DailyPracticeResult>);
    }
}

export class DailySourceDistribution {
    "mistake_count": number;
    "new_count": number;
    "review_count": number;

    /** Creates a new DailySourceDistribution instance. */
    constructor($$source: Partial<DailySourceDistribution> = {}) {
        if (!("mistake_count" in $$source)) {
            this["mistake_count"] = 0;
        }
        if (!("new_count" in $$source)) {
            this["new_count"] = 0;
        }
        if (!("review_count" in $$source)) {
            this["review_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailySourceDistribution instance from a string or object.
     */
    static createFrom($$source: any = {}): DailySourceDistribution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailySourceDistribution($$parsedSource as Partial<DailySourceDistribution>);
    }
}

export class DifficultyStatItem {
    "total": number;
    "correct": number;
    "rate": number;

    /** Creates a new DifficultyStatItem instance. */
    constructor($$source: Partial<DifficultyStatItem> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("correct" in $$source)) {
            this["correct"] = 0;
        }
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DifficultyStatItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DifficultyStatItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DifficultyStatItem($$parsedSource as Partial<DifficultyStatItem>);
    }
}

export class GenerateMockExamRequest {
    "exam_id": string;
    "config": MockExamConfig;

    /** Creates a new GenerateMockExamRequest instance. */
    constructor($$source: Partial<GenerateMockExamRequest> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new MockExamConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateMockExamRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateMockExamRequest {
        const $$createField1_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new GenerateMockExamRequest($$parsedSource as Partial<GenerateMockExamRequest>);
    }
}

export class GeneratePaperRequest {
    "exam_id": string;
    "config": PaperConfig;

    /** Creates a new GeneratePaperRequest instance. */
    constructor($$source: Partial<GeneratePaperRequest> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new PaperConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratePaperRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneratePaperRequest {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new GeneratePaperRequest($$parsedSource as Partial<GeneratePaperRequest>);
    }
}

export class GeneratedPaper {
    "id": string;
    "title": string;
    "exam_id": string;
    "questions": Question[];
    "total_score": number;
    "config": PaperConfig;
    "created_at": string;
    "export_path"?: string | null;

    /** Creates a new GeneratedPaper instance. */
    constructor($$source: Partial<GeneratedPaper> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("questions" in $$source)) {
            this["questions"] = [];
        }
        if (!("total_score" in $$source)) {
            this["total_score"] = 0;
        }
        if (!("config" in $$source)) {
            this["config"] = (new PaperConfig());
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratedPaper instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneratedPaper {
        const $$createField3_0 = $$createType17;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField3_0($$parsedSource["questions"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField5_0($$parsedSource["config"]);
        }
        return new GeneratedPaper($$parsedSource as Partial<GeneratedPaper>);
    }
}

export class GetActivityHeatmapRequest {
    "exam_id"?: string | null;
    "year": number;

    /** Creates a new GetActivityHeatmapRequest instance. */
    constructor($$source: Partial<GetActivityHeatmapRequest> = {}) {
        if (!("year" in $$source)) {
            this["year"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetActivityHeatmapRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetActivityHeatmapRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetActivityHeatmapRequest($$parsedSource as Partial<GetActivityHeatmapRequest>);
    }
}

export class GetCheckInCalendarRequest {
    "exam_id"?: string | null;
    "year": number;
    "month": number;

    /** Creates a new GetCheckInCalendarRequest instance. */
    constructor($$source: Partial<GetCheckInCalendarRequest> = {}) {
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("month" in $$source)) {
            this["month"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetCheckInCalendarRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetCheckInCalendarRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetCheckInCalendarRequest($$parsedSource as Partial<GetCheckInCalendarRequest>);
    }
}

export class GetDailyPracticeRequest {
    "exam_id": string;
    "count": number;

    /** Creates a new GetDailyPracticeRequest instance. */
    constructor($$source: Partial<GetDailyPracticeRequest> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetDailyPracticeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetDailyPracticeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetDailyPracticeRequest($$parsedSource as Partial<GetDailyPracticeRequest>);
    }
}

export class GetKnowledgeStatsRequest {
    "exam_id"?: string | null;

    /** Creates a new GetKnowledgeStatsRequest instance. */
    constructor($$source: Partial<GetKnowledgeStatsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetKnowledgeStatsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetKnowledgeStatsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetKnowledgeStatsRequest($$parsedSource as Partial<GetKnowledgeStatsRequest>);
    }
}

export class GetLearningTrendRequest {
    "exam_id"?: string | null;
    "start_date": string;
    "end_date": string;

    /** Creates a new GetLearningTrendRequest instance. */
    constructor($$source: Partial<GetLearningTrendRequest> = {}) {
        if (!("start_date" in $$source)) {
            this["start_date"] = "";
        }
        if (!("end_date" in $$source)) {
            this["end_date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetLearningTrendRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetLearningTrendRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetLearningTrendRequest($$parsedSource as Partial<GetLearningTrendRequest>);
    }
}

export class KnowledgePoint {
    "tag": string;
    "total": number;
    "mastered": number;
    "in_progress": number;
    "review": number;
    "new_count": number;
    "mastery_rate": number;
    "correct_rate": number;

    /** Creates a new KnowledgePoint instance. */
    constructor($$source: Partial<KnowledgePoint> = {}) {
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("mastered" in $$source)) {
            this["mastered"] = 0;
        }
        if (!("in_progress" in $$source)) {
            this["in_progress"] = 0;
        }
        if (!("review" in $$source)) {
            this["review"] = 0;
        }
        if (!("new_count" in $$source)) {
            this["new_count"] = 0;
        }
        if (!("mastery_rate" in $$source)) {
            this["mastery_rate"] = 0;
        }
        if (!("correct_rate" in $$source)) {
            this["correct_rate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgePoint instance from a string or object.
     */
    static createFrom($$source: any = {}): KnowledgePoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnowledgePoint($$parsedSource as Partial<KnowledgePoint>);
    }
}

export class KnowledgeStatsComparison {
    "current": KnowledgePoint[];
    "previous": KnowledgePoint[];

    /** Creates a new KnowledgeStatsComparison instance. */
    constructor($$source: Partial<KnowledgeStatsComparison> = {}) {
        if (!("current" in $$source)) {
            this["current"] = [];
        }
        if (!("previous" in $$source)) {
            this["previous"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeStatsComparison instance from a string or object.
     */
    static createFrom($$source: any = {}): KnowledgeStatsComparison {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("current" in $$parsedSource) {
            $$parsedSource["current"] = $$createField0_0($$parsedSource["current"]);
        }
        if ("previous" in $$parsedSource) {
            $$parsedSource["previous"] = $$createField1_0($$parsedSource["previous"]);
        }
        return new KnowledgeStatsComparison($$parsedSource as Partial<KnowledgeStatsComparison>);
    }
}

export class LearningTrendPoint {
    "date": string;
    "attempt_count": number;
    "correct_count": number;
    "correct_rate": number;

    /** Creates a new LearningTrendPoint instance. */
    constructor($$source: Partial<LearningTrendPoint> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("attempt_count" in $$source)) {
            this["attempt_count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("correct_rate" in $$source)) {
            this["correct_rate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LearningTrendPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): LearningTrendPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LearningTrendPoint($$parsedSource as Partial<LearningTrendPoint>);
    }
}

export class ListQuestionsRequest {
    "exam_id": string;
    "filters"?: QuestionFilters | null;
    "page"?: number;
    "page_size"?: number;

    /** Creates a new ListQuestionsRequest instance. */
    constructor($$source: Partial<ListQuestionsRequest> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListQuestionsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListQuestionsRequest {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField1_0($$parsedSource["filters"]);
        }
        return new ListQuestionsRequest($$parsedSource as Partial<ListQuestionsRequest>);
    }
}

export class MockExamConfig {
    "duration_minutes": number;
    "type_distribution": { [_ in string]?: number };
    "difficulty_distribution": { [_ in string]?: number };
    "total_count"?: number | null;
    "shuffle": boolean;
    "include_mistakes": boolean;
    "tags"?: string[];

    /** Creates a new MockExamConfig instance. */
    constructor($$source: Partial<MockExamConfig> = {}) {
        if (!("duration_minutes" in $$source)) {
            this["duration_minutes"] = 0;
        }
        if (!("type_distribution" in $$source)) {
            this["type_distribution"] = {};
        }
        if (!("difficulty_distribution" in $$source)) {
            this["difficulty_distribution"] = {};
        }
        if (!("shuffle" in $$source)) {
            this["shuffle"] = false;
        }
        if (!("include_mistakes" in $$source)) {
            this["include_mistakes"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MockExamConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MockExamConfig {
        const $$createField1_0 = $$createType20;
        const $$createField2_0 = $$createType20;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("type_distribution" in $$parsedSource) {
            $$parsedSource["type_distribution"] = $$createField1_0($$parsedSource["type_distribution"]);
        }
        if ("difficulty_distribution" in $$parsedSource) {
            $$parsedSource["difficulty_distribution"] = $$createField2_0($$parsedSource["difficulty_distribution"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new MockExamConfig($$parsedSource as Partial<MockExamConfig>);
    }
}

export class MockExamScoreCard {
    "session_id": string;
    "exam_id": string;
    "total_count": number;
    "answered_count": number;
    "correct_count": number;
    "wrong_count": number;
    "unanswered_count": number;
    "correct_rate": number;
    "time_spent_seconds": number;
    "type_stats": { [_ in string]?: TypeStatItem };
    "difficulty_stats": { [_ in string]?: DifficultyStatItem };
    "wrong_question_ids": string[];
    "comment": string;
    "completed_at": string;

    /** Creates a new MockExamScoreCard instance. */
    constructor($$source: Partial<MockExamScoreCard> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("total_count" in $$source)) {
            this["total_count"] = 0;
        }
        if (!("answered_count" in $$source)) {
            this["answered_count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("wrong_count" in $$source)) {
            this["wrong_count"] = 0;
        }
        if (!("unanswered_count" in $$source)) {
            this["unanswered_count"] = 0;
        }
        if (!("correct_rate" in $$source)) {
            this["correct_rate"] = 0;
        }
        if (!("time_spent_seconds" in $$source)) {
            this["time_spent_seconds"] = 0;
        }
        if (!("type_stats" in $$source)) {
            this["type_stats"] = {};
        }
        if (!("difficulty_stats" in $$source)) {
            this["difficulty_stats"] = {};
        }
        if (!("wrong_question_ids" in $$source)) {
            this["wrong_question_ids"] = [];
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }
        if (!("completed_at" in $$source)) {
            this["completed_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MockExamScoreCard instance from a string or object.
     */
    static createFrom($$source: any = {}): MockExamScoreCard {
        const $$createField9_0 = $$createType22;
        const $$createField10_0 = $$createType24;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("type_stats" in $$parsedSource) {
            $$parsedSource["type_stats"] = $$createField9_0($$parsedSource["type_stats"]);
        }
        if ("difficulty_stats" in $$parsedSource) {
            $$parsedSource["difficulty_stats"] = $$createField10_0($$parsedSource["difficulty_stats"]);
        }
        if ("wrong_question_ids" in $$parsedSource) {
            $$parsedSource["wrong_question_ids"] = $$createField11_0($$parsedSource["wrong_question_ids"]);
        }
        return new MockExamScoreCard($$parsedSource as Partial<MockExamScoreCard>);
    }
}

export class MockExamSession {
    "id": string;
    "exam_id": string;
    "config": MockExamConfig;
    "question_ids": string[];
    "started_at": string;
    "ended_at"?: string | null;
    "answers": { [_ in string]?: string };
    "results": { [_ in string]?: boolean };
    "is_submitted": boolean;
    "score"?: number | null;
    "correct_rate"?: number | null;

    /** Creates a new MockExamSession instance. */
    constructor($$source: Partial<MockExamSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new MockExamConfig());
        }
        if (!("question_ids" in $$source)) {
            this["question_ids"] = [];
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "";
        }
        if (!("answers" in $$source)) {
            this["answers"] = {};
        }
        if (!("results" in $$source)) {
            this["results"] = {};
        }
        if (!("is_submitted" in $$source)) {
            this["is_submitted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MockExamSession instance from a string or object.
     */
    static createFrom($$source: any = {}): MockExamSession {
        const $$createField2_0 = $$createType14;
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType9;
        const $$createField7_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField2_0($$parsedSource["config"]);
        }
        if ("question_ids" in $$parsedSource) {
            $$parsedSource["question_ids"] = $$createField3_0($$parsedSource["question_ids"]);
        }
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField6_0($$parsedSource["answers"]);
        }
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField7_0($$parsedSource["results"]);
        }
        return new MockExamSession($$parsedSource as Partial<MockExamSession>);
    }
}

export class NotesMentionIrecCardHit {
    "id": string;
    "title": string;
    "insight": string;
    "subject"?: string | null;
    "tags": string[];
    "mistake_id"?: string | null;

    /** Creates a new NotesMentionIrecCardHit instance. */
    constructor($$source: Partial<NotesMentionIrecCardHit> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("insight" in $$source)) {
            this["insight"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotesMentionIrecCardHit instance from a string or object.
     */
    static createFrom($$source: any = {}): NotesMentionIrecCardHit {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new NotesMentionIrecCardHit($$parsedSource as Partial<NotesMentionIrecCardHit>);
    }
}

export class NotesMentionMistakeHit {
    "id": string;
    "subject": string;
    "title": string;
    "summary"?: string | null;
    "tags": string[];

    /** Creates a new NotesMentionMistakeHit instance. */
    constructor($$source: Partial<NotesMentionMistakeHit> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotesMentionMistakeHit instance from a string or object.
     */
    static createFrom($$source: any = {}): NotesMentionMistakeHit {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new NotesMentionMistakeHit($$parsedSource as Partial<NotesMentionMistakeHit>);
    }
}

export class NotesMentionSearchResult {
    "mistakes": NotesMentionMistakeHit[];
    "irec_cards": NotesMentionIrecCardHit[];

    /** Creates a new NotesMentionSearchResult instance. */
    constructor($$source: Partial<NotesMentionSearchResult> = {}) {
        if (!("mistakes" in $$source)) {
            this["mistakes"] = [];
        }
        if (!("irec_cards" in $$source)) {
            this["irec_cards"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotesMentionSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): NotesMentionSearchResult {
        const $$createField0_0 = $$createType27;
        const $$createField1_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mistakes" in $$parsedSource) {
            $$parsedSource["mistakes"] = $$createField0_0($$parsedSource["mistakes"]);
        }
        if ("irec_cards" in $$parsedSource) {
            $$parsedSource["irec_cards"] = $$createField1_0($$parsedSource["irec_cards"]);
        }
        return new NotesMentionSearchResult($$parsedSource as Partial<NotesMentionSearchResult>);
    }
}

export class PaperConfig {
    "title": string;
    "type_selection": { [_ in string]?: number };
    "difficulty_filter"?: string[];
    "tags_filter"?: string[];
    "shuffle": boolean;
    "include_answers": boolean;
    "include_explanations": boolean;
    "export_format": string;

    /** Creates a new PaperConfig instance. */
    constructor($$source: Partial<PaperConfig> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("type_selection" in $$source)) {
            this["type_selection"] = {};
        }
        if (!("shuffle" in $$source)) {
            this["shuffle"] = false;
        }
        if (!("include_answers" in $$source)) {
            this["include_answers"] = false;
        }
        if (!("include_explanations" in $$source)) {
            this["include_explanations"] = false;
        }
        if (!("export_format" in $$source)) {
            this["export_format"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaperConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PaperConfig {
        const $$createField1_0 = $$createType20;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("type_selection" in $$parsedSource) {
            $$parsedSource["type_selection"] = $$createField1_0($$parsedSource["type_selection"]);
        }
        if ("difficulty_filter" in $$parsedSource) {
            $$parsedSource["difficulty_filter"] = $$createField2_0($$parsedSource["difficulty_filter"]);
        }
        if ("tags_filter" in $$parsedSource) {
            $$parsedSource["tags_filter"] = $$createField3_0($$parsedSource["tags_filter"]);
        }
        return new PaperConfig($$parsedSource as Partial<PaperConfig>);
    }
}

export class QbankGradingRequest {
    "question_id": string;
    "submission_id": string;
    "stream_session_id": string;
    "mode": string;
    "model_config_id"?: string | null;

    /** Creates a new QbankGradingRequest instance. */
    constructor($$source: Partial<QbankGradingRequest> = {}) {
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("submission_id" in $$source)) {
            this["submission_id"] = "";
        }
        if (!("stream_session_id" in $$source)) {
            this["stream_session_id"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QbankGradingRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): QbankGradingRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QbankGradingRequest($$parsedSource as Partial<QbankGradingRequest>);
    }
}

export class QbankGradingResponse {
    "submission_id": string;
    "verdict"?: string | null;
    "score"?: number | null;
    "feedback": string;

    /** Creates a new QbankGradingResponse instance. */
    constructor($$source: Partial<QbankGradingResponse> = {}) {
        if (!("submission_id" in $$source)) {
            this["submission_id"] = "";
        }
        if (!("feedback" in $$source)) {
            this["feedback"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QbankGradingResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): QbankGradingResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QbankGradingResponse($$parsedSource as Partial<QbankGradingResponse>);
    }
}

export class Question {
    "id": string;
    "exam_id": string;
    "card_id"?: string | null;
    "question_label"?: string | null;
    "content": string;
    "options": QuestionOption[];
    "answer": string;
    "explanation": string;
    "question_type": string;
    "difficulty": string;
    "tags": string[];
    "status": string;
    "user_answer": string;
    "is_correct": boolean | null;
    "attempt_count": number;
    "correct_count": number;
    "last_attempt_at": string | null;
    "user_note": string;
    "is_favorite": boolean;
    "images": QuestionImage[];
    "source_type": string;
    "source_ref"?: string | null;
    "parent_id"?: string | null;
    "created_at": string;
    "updated_at": string;
    "resource_id"?: string;
    "resource_hash"?: string;
    "ai_feedback"?: string | null;
    "ai_score"?: number | null;
    "ai_graded_at"?: string | null;

    /** Creates a new Question instance. */
    constructor($$source: Partial<Question> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("answer" in $$source)) {
            this["answer"] = "";
        }
        if (!("explanation" in $$source)) {
            this["explanation"] = "";
        }
        if (!("question_type" in $$source)) {
            this["question_type"] = "";
        }
        if (!("difficulty" in $$source)) {
            this["difficulty"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("user_answer" in $$source)) {
            this["user_answer"] = "";
        }
        if (!("is_correct" in $$source)) {
            this["is_correct"] = null;
        }
        if (!("attempt_count" in $$source)) {
            this["attempt_count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("last_attempt_at" in $$source)) {
            this["last_attempt_at"] = null;
        }
        if (!("user_note" in $$source)) {
            this["user_note"] = "";
        }
        if (!("is_favorite" in $$source)) {
            this["is_favorite"] = false;
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Question instance from a string or object.
     */
    static createFrom($$source: any = {}): Question {
        const $$createField5_0 = $$createType4;
        const $$createField10_0 = $$createType0;
        const $$createField19_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField19_0($$parsedSource["images"]);
        }
        return new Question($$parsedSource as Partial<Question>);
    }
}

export class QuestionBankStats {
    "exam_id": string;
    "total_count": number;
    "new_count": number;
    "in_progress_count": number;
    "mastered_count": number;
    "review_count": number;
    "total_attempts": number;
    "total_correct": number;
    "correct_rate": number;
    "updated_at": string;

    /** Creates a new QuestionBankStats instance. */
    constructor($$source: Partial<QuestionBankStats> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("total_count" in $$source)) {
            this["total_count"] = 0;
        }
        if (!("new_count" in $$source)) {
            this["new_count"] = 0;
        }
        if (!("in_progress_count" in $$source)) {
            this["in_progress_count"] = 0;
        }
        if (!("mastered_count" in $$source)) {
            this["mastered_count"] = 0;
        }
        if (!("review_count" in $$source)) {
            this["review_count"] = 0;
        }
        if (!("total_attempts" in $$source)) {
            this["total_attempts"] = 0;
        }
        if (!("total_correct" in $$source)) {
            this["total_correct"] = 0;
        }
        if (!("correct_rate" in $$source)) {
            this["correct_rate"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionBankStats instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionBankStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionBankStats($$parsedSource as Partial<QuestionBankStats>);
    }
}

export class QuestionFilters {
    "status"?: string[];
    "difficulty"?: string[];
    "question_type"?: string[];
    "tags"?: string[];
    "search"?: string | null;
    "is_favorite"?: boolean | null;

    /** Creates a new QuestionFilters instance. */
    constructor($$source: Partial<QuestionFilters> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionFilters instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionFilters {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField0_0($$parsedSource["status"]);
        }
        if ("difficulty" in $$parsedSource) {
            $$parsedSource["difficulty"] = $$createField1_0($$parsedSource["difficulty"]);
        }
        if ("question_type" in $$parsedSource) {
            $$parsedSource["question_type"] = $$createField2_0($$parsedSource["question_type"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new QuestionFilters($$parsedSource as Partial<QuestionFilters>);
    }
}

export class QuestionHistory {
    "id": string;
    "question_id": string;
    "field_name": string;
    "old_value"?: string | null;
    "new_value"?: string | null;
    "operator": string;
    "reason"?: string | null;
    "created_at": string;

    /** Creates a new QuestionHistory instance. */
    constructor($$source: Partial<QuestionHistory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("field_name" in $$source)) {
            this["field_name"] = "";
        }
        if (!("operator" in $$source)) {
            this["operator"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionHistory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionHistory($$parsedSource as Partial<QuestionHistory>);
    }
}

export class QuestionImage {
    "id": string;
    "name": string;
    "mime": string;
    "hash": string;

    /** Creates a new QuestionImage instance. */
    constructor($$source: Partial<QuestionImage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mime" in $$source)) {
            this["mime"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionImage instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionImage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionImage($$parsedSource as Partial<QuestionImage>);
    }
}

export class QuestionListResult {
    "questions": Question[];
    "total": number;
    "page": number;
    "page_size": number;
    "has_more": boolean;

    /** Creates a new QuestionListResult instance. */
    constructor($$source: Partial<QuestionListResult> = {}) {
        if (!("questions" in $$source)) {
            this["questions"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            this["page_size"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionListResult {
        const $$createField0_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField0_0($$parsedSource["questions"]);
        }
        return new QuestionListResult($$parsedSource as Partial<QuestionListResult>);
    }
}

export class QuestionOption {
    "key": string;
    "content": string;

    /** Creates a new QuestionOption instance. */
    constructor($$source: Partial<QuestionOption> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuestionOption($$parsedSource as Partial<QuestionOption>);
    }
}

export class QuestionSearchListResult {
    "results": QuestionSearchResult[];
    "total": number;
    "page": number;
    "page_size": number;
    "has_more": boolean;
    "search_time_ms": number;

    /** Creates a new QuestionSearchListResult instance. */
    constructor($$source: Partial<QuestionSearchListResult> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            this["page_size"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }
        if (!("search_time_ms" in $$source)) {
            this["search_time_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionSearchListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionSearchListResult {
        const $$createField0_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new QuestionSearchListResult($$parsedSource as Partial<QuestionSearchListResult>);
    }
}

export class QuestionSearchResult {
    "question": Question;
    "highlight_content"?: string | null;
    "highlight_answer"?: string | null;
    "highlight_explanation"?: string | null;
    "relevance_score": number;

    /** Creates a new QuestionSearchResult instance. */
    constructor($$source: Partial<QuestionSearchResult> = {}) {
        if (!("question" in $$source)) {
            this["question"] = (new Question());
        }
        if (!("relevance_score" in $$source)) {
            this["relevance_score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionSearchResult {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("question" in $$parsedSource) {
            $$parsedSource["question"] = $$createField0_0($$parsedSource["question"]);
        }
        return new QuestionSearchResult($$parsedSource as Partial<QuestionSearchResult>);
    }
}

export class QuestionVersion {
    "id": string;
    "content": string;
    "options"?: QuestionOption[];
    "answer"?: string;
    "explanation"?: string;
    "question_type": string;
    "difficulty"?: string;
    "tags": string[];
    "status": string;
    "user_answer"?: string;
    "is_correct"?: boolean | null;
    "attempt_count": number;
    "correct_count": number;
    "user_note"?: string;
    "is_favorite": boolean;
    "content_hash": string;
    "updated_at": string;
    "remote_version": number;

    /** Creates a new QuestionVersion instance. */
    constructor($$source: Partial<QuestionVersion> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("question_type" in $$source)) {
            this["question_type"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("attempt_count" in $$source)) {
            this["attempt_count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("is_favorite" in $$source)) {
            this["is_favorite"] = false;
        }
        if (!("content_hash" in $$source)) {
            this["content_hash"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("remote_version" in $$source)) {
            this["remote_version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): QuestionVersion {
        const $$createField2_0 = $$createType4;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new QuestionVersion($$parsedSource as Partial<QuestionVersion>);
    }
}

export class SearchQuestionsRequest {
    "keyword": string;
    "exam_id"?: string | null;
    "filters"?: QuestionFilters | null;
    "page"?: number;
    "page_size"?: number;

    /** Creates a new SearchQuestionsRequest instance. */
    constructor($$source: Partial<SearchQuestionsRequest> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchQuestionsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchQuestionsRequest {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField2_0($$parsedSource["filters"]);
        }
        return new SearchQuestionsRequest($$parsedSource as Partial<SearchQuestionsRequest>);
    }
}

export class StartTimedPracticeRequest {
    "exam_id": string;
    "duration_minutes": number;
    "question_count": number;

    /** Creates a new StartTimedPracticeRequest instance. */
    constructor($$source: Partial<StartTimedPracticeRequest> = {}) {
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("duration_minutes" in $$source)) {
            this["duration_minutes"] = 0;
        }
        if (!("question_count" in $$source)) {
            this["question_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartTimedPracticeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartTimedPracticeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartTimedPracticeRequest($$parsedSource as Partial<StartTimedPracticeRequest>);
    }
}

export class SubmitAnswerRequest {
    "question_id": string;
    "user_answer": string;
    "is_correct_override"?: boolean | null;
    "client_request_id"?: string | null;

    /** Creates a new SubmitAnswerRequest instance. */
    constructor($$source: Partial<SubmitAnswerRequest> = {}) {
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("user_answer" in $$source)) {
            this["user_answer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitAnswerRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SubmitAnswerRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubmitAnswerRequest($$parsedSource as Partial<SubmitAnswerRequest>);
    }
}

export class SubmitAnswerResult {
    "is_correct": boolean | null;
    "correct_answer"?: string | null;
    "needs_manual_grading": boolean;
    "message": string;
    "updated_question": Question;
    "updated_stats": QuestionBankStats;
    "submission_id": string;

    /** Creates a new SubmitAnswerResult instance. */
    constructor($$source: Partial<SubmitAnswerResult> = {}) {
        if (!("is_correct" in $$source)) {
            this["is_correct"] = null;
        }
        if (!("needs_manual_grading" in $$source)) {
            this["needs_manual_grading"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("updated_question" in $$source)) {
            this["updated_question"] = (new Question());
        }
        if (!("updated_stats" in $$source)) {
            this["updated_stats"] = (new QuestionBankStats());
        }
        if (!("submission_id" in $$source)) {
            this["submission_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitAnswerResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SubmitAnswerResult {
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updated_question" in $$parsedSource) {
            $$parsedSource["updated_question"] = $$createField4_0($$parsedSource["updated_question"]);
        }
        if ("updated_stats" in $$parsedSource) {
            $$parsedSource["updated_stats"] = $$createField5_0($$parsedSource["updated_stats"]);
        }
        return new SubmitAnswerResult($$parsedSource as Partial<SubmitAnswerResult>);
    }
}

export class SubmitMockExamRequest {
    "session": MockExamSession;

    /** Creates a new SubmitMockExamRequest instance. */
    constructor($$source: Partial<SubmitMockExamRequest> = {}) {
        if (!("session" in $$source)) {
            this["session"] = (new MockExamSession());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmitMockExamRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SubmitMockExamRequest {
        const $$createField0_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField0_0($$parsedSource["session"]);
        }
        return new SubmitMockExamRequest($$parsedSource as Partial<SubmitMockExamRequest>);
    }
}

export class SyncConfig {
    "default_strategy": string;
    "auto_sync": boolean;
    "sync_interval_secs": number;
    "sync_progress": boolean;
    "sync_notes": boolean;

    /** Creates a new SyncConfig instance. */
    constructor($$source: Partial<SyncConfig> = {}) {
        if (!("default_strategy" in $$source)) {
            this["default_strategy"] = "";
        }
        if (!("auto_sync" in $$source)) {
            this["auto_sync"] = false;
        }
        if (!("sync_interval_secs" in $$source)) {
            this["sync_interval_secs"] = 0;
        }
        if (!("sync_progress" in $$source)) {
            this["sync_progress"] = false;
        }
        if (!("sync_notes" in $$source)) {
            this["sync_notes"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncConfig($$parsedSource as Partial<SyncConfig>);
    }
}

export class SyncConflict {
    "id": string;
    "question_id": string;
    "exam_id": string;
    "conflict_type": string;
    "local_version": QuestionVersion;
    "remote_version": QuestionVersion;
    "status": string;
    "resolved_strategy"?: string | null;
    "resolved_at"?: string | null;
    "created_at": string;

    /** Creates a new SyncConflict instance. */
    constructor($$source: Partial<SyncConflict> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("conflict_type" in $$source)) {
            this["conflict_type"] = "";
        }
        if (!("local_version" in $$source)) {
            this["local_version"] = (new QuestionVersion());
        }
        if (!("remote_version" in $$source)) {
            this["remote_version"] = (new QuestionVersion());
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncConflict {
        const $$createField4_0 = $$createType34;
        const $$createField5_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local_version" in $$parsedSource) {
            $$parsedSource["local_version"] = $$createField4_0($$parsedSource["local_version"]);
        }
        if ("remote_version" in $$parsedSource) {
            $$parsedSource["remote_version"] = $$createField5_0($$parsedSource["remote_version"]);
        }
        return new SyncConflict($$parsedSource as Partial<SyncConflict>);
    }
}

export class SyncStatusResult {
    "sync_enabled": boolean;
    "last_synced_at"?: string | null;
    "local_modified_count": number;
    "pending_conflict_count": number;
    "total_count": number;
    "synced_count": number;
    "sync_config"?: SyncConfig | null;

    /** Creates a new SyncStatusResult instance. */
    constructor($$source: Partial<SyncStatusResult> = {}) {
        if (!("sync_enabled" in $$source)) {
            this["sync_enabled"] = false;
        }
        if (!("local_modified_count" in $$source)) {
            this["local_modified_count"] = 0;
        }
        if (!("pending_conflict_count" in $$source)) {
            this["pending_conflict_count"] = 0;
        }
        if (!("total_count" in $$source)) {
            this["total_count"] = 0;
        }
        if (!("synced_count" in $$source)) {
            this["synced_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncStatusResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncStatusResult {
        const $$createField6_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sync_config" in $$parsedSource) {
            $$parsedSource["sync_config"] = $$createField6_0($$parsedSource["sync_config"]);
        }
        return new SyncStatusResult($$parsedSource as Partial<SyncStatusResult>);
    }
}

export class TimedPracticeSession {
    "id": string;
    "exam_id": string;
    "duration_minutes": number;
    "question_count": number;
    "question_ids": string[];
    "started_at": string;
    "ended_at"?: string | null;
    "answered_count": number;
    "correct_count": number;
    "is_timeout": boolean;
    "is_submitted": boolean;
    "paused_seconds": number;
    "is_paused": boolean;

    /** Creates a new TimedPracticeSession instance. */
    constructor($$source: Partial<TimedPracticeSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("exam_id" in $$source)) {
            this["exam_id"] = "";
        }
        if (!("duration_minutes" in $$source)) {
            this["duration_minutes"] = 0;
        }
        if (!("question_count" in $$source)) {
            this["question_count"] = 0;
        }
        if (!("question_ids" in $$source)) {
            this["question_ids"] = [];
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "";
        }
        if (!("answered_count" in $$source)) {
            this["answered_count"] = 0;
        }
        if (!("correct_count" in $$source)) {
            this["correct_count"] = 0;
        }
        if (!("is_timeout" in $$source)) {
            this["is_timeout"] = false;
        }
        if (!("is_submitted" in $$source)) {
            this["is_submitted"] = false;
        }
        if (!("paused_seconds" in $$source)) {
            this["paused_seconds"] = 0;
        }
        if (!("is_paused" in $$source)) {
            this["is_paused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimedPracticeSession instance from a string or object.
     */
    static createFrom($$source: any = {}): TimedPracticeSession {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("question_ids" in $$parsedSource) {
            $$parsedSource["question_ids"] = $$createField4_0($$parsedSource["question_ids"]);
        }
        return new TimedPracticeSession($$parsedSource as Partial<TimedPracticeSession>);
    }
}

export class TypeStatItem {
    "total": number;
    "correct": number;
    "rate": number;

    /** Creates a new TypeStatItem instance. */
    constructor($$source: Partial<TypeStatItem> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("correct" in $$source)) {
            this["correct"] = 0;
        }
        if (!("rate" in $$source)) {
            this["rate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeStatItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TypeStatItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TypeStatItem($$parsedSource as Partial<TypeStatItem>);
    }
}

export class UpdateQuestionParams {
    "content"?: string | null;
    "question_type"?: string | null;
    "options"?: QuestionOption[];
    "answer"?: string | null;
    "explanation"?: string | null;
    "difficulty"?: string | null;
    "tags"?: string[];
    "status"?: string | null;
    "user_answer"?: string | null;
    "is_correct"?: boolean | null;
    "user_note"?: string | null;
    "images"?: QuestionImage[];

    /** Creates a new UpdateQuestionParams instance. */
    constructor($$source: Partial<UpdateQuestionParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateQuestionParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateQuestionParams {
        const $$createField2_0 = $$createType4;
        const $$createField6_0 = $$createType0;
        const $$createField11_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField11_0($$parsedSource["images"]);
        }
        return new UpdateQuestionParams($$parsedSource as Partial<UpdateQuestionParams>);
    }
}

export class UpdateQuestionRequest {
    "question_id": string;
    "params": UpdateQuestionParams;
    "record_history"?: boolean;

    /** Creates a new UpdateQuestionRequest instance. */
    constructor($$source: Partial<UpdateQuestionRequest> = {}) {
        if (!("question_id" in $$source)) {
            this["question_id"] = "";
        }
        if (!("params" in $$source)) {
            this["params"] = (new UpdateQuestionParams());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateQuestionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateQuestionRequest {
        const $$createField1_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField1_0($$parsedSource["params"]);
        }
        return new UpdateQuestionRequest($$parsedSource as Partial<UpdateQuestionRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DailyCheckIn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = QuestionOption.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = QuestionImage.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = QuestionFilters.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = CsvImportError.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = DailySourceDistribution.createFrom;
const $$createType14 = MockExamConfig.createFrom;
const $$createType15 = PaperConfig.createFrom;
const $$createType16 = Question.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = KnowledgePoint.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $Create.Map($Create.Any, $Create.Any);
const $$createType21 = TypeStatItem.createFrom;
const $$createType22 = $Create.Map($Create.Any, $$createType21);
const $$createType23 = DifficultyStatItem.createFrom;
const $$createType24 = $Create.Map($Create.Any, $$createType23);
const $$createType25 = $Create.Map($Create.Any, $Create.Any);
const $$createType26 = NotesMentionMistakeHit.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = NotesMentionIrecCardHit.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = QuestionSearchResult.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = QuestionBankStats.createFrom;
const $$createType33 = MockExamSession.createFrom;
const $$createType34 = QuestionVersion.createFrom;
const $$createType35 = SyncConfig.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = UpdateQuestionParams.createFrom;
