// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as anki$0 from "../anki/models.js";

export function CheckConnectStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1163148525);
}

export function DeleteDocumentSession(documentID: string): $CancellablePromise<boolean> {
    return $Call.ByID(576237777, documentID);
}

export function GetDocumentCards(documentID: string): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByID(411097873, documentID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetDocumentProcessingState(documentID: string): $CancellablePromise<anki$0.DocumentProcessingState> {
    return $Call.ByID(1461456042, documentID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetDocumentState(documentID: string): $CancellablePromise<anki$0.DocumentProcessingState> {
    return $Call.ByID(3505756455, documentID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetDocumentTaskCounts(documentID: string): $CancellablePromise<anki$0.DocumentTaskCounts> {
    return $Call.ByID(4006438143, documentID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetDocumentTasks(documentID: string): $CancellablePromise<anki$0.DocumentTask[]> {
    return $Call.ByID(1347349684, documentID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListDeckNames(): $CancellablePromise<string[]> {
    return $Call.ByID(1568999460).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListModelNames(): $CancellablePromise<string[]> {
    return $Call.ByID(3112910690).then(($result: any) => {
        return $$createType6($result);
    });
}

export function PauseDocumentProcessing(documentID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2796060079, documentID);
}

export function RecoverStuckDocumentTasks(): $CancellablePromise<number> {
    return $Call.ByID(635264714);
}

export function ResumeDocumentProcessing(documentID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2347803332, documentID);
}

export function SaveAnkiCards(request: anki$0.SaveAnkiCardsRequest): $CancellablePromise<anki$0.SaveAnkiCardsResponse> {
    return $Call.ByID(1922710910, request).then(($result: any) => {
        return $$createType7($result);
    });
}

export function StartEnhancedDocumentProcessing(documentContent: string, originalDocumentName: string, options: { [_ in string]?: any }): $CancellablePromise<string> {
    return $Call.ByID(540479799, documentContent, originalDocumentName, options);
}

export function TriggerTaskProcessing(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2246312057, taskID);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = anki$0.DocumentProcessingState.createFrom;
const $$createType3 = anki$0.DocumentTaskCounts.createFrom;
const $$createType4 = anki$0.DocumentTask.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = anki$0.SaveAnkiCardsResponse.createFrom;
