// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chat$0 from "../chat/models.js";

export function AddTag(sessionID: string, tag: string): $CancellablePromise<boolean> {
    return $Call.ByID(3022649753, sessionID, tag);
}

export function ArchiveSession(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2718250154, sessionID);
}

export function BranchSession(sourceSessionID: string, upToMessageID: string): $CancellablePromise<chat$0.Session> {
    return $Call.ByID(3687836596, sourceSessionID, upToMessageID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CancelStream(sessionID: string, messageID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3729593322, sessionID, messageID);
}

export function ClearApprovalHistory(): $CancellablePromise<number> {
    return $Call.ByID(3969903086);
}

export function ContinueMessage(sessionID: string, messageID: string, options: { [_ in string]?: any }): $CancellablePromise<string> {
    return $Call.ByID(1134423840, sessionID, messageID, options);
}

export function CountSessions(status: string | null, groupID: string | null): $CancellablePromise<number> {
    return $Call.ByID(2162662294, status, groupID);
}

export function CreateGroup(request: chat$0.CreateGroupRequest): $CancellablePromise<chat$0.Group> {
    return $Call.ByID(2694604911, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateSession(mode: string, title: string | null, metadata: { [_ in string]?: any }, groupID: string | null): $CancellablePromise<chat$0.Session> {
    return $Call.ByID(270197720, mode, title, metadata, groupID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteGroup(groupID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2561244666, groupID);
}

export function DeleteMessage(sessionID: string, messageID: string): $CancellablePromise<boolean> {
    return $Call.ByID(581746314, sessionID, messageID);
}

export function DeleteSession(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3138096717, sessionID);
}

export function EditAndResend(request: chat$0.EditAndResendRequest): $CancellablePromise<chat$0.EditAndResendResponse> {
    return $Call.ByID(1637315926, request).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetGroup(groupID: string): $CancellablePromise<chat$0.Group | null> {
    return $Call.ByID(429679735, groupID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetMessageSummary(): $CancellablePromise<chat$0.MessageSummary> {
    return $Call.ByID(2899951325).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSession(sessionID: string): $CancellablePromise<chat$0.Session | null> {
    return $Call.ByID(3624447296, sessionID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSessionTags(sessionID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3426533705, sessionID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetTagsBatch(sessionIDs: string[]): $CancellablePromise<{ [_ in string]?: string[] }> {
    return $Call.ByID(1613465827, sessionIDs).then(($result: any) => {
        return $$createType7($result);
    });
}

export function LLMUsageByCaller(startDate: string, endDate: string): $CancellablePromise<chat$0.CallerTypeSummary[]> {
    return $Call.ByID(2842130388, startDate, endDate).then(($result: any) => {
        return $$createType9($result);
    });
}

export function LLMUsageByModel(startDate: string, endDate: string): $CancellablePromise<chat$0.ModelSummary[]> {
    return $Call.ByID(2073127500, startDate, endDate).then(($result: any) => {
        return $$createType11($result);
    });
}

export function LLMUsageCleanup(beforeDate: string): $CancellablePromise<number> {
    return $Call.ByID(2833172502, beforeDate);
}

export function LLMUsageDaily(startDate: string, endDate: string): $CancellablePromise<chat$0.DailySummary[]> {
    return $Call.ByID(2639843699, startDate, endDate).then(($result: any) => {
        return $$createType13($result);
    });
}

export function LLMUsageGetTrends(days: number, granularity: string): $CancellablePromise<chat$0.UsageTrendPoint[]> {
    return $Call.ByID(1411197906, days, granularity).then(($result: any) => {
        return $$createType15($result);
    });
}

export function LLMUsageRecent(limit: number): $CancellablePromise<chat$0.UsageRecord[]> {
    return $Call.ByID(2549069085, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

export function LLMUsageSummary(startDate: string | null, endDate: string | null): $CancellablePromise<chat$0.UsageSummary> {
    return $Call.ByID(3421125442, startDate, endDate).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListAllTags(): $CancellablePromise<any[][]> {
    return $Call.ByID(3438588710).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ListGroups(status: string | null, workspaceID: string | null): $CancellablePromise<chat$0.Group[]> {
    return $Call.ByID(230033584, status, workspaceID).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ListSessions(status: string | null, groupID: string | null, limit: number, offset: number): $CancellablePromise<chat$0.Session[]> {
    return $Call.ByID(3142689101, status, groupID, limit, offset).then(($result: any) => {
        return $$createType22($result);
    });
}

export function LoadSession(sessionID: string): $CancellablePromise<chat$0.LoadSessionResponse> {
    return $Call.ByID(1657467024, sessionID).then(($result: any) => {
        return $$createType23($result);
    });
}

export function MoveSessionToGroup(sessionID: string, groupID: string | null): $CancellablePromise<boolean> {
    return $Call.ByID(3697664309, sessionID, groupID);
}

export function RemoveTag(sessionID: string, tag: string): $CancellablePromise<boolean> {
    return $Call.ByID(3804930496, sessionID, tag);
}

export function ReorderGroups(groupIDs: string[]): $CancellablePromise<boolean> {
    return $Call.ByID(752941083, groupIDs);
}

export function RespondAskUser(toolCallID: string, selectedTexts: string[], selectedIndices: number[], customText: string | null, source: string): $CancellablePromise<boolean> {
    return $Call.ByID(1263024429, toolCallID, selectedTexts, selectedIndices, customText, source);
}

export function RespondToolApproval(sessionID: string, toolCallID: string, toolName: string, approved: boolean, reason: string | null, remember: boolean, $arguments: { [_ in string]?: any }): $CancellablePromise<boolean> {
    return $Call.ByID(695650412, sessionID, toolCallID, toolName, approved, reason, remember, $arguments);
}

export function RestoreGroup(groupID: string): $CancellablePromise<chat$0.Group> {
    return $Call.ByID(363545101, groupID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RestoreSession(sessionID: string): $CancellablePromise<chat$0.Session> {
    return $Call.ByID(280590878, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RetryMessage(sessionID: string, messageID: string, options: { [_ in string]?: any }): $CancellablePromise<chat$0.RetryMessageResponse> {
    return $Call.ByID(3910905121, sessionID, messageID, options).then(($result: any) => {
        return $$createType24($result);
    });
}

export function SaveSession(sessionID: string, sessionState: chat$0.SessionState): $CancellablePromise<boolean> {
    return $Call.ByID(829387847, sessionID, sessionState);
}

export function SendMessage(request: chat$0.SendMessageRequest): $CancellablePromise<string> {
    return $Call.ByID(1848155861, request);
}

export function UpdateBlockContent(blockID: string, content: string): $CancellablePromise<boolean> {
    return $Call.ByID(1482041199, blockID, content);
}

export function UpdateGroup(groupID: string, request: chat$0.UpdateGroupRequest): $CancellablePromise<chat$0.Group> {
    return $Call.ByID(1650110672, groupID, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateSessionSettings(sessionID: string, settings: chat$0.SessionSettings): $CancellablePromise<chat$0.Session> {
    return $Call.ByID(3540019046, sessionID, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpsertStreamingBlock(blockID: string, messageID: string, blockType: string, content: string, sessionID: string | null): $CancellablePromise<boolean> {
    return $Call.ByID(2735636250, blockID, messageID, blockType, content, sessionID);
}

// Private type creation functions
const $$createType0 = chat$0.Session.createFrom;
const $$createType1 = chat$0.Group.createFrom;
const $$createType2 = chat$0.EditAndResendResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType1);
const $$createType4 = chat$0.MessageSummary.createFrom;
const $$createType5 = $Create.Nullable($$createType0);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = chat$0.CallerTypeSummary.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = chat$0.ModelSummary.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = chat$0.DailySummary.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = chat$0.UsageTrendPoint.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = chat$0.UsageRecord.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = chat$0.UsageSummary.createFrom;
const $$createType19 = $Create.Array($Create.Any);
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Array($$createType1);
const $$createType22 = $Create.Array($$createType0);
const $$createType23 = chat$0.LoadSessionResponse.createFrom;
const $$createType24 = chat$0.RetryMessageResponse.createFrom;
