// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dstu$0 from "../dstu/models.js";

export function AddFolderItem(folderID: string | null, itemType: string, itemID: string): $CancellablePromise<dstu$0.VfsFolderItem> {
    return $Call.ByID(2719119928, folderID, itemType, itemID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AddTextbooks(request: dstu$0.AddTextbooksRequest): $CancellablePromise<dstu$0.TextbookRecord[]> {
    return $Call.ByID(2943217174, request).then(($result: any) => {
        return $$createType2($result);
    });
}

export function BatchMove(request: dstu$0.BatchMoveRequest): $CancellablePromise<dstu$0.BatchMoveResult> {
    return $Call.ByID(69743341, request).then(($result: any) => {
        return $$createType3($result);
    });
}

export function BuildPath(folderID: string | null, resourceID: string): $CancellablePromise<string> {
    return $Call.ByID(1329167663, folderID, resourceID);
}

export function CanvasAppendContent(noteID: string, content: string, section: string | null): $CancellablePromise<void> {
    return $Call.ByID(3933582673, noteID, content, section);
}

export function CanvasReadContent(noteID: string, section: string | null): $CancellablePromise<string> {
    return $Call.ByID(2056491069, noteID, section);
}

export function CanvasReplaceContent(noteID: string, search: string, replace: string, isRegex: boolean): $CancellablePromise<number> {
    return $Call.ByID(681519913, noteID, search, replace, isRegex);
}

export function CanvasSetContent(noteID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2950699865, noteID, content);
}

export function Create(path: string, options: dstu$0.CreateOptions): $CancellablePromise<dstu$0.Node> {
    return $Call.ByID(2192066604, path, options).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CreateFolder(title: string, parentID: string | null, icon: string | null, color: string | null): $CancellablePromise<dstu$0.VfsFolder> {
    return $Call.ByID(450281752, title, parentID, icon, color).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Delete(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3954157203, path);
}

export function DeleteFolder(folderID: string): $CancellablePromise<void> {
    return $Call.ByID(2083158135, folderID);
}

export function DeleteMany(paths: string[]): $CancellablePromise<number> {
    return $Call.ByID(4082553356, paths);
}

export function EmptyTrash(): $CancellablePromise<number> {
    return $Call.ByID(378038761);
}

export function Get(path: string): $CancellablePromise<dstu$0.Node | null> {
    return $Call.ByID(1586480500, path).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetContent(path: string): $CancellablePromise<string> {
    return $Call.ByID(714563521, path);
}

export function GetFolder(folderID: string): $CancellablePromise<dstu$0.VfsFolder | null> {
    return $Call.ByID(1130307904, folderID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetFolderAllResources(folderID: string, includeSubfolders: boolean, includeContent: boolean): $CancellablePromise<dstu$0.FolderResourcesResult> {
    return $Call.ByID(1391528740, folderID, includeSubfolders, includeContent).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetFolderBreadcrumbs(folderID: string): $CancellablePromise<dstu$0.BreadcrumbItem[]> {
    return $Call.ByID(548317430, folderID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetFolderItems(folderID: string | null): $CancellablePromise<dstu$0.VfsFolderItem[]> {
    return $Call.ByID(2529489908, folderID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetFolderTree(): $CancellablePromise<dstu$0.FolderTreeNode[]> {
    return $Call.ByID(3837692424).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetPathByID(resourceID: string): $CancellablePromise<string> {
    return $Call.ByID(2528596451, resourceID);
}

export function GetResourceByPath(path: string): $CancellablePromise<dstu$0.Node | null> {
    return $Call.ByID(1526374934, path).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetResourceLocation(resourceID: string): $CancellablePromise<dstu$0.ResourceLocation> {
    return $Call.ByID(3757095839, resourceID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ImportMarkdown(request: dstu$0.ImportMarkdownRequest): $CancellablePromise<dstu$0.Node> {
    return $Call.ByID(1088622044, request).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ImportMarkdownBatch(request: dstu$0.ImportMarkdownBatchRequest): $CancellablePromise<dstu$0.ImportMarkdownBatchResponse> {
    return $Call.ByID(3552184804, request).then(($result: any) => {
        return $$createType15($result);
    });
}

export function List(path: string, options: dstu$0.ListOptions | null): $CancellablePromise<dstu$0.Node[]> {
    return $Call.ByID(1993774928, path, options).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListDeleted(resourceType: string, limit: number | null, offset: number | null): $CancellablePromise<dstu$0.Node[]> {
    return $Call.ByID(4192942877, resourceType, limit, offset).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListFolders(): $CancellablePromise<dstu$0.VfsFolder[]> {
    return $Call.ByID(468091877).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ListTags(): $CancellablePromise<string[]> {
    return $Call.ByID(3536464345).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListTrash(limit: number | null, offset: number | null): $CancellablePromise<dstu$0.Node[]> {
    return $Call.ByID(3328946778, limit, offset).then(($result: any) => {
        return $$createType16($result);
    });
}

export function MoveFolder(folderID: string, newParentID: string | null): $CancellablePromise<void> {
    return $Call.ByID(3918707661, folderID, newParentID);
}

export function MoveFolderItem(itemType: string, itemID: string, newFolderID: string | null): $CancellablePromise<void> {
    return $Call.ByID(3504985646, itemType, itemID, newFolderID);
}

export function MoveToFolder(resourceID: string, targetFolderID: string | null): $CancellablePromise<dstu$0.ResourceLocation> {
    return $Call.ByID(3762930144, resourceID, targetFolderID).then(($result: any) => {
        return $$createType14($result);
    });
}

export function NotesSearch(keyword: string, limit: number): $CancellablePromise<dstu$0.NotesSearchHit[]> {
    return $Call.ByID(3730146649, keyword, limit).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ParsePath(path: string): $CancellablePromise<dstu$0.ParsedPath> {
    return $Call.ByID(2634764208, path).then(($result: any) => {
        return $$createType21($result);
    });
}

export function PermanentlyDelete(id: string, itemType: string): $CancellablePromise<void> {
    return $Call.ByID(235988826, id, itemType);
}

export function Purge(path: string): $CancellablePromise<void> {
    return $Call.ByID(4013980903, path);
}

export function PurgeAll(resourceType: string): $CancellablePromise<number> {
    return $Call.ByID(3288307522, resourceType);
}

export function RefreshPathCache(resourceID: string | null): $CancellablePromise<number> {
    return $Call.ByID(1222815726, resourceID);
}

export function RemoveFolderItem(itemType: string, itemID: string): $CancellablePromise<void> {
    return $Call.ByID(2643060363, itemType, itemID);
}

export function RenameFolder(folderID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(755073874, folderID, title);
}

export function ReorderFolderItems(folderID: string | null, itemIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2993251689, folderID, itemIDs);
}

export function ReorderFolders(folderIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(3899745724, folderIDs);
}

export function Restore(path: string): $CancellablePromise<dstu$0.Node> {
    return $Call.ByID(1884738826, path).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RestoreMany(paths: string[]): $CancellablePromise<number> {
    return $Call.ByID(2381159245, paths);
}

export function Search(query: string, options: dstu$0.ListOptions | null): $CancellablePromise<dstu$0.Node[]> {
    return $Call.ByID(3164133364, query, options).then(($result: any) => {
        return $$createType16($result);
    });
}

export function SetFavorite(path: string, favorite: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(578496596, path, favorite);
}

export function SetFolderExpanded(folderID: string, isExpanded: boolean): $CancellablePromise<void> {
    return $Call.ByID(1318667773, folderID, isExpanded);
}

export function SetMetadata(path: string, metadata: { [_ in string]?: any }): $CancellablePromise<boolean> {
    return $Call.ByID(3270424605, path, metadata);
}

export function SoftDelete(id: string, itemType: string): $CancellablePromise<void> {
    return $Call.ByID(1716126827, id, itemType);
}

export function TrashRestore(id: string, itemType: string): $CancellablePromise<void> {
    return $Call.ByID(2343221752, id, itemType);
}

export function Update(path: string, content: string, resourceType: string): $CancellablePromise<dstu$0.Node> {
    return $Call.ByID(3443696841, path, content, resourceType).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = dstu$0.VfsFolderItem.createFrom;
const $$createType1 = dstu$0.TextbookRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = dstu$0.BatchMoveResult.createFrom;
const $$createType4 = dstu$0.Node.createFrom;
const $$createType5 = dstu$0.VfsFolder.createFrom;
const $$createType6 = $Create.Nullable($$createType4);
const $$createType7 = $Create.Nullable($$createType5);
const $$createType8 = dstu$0.FolderResourcesResult.createFrom;
const $$createType9 = dstu$0.BreadcrumbItem.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($$createType0);
const $$createType12 = dstu$0.FolderTreeNode.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = dstu$0.ResourceLocation.createFrom;
const $$createType15 = dstu$0.ImportMarkdownBatchResponse.createFrom;
const $$createType16 = $Create.Array($$createType4);
const $$createType17 = $Create.Array($$createType5);
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = dstu$0.NotesSearchHit.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = dstu$0.ParsedPath.createFrom;
