// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CopyFile(sourcePath: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(406500475, sourcePath, destPath);
}

export function GetFileSize(path: string): $CancellablePromise<number> {
    return $Call.ByID(3610478355, path);
}

export function ReadFileBytes(path: string): $CancellablePromise<string> {
    return $Call.ByID(1112677633, path).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

export function ReadFileText(path: string): $CancellablePromise<string> {
    return $Call.ByID(52057737, path);
}

export function SaveTextToFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2479736405, path, content);
}
