// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CloseStdioSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(878202307, sessionID);
}

export function SendStdioMessage(sessionID: string, payload: string): $CancellablePromise<void> {
    return $Call.ByID(240483886, sessionID, payload);
}

export function StartStdioSession(command: string, args: string[], env: { [_ in string]?: string }, framing: string | null, cwd: string | null): $CancellablePromise<string> {
    return $Call.ByID(1094380363, command, args, env, framing, cwd);
}
