// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notes$0 from "../notes/models.js";

export function AssetsIndexScan(noteID: string): $CancellablePromise<number> {
    return $Call.ByID(1219111141, noteID);
}

export function BulkDeleteAssets(paths: string[]): $CancellablePromise<number> {
    return $Call.ByID(3356585711, paths);
}

export function DBStats(): $CancellablePromise<notes$0.DBStats> {
    return $Call.ByID(215942206).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DBVacuum(): $CancellablePromise<boolean> {
    return $Call.ByID(1893024944);
}

export function DeleteAsset(relativePath: string): $CancellablePromise<boolean> {
    return $Call.ByID(4225359166, relativePath);
}

export function Export(request: notes$0.ExportRequest): $CancellablePromise<notes$0.ExportResult> {
    return $Call.ByID(1656614067, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExportSingle(request: notes$0.ExportSingleRequest): $CancellablePromise<notes$0.ExportResult> {
    return $Call.ByID(3220277451, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetImageAsBase64(relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(3575878251, relativePath);
}

export function GetPref(key: string): $CancellablePromise<string | null> {
    return $Call.ByID(3302373186, key);
}

export function Import(request: notes$0.ImportRequest): $CancellablePromise<notes$0.ImportResult> {
    return $Call.ByID(2027974868, request).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListAssets(subject: string, noteID: string): $CancellablePromise<notes$0.AssetRef[]> {
    return $Call.ByID(580887044, subject, noteID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ResolveAssetPath(relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(3079028550, relativePath);
}

export function SaveAsset(subject: string, noteID: string, base64Data: string, defaultExt: string | null): $CancellablePromise<notes$0.AssetRef> {
    return $Call.ByID(1981425384, subject, noteID, base64Data, defaultExt).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ScanOrphanAssets(): $CancellablePromise<string[]> {
    return $Call.ByID(2357317699).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetPref(key: string, value: string): $CancellablePromise<boolean> {
    return $Call.ByID(1371529086, key, value);
}

// Private type creation functions
const $$createType0 = notes$0.DBStats.createFrom;
const $$createType1 = notes$0.ExportResult.createFrom;
const $$createType2 = notes$0.ImportResult.createFrom;
const $$createType3 = notes$0.AssetRef.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
