// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as qbank$0 from "../qbank/models.js";

export function AIGrade(request: qbank$0.QbankGradingRequest): $CancellablePromise<qbank$0.QbankGradingResponse | null> {
    return $Call.ByID(4068910066, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function BatchDeleteQuestions(questionIDs: string[]): $CancellablePromise<qbank$0.BatchResult> {
    return $Call.ByID(1572211085, questionIDs).then(($result: any) => {
        return $$createType2($result);
    });
}

export function BatchResolveConflicts(examID: string, strategy: string): $CancellablePromise<qbank$0.Question[]> {
    return $Call.ByID(2083978364, examID, strategy).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CancelGrading(streamEventName: string): $CancellablePromise<boolean> {
    return $Call.ByID(4056940617, streamEventName);
}

export function CheckSyncStatus(examID: string): $CancellablePromise<qbank$0.SyncStatusResult> {
    return $Call.ByID(1243209066, examID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function CreateQuestion(params: qbank$0.CreateQuestionParams): $CancellablePromise<qbank$0.Question> {
    return $Call.ByID(4096963957, params).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DeleteQuestion(questionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2043411530, questionID);
}

export function ExportQuestionsCsv(request: qbank$0.CsvExportRequest): $CancellablePromise<qbank$0.CsvExportResult> {
    return $Call.ByID(4209548812, request).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GenerateMockExam(request: qbank$0.GenerateMockExamRequest): $CancellablePromise<qbank$0.MockExamSession> {
    return $Call.ByID(3379595607, request).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GeneratePaper(request: qbank$0.GeneratePaperRequest): $CancellablePromise<qbank$0.GeneratedPaper> {
    return $Call.ByID(412582492, request).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetActivityHeatmap(request: qbank$0.GetActivityHeatmapRequest): $CancellablePromise<qbank$0.ActivityHeatmapPoint[]> {
    return $Call.ByID(566070814, request).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetCheckInCalendar(request: qbank$0.GetCheckInCalendarRequest): $CancellablePromise<qbank$0.CheckInCalendar> {
    return $Call.ByID(1477222132, request).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetCsvExportableFields(): $CancellablePromise<string[][]> {
    return $Call.ByID(3738011666).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetCsvPreview(filePath: string, rows: number): $CancellablePromise<qbank$0.CsvPreviewResult> {
    return $Call.ByID(1466522531, filePath, rows).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetDailyPractice(request: qbank$0.GetDailyPracticeRequest): $CancellablePromise<qbank$0.DailyPracticeResult> {
    return $Call.ByID(2821671165, request).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetHistory(questionID: string, limit: number): $CancellablePromise<qbank$0.QuestionHistory[]> {
    return $Call.ByID(4039437505, questionID, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetKnowledgeStats(request: qbank$0.GetKnowledgeStatsRequest): $CancellablePromise<qbank$0.KnowledgePoint[]> {
    return $Call.ByID(2898160196, request).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetKnowledgeStatsWithComparison(request: qbank$0.GetKnowledgeStatsRequest): $CancellablePromise<qbank$0.KnowledgeStatsComparison> {
    return $Call.ByID(1489579565, request).then(($result: any) => {
        return $$createType20($result);
    });
}

export function GetLearningTrend(request: qbank$0.GetLearningTrendRequest): $CancellablePromise<qbank$0.LearningTrendPoint[]> {
    return $Call.ByID(1000245448, request).then(($result: any) => {
        return $$createType22($result);
    });
}

export function GetQuestion(questionID: string): $CancellablePromise<qbank$0.Question | null> {
    return $Call.ByID(4239340315, questionID).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetStats(examID: string): $CancellablePromise<qbank$0.QuestionBankStats | null> {
    return $Call.ByID(3470541042, examID).then(($result: any) => {
        return $$createType25($result);
    });
}

export function GetSubmissions(questionID: string, limit: number): $CancellablePromise<qbank$0.AnswerSubmission[]> {
    return $Call.ByID(762392368, questionID, limit).then(($result: any) => {
        return $$createType27($result);
    });
}

export function GetSyncConflicts(examID: string): $CancellablePromise<qbank$0.SyncConflict[]> {
    return $Call.ByID(3136250955, examID).then(($result: any) => {
        return $$createType29($result);
    });
}

export function ImportQuestionsCsv(request: qbank$0.CsvImportRequest): $CancellablePromise<qbank$0.CsvImportResult> {
    return $Call.ByID(2317553267, request).then(($result: any) => {
        return $$createType30($result);
    });
}

export function ListQuestions(request: qbank$0.ListQuestionsRequest): $CancellablePromise<qbank$0.QuestionListResult> {
    return $Call.ByID(3749039046, request).then(($result: any) => {
        return $$createType31($result);
    });
}

export function NotesMentionsSearch(keyword: string, subject: string | null, limit: number): $CancellablePromise<qbank$0.NotesMentionSearchResult> {
    return $Call.ByID(579726609, keyword, subject, limit).then(($result: any) => {
        return $$createType32($result);
    });
}

export function RebuildFTSIndex(): $CancellablePromise<number> {
    return $Call.ByID(969082929);
}

export function RefreshStats(examID: string): $CancellablePromise<qbank$0.QuestionBankStats> {
    return $Call.ByID(189497351, examID).then(($result: any) => {
        return $$createType24($result);
    });
}

export function ResetProgress(examID: string): $CancellablePromise<qbank$0.QuestionBankStats> {
    return $Call.ByID(3339328059, examID).then(($result: any) => {
        return $$createType24($result);
    });
}

export function ResetQuestionsProgress(questionIDs: string[]): $CancellablePromise<qbank$0.BatchResult> {
    return $Call.ByID(1009228422, questionIDs).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ResolveSyncConflict(conflictID: string, strategy: string): $CancellablePromise<qbank$0.Question> {
    return $Call.ByID(2398198214, conflictID, strategy).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SearchQuestions(request: qbank$0.SearchQuestionsRequest): $CancellablePromise<qbank$0.QuestionSearchListResult> {
    return $Call.ByID(2979133726, request).then(($result: any) => {
        return $$createType33($result);
    });
}

export function SetSyncEnabled(examID: string, enabled: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(640743725, examID, enabled);
}

export function StartTimedPractice(request: qbank$0.StartTimedPracticeRequest): $CancellablePromise<qbank$0.TimedPracticeSession> {
    return $Call.ByID(2752056963, request).then(($result: any) => {
        return $$createType34($result);
    });
}

export function SubmitAnswer(request: qbank$0.SubmitAnswerRequest): $CancellablePromise<qbank$0.SubmitAnswerResult> {
    return $Call.ByID(2125855335, request).then(($result: any) => {
        return $$createType35($result);
    });
}

export function SubmitMockExam(request: qbank$0.SubmitMockExamRequest): $CancellablePromise<qbank$0.MockExamScoreCard> {
    return $Call.ByID(2844739856, request).then(($result: any) => {
        return $$createType36($result);
    });
}

export function ToggleFavorite(questionID: string): $CancellablePromise<qbank$0.Question> {
    return $Call.ByID(2953823173, questionID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateQuestion(request: qbank$0.UpdateQuestionRequest): $CancellablePromise<qbank$0.Question> {
    return $Call.ByID(802740240, request).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateSyncConfig(examID: string, config: qbank$0.SyncConfig): $CancellablePromise<boolean> {
    return $Call.ByID(833450429, examID, config);
}

// Private type creation functions
const $$createType0 = qbank$0.QbankGradingResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = qbank$0.BatchResult.createFrom;
const $$createType3 = qbank$0.Question.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = qbank$0.SyncStatusResult.createFrom;
const $$createType6 = qbank$0.CsvExportResult.createFrom;
const $$createType7 = qbank$0.MockExamSession.createFrom;
const $$createType8 = qbank$0.GeneratedPaper.createFrom;
const $$createType9 = qbank$0.ActivityHeatmapPoint.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = qbank$0.CheckInCalendar.createFrom;
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = qbank$0.CsvPreviewResult.createFrom;
const $$createType15 = qbank$0.DailyPracticeResult.createFrom;
const $$createType16 = qbank$0.QuestionHistory.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = qbank$0.KnowledgePoint.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = qbank$0.KnowledgeStatsComparison.createFrom;
const $$createType21 = qbank$0.LearningTrendPoint.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Nullable($$createType3);
const $$createType24 = qbank$0.QuestionBankStats.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = qbank$0.AnswerSubmission.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = qbank$0.SyncConflict.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = qbank$0.CsvImportResult.createFrom;
const $$createType31 = qbank$0.QuestionListResult.createFrom;
const $$createType32 = qbank$0.NotesMentionSearchResult.createFrom;
const $$createType33 = qbank$0.QuestionSearchListResult.createFrom;
const $$createType34 = qbank$0.TimedPracticeSession.createFrom;
const $$createType35 = qbank$0.SubmitAnswerResult.createFrom;
const $$createType36 = qbank$0.MockExamScoreCard.createFrom;
