// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reviewplan$0 from "../reviewplan/models.js";

export function BatchCreate(questionIDs: string[], examID: string): $CancellablePromise<reviewplan$0.BatchCreateResult> {
    return $Call.ByID(2456174423, questionIDs, examID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Create(questionID: string, examID: string): $CancellablePromise<reviewplan$0.ReviewPlan> {
    return $Call.ByID(3600204441, questionID, examID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateForExam(examID: string): $CancellablePromise<reviewplan$0.BatchCreateResult> {
    return $Call.ByID(1586206175, examID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Delete(planID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2766104558, planID);
}

export function Get(planID: string): $CancellablePromise<reviewplan$0.ReviewPlan | null> {
    return $Call.ByID(1933717707, planID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetByQuestion(questionID: string): $CancellablePromise<reviewplan$0.ReviewPlan | null> {
    return $Call.ByID(2174079302, questionID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetCalendarData(startDate: string | null, endDate: string | null, examID: string | null): $CancellablePromise<reviewplan$0.CalendarHeatmapData[]> {
    return $Call.ByID(89400697, startDate, endDate, examID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetDue(examID: string | null, untilDate: string | null): $CancellablePromise<reviewplan$0.DueReviewsResult> {
    return $Call.ByID(2525777383, examID, untilDate).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetDueWithFilter(filter: reviewplan$0.DueReviewsFilter): $CancellablePromise<reviewplan$0.DueReviewsResult> {
    return $Call.ByID(3484146089, filter).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetHistory(planID: string, limit: number): $CancellablePromise<reviewplan$0.ReviewHistory[]> {
    return $Call.ByID(3466629077, planID, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetOrCreate(questionID: string, examID: string): $CancellablePromise<reviewplan$0.ReviewPlan> {
    return $Call.ByID(2868215214, questionID, examID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetStats(examID: string | null): $CancellablePromise<reviewplan$0.ReviewStats> {
    return $Call.ByID(2322177942, examID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListByExam(examID: string, limit: number, offset: number): $CancellablePromise<reviewplan$0.DueReviewsResult> {
    return $Call.ByID(1219321031, examID, limit, offset).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Process(planID: string, quality: number, userAnswer: string | null, timeSpentSeconds: number | null): $CancellablePromise<reviewplan$0.ProcessReviewResult> {
    return $Call.ByID(4179174358, planID, quality, userAnswer, timeSpentSeconds).then(($result: any) => {
        return $$createType9($result);
    });
}

export function RefreshStats(examID: string | null): $CancellablePromise<reviewplan$0.ReviewStats> {
    return $Call.ByID(1762962011, examID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Resume(planID: string): $CancellablePromise<reviewplan$0.ReviewPlan> {
    return $Call.ByID(1798786670, planID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Suspend(planID: string): $CancellablePromise<reviewplan$0.ReviewPlan> {
    return $Call.ByID(126688159, planID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = reviewplan$0.BatchCreateResult.createFrom;
const $$createType1 = reviewplan$0.ReviewPlan.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = reviewplan$0.CalendarHeatmapData.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = reviewplan$0.DueReviewsResult.createFrom;
const $$createType6 = reviewplan$0.ReviewHistory.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = reviewplan$0.ReviewStats.createFrom;
const $$createType9 = reviewplan$0.ProcessReviewResult.createFrom;
