// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

export function AddOCREngine(configID: string, model: string, name: string, engineType: string | null): $CancellablePromise<boolean> {
    return $Call.ByID(4141003568, configID, model, name, engineType);
}

export function CheckAPIConfigStatus(): $CancellablePromise<settings$0.APIConfigStatus> {
    return $Call.ByID(2656373043).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateAttachmentRootFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(1321477374, title);
}

export function DataDir(): $CancellablePromise<string> {
    return $Call.ByID(2530680446);
}

export function DeleteSetting(key: string): $CancellablePromise<void> {
    return $Call.ByID(1739978560, key);
}

export function GetAPIConfigurations(): $CancellablePromise<settings$0.ApiConfig[]> {
    return $Call.ByID(2182435408).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAttachmentConfig(): $CancellablePromise<settings$0.AttachmentConfig> {
    return $Call.ByID(22950098).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetAvailableOCRModels(): $CancellablePromise<settings$0.AvailableOCRModel[]> {
    return $Call.ByID(3705783926).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetBackupConfig(): $CancellablePromise<settings$0.BackupConfig> {
    return $Call.ByID(1249882817).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetCNWhitelistConfig(): $CancellablePromise<settings$0.CNWhitelistConfigResult> {
    return $Call.ByID(3732136499).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetEnhancedStatistics(): $CancellablePromise<settings$0.EnhancedStatistics> {
    return $Call.ByID(1163748432).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetMCPStatus(): $CancellablePromise<settings$0.MCPStatus> {
    return $Call.ByID(1542646489).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetMCPTools(): $CancellablePromise<settings$0.MCPToolInfo[]> {
    return $Call.ByID(2518215406).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetMemoryConfig(): $CancellablePromise<settings$0.MemoryConfig> {
    return $Call.ByID(4177902036).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetModelAdapterOptions(): $CancellablePromise<settings$0.ModelAdapterOption[]> {
    return $Call.ByID(357502709).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetModelAssignments(): $CancellablePromise<settings$0.ModelAssignments> {
    return $Call.ByID(1444889552).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetModelProfiles(): $CancellablePromise<settings$0.ModelProfile[]> {
    return $Call.ByID(4170381496).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetOCREngineType(): $CancellablePromise<string> {
    return $Call.ByID(1723862733);
}

export function GetOCREngines(): $CancellablePromise<settings$0.OCREngineInfo[]> {
    return $Call.ByID(1229224866).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetOCRThinkingEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2680980296);
}

export function GetProviderStrategiesConfig(): $CancellablePromise<settings$0.ProviderStrategiesConfigResult> {
    return $Call.ByID(3947788723).then(($result: any) => {
        return $$createType20($result);
    });
}

export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(976379223, key);
}

export function GetSettings(keys: string[]): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3242762156, keys).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetSettingsByPrefix(prefix: string): $CancellablePromise<string[][]> {
    return $Call.ByID(3082402557, prefix).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetStatistics(): $CancellablePromise<settings$0.BasicStatistics> {
    return $Call.ByID(99208270).then(($result: any) => {
        return $$createType24($result);
    });
}

export function GetVendorConfigs(): $CancellablePromise<settings$0.VendorConfig[]> {
    return $Call.ByID(1426080834).then(($result: any) => {
        return $$createType26($result);
    });
}

export function PreheatMCPTools(): $CancellablePromise<settings$0.MCPPreheatResult> {
    return $Call.ByID(2504021969).then(($result: any) => {
        return $$createType27($result);
    });
}

export function ReloadMCPClient(): $CancellablePromise<settings$0.MCPReloadResult> {
    return $Call.ByID(788636121).then(($result: any) => {
        return $$createType28($result);
    });
}

export function RemoveOCREngine(configID: string): $CancellablePromise<boolean> {
    return $Call.ByID(996569267, configID);
}

export function RestoreDefaultAPIConfigs(): $CancellablePromise<string> {
    return $Call.ByID(842570687);
}

export function SaveAPIConfigurations(configs: settings$0.ApiConfig[]): $CancellablePromise<void> {
    return $Call.ByID(2381815693, configs);
}

export function SaveAvailableOCRModels(models: settings$0.SaveOCRModelRequest[]): $CancellablePromise<boolean> {
    return $Call.ByID(2861947457, models);
}

export function SaveModelAssignments(assignments: settings$0.ModelAssignments): $CancellablePromise<void> {
    return $Call.ByID(30012095, assignments);
}

export function SaveModelProfiles(profiles: settings$0.ModelProfile[]): $CancellablePromise<void> {
    return $Call.ByID(3364078169, profiles);
}

export function SaveProviderStrategiesConfig(strategies: settings$0.ProviderStrategies): $CancellablePromise<boolean> {
    return $Call.ByID(1804846556, strategies);
}

export function SaveSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1796832462, key, value);
}

export function SaveSettings(values: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(1444896135, values);
}

export function SaveVendorConfigs(configs: settings$0.VendorConfig[]): $CancellablePromise<void> {
    return $Call.ByID(2573975871, configs);
}

export function SetAttachmentRootFolder(folderID: string): $CancellablePromise<void> {
    return $Call.ByID(1231137404, folderID);
}

export function SetBackupConfig(config: settings$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(3728179797, config);
}

export function SetOCRThinkingEnabled(enabled: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(1264395236, enabled);
}

export function TestAPIConnection(apiKey: string, apiBase: string, apiProtocol: string | null, supportsOpenAIResponses: boolean | null, model: string | null, vendorID: string | null): $CancellablePromise<boolean> {
    return $Call.ByID(1288192269, apiKey, apiBase, apiProtocol, supportsOpenAIResponses, model, vendorID);
}

export function TestAllSearchEngines(): $CancellablePromise<settings$0.SearchEngineHealthReport> {
    return $Call.ByID(3558475509).then(($result: any) => {
        return $$createType29($result);
    });
}

export function TestOCREngine(request: settings$0.OCRTestRequest): $CancellablePromise<settings$0.OCRTestResponse> {
    return $Call.ByID(1423547659, request).then(($result: any) => {
        return $$createType30($result);
    });
}

export function TestSearchEngine(engine: string): $CancellablePromise<settings$0.SearchEngineTestResult> {
    return $Call.ByID(3528959589, engine).then(($result: any) => {
        return $$createType31($result);
    });
}

export function TestWebSearchConnectivity(engine: string | null): $CancellablePromise<settings$0.WebSearchConnectivityResult> {
    return $Call.ByID(361551872, engine).then(($result: any) => {
        return $$createType32($result);
    });
}

export function UpdateOCREnginePriority(engineList: settings$0.UpdateOCRPriorityItem[]): $CancellablePromise<boolean> {
    return $Call.ByID(2021023652, engineList);
}

// Private type creation functions
const $$createType0 = settings$0.APIConfigStatus.createFrom;
const $$createType1 = settings$0.ApiConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = settings$0.AttachmentConfig.createFrom;
const $$createType4 = settings$0.AvailableOCRModel.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = settings$0.BackupConfig.createFrom;
const $$createType7 = settings$0.CNWhitelistConfigResult.createFrom;
const $$createType8 = settings$0.EnhancedStatistics.createFrom;
const $$createType9 = settings$0.MCPStatus.createFrom;
const $$createType10 = settings$0.MCPToolInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = settings$0.MemoryConfig.createFrom;
const $$createType13 = settings$0.ModelAdapterOption.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = settings$0.ModelAssignments.createFrom;
const $$createType16 = settings$0.ModelProfile.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = settings$0.OCREngineInfo.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = settings$0.ProviderStrategiesConfigResult.createFrom;
const $$createType21 = $Create.Map($Create.Any, $Create.Any);
const $$createType22 = $Create.Array($Create.Any);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = settings$0.BasicStatistics.createFrom;
const $$createType25 = settings$0.VendorConfig.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = settings$0.MCPPreheatResult.createFrom;
const $$createType28 = settings$0.MCPReloadResult.createFrom;
const $$createType29 = settings$0.SearchEngineHealthReport.createFrom;
const $$createType30 = settings$0.OCRTestResponse.createFrom;
const $$createType31 = settings$0.SearchEngineTestResult.createFrom;
const $$createType32 = settings$0.WebSearchConnectivityResult.createFrom;
