// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "../skills/models.js";

export function Create(basePath: string, skillID: string, content: string): $CancellablePromise<skills$0.FileContent> {
    return $Call.ByID(2595420257, basePath, skillID, content).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Delete(path: string): $CancellablePromise<void> {
    return $Call.ByID(3655402502, path);
}

export function ListDirectories(path: string): $CancellablePromise<skills$0.DirectoryEntry[]> {
    return $Call.ByID(1053100468, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReadFile(path: string): $CancellablePromise<skills$0.FileContent> {
    return $Call.ByID(3559182039, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Update(path: string, content: string): $CancellablePromise<skills$0.FileContent> {
    return $Call.ByID(1738139760, path, content).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = skills$0.FileContent.createFrom;
const $$createType1 = skills$0.DirectoryEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
