// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "../system/models.js";

export function AppDataDir(): $CancellablePromise<string> {
    return $Call.ByID(1251746965);
}

export function EnsureDebugLogDir(): $CancellablePromise<string> {
    return $Call.ByID(2760244101);
}

export function OpenLogsFolder(logType: string): $CancellablePromise<void> {
    return $Call.ByID(3267857288, logType);
}

export function ReportFrontendLog(payload: system$0.FrontendLogPayload): $CancellablePromise<void> {
    return $Call.ByID(965743257, payload);
}

export function SaveWebviewSettings(settings: { [_ in string]?: any }): $CancellablePromise<system$0.SaveWebviewSettingsResult> {
    return $Call.ByID(3104018748, settings).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = system$0.SaveWebviewSettingsResult.createFrom;
