// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as templates$0 from "../templates/models.js";

export function CreateCustomTemplate(request: { [_ in string]?: any }): $CancellablePromise<string> {
    return $Call.ByID(3358248901, request);
}

export function DeleteCustomTemplate(templateID: string): $CancellablePromise<void> {
    return $Call.ByID(2841048394, templateID);
}

export function ExportTemplate(templateID: string): $CancellablePromise<templates$0.TemplateExportResponse> {
    return $Call.ByID(739818272, templateID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetAllCustomTemplates(): $CancellablePromise<templates$0.Template[]> {
    return $Call.ByID(4073960271).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetDefaultTemplateID(): $CancellablePromise<string | null> {
    return $Call.ByID(1055004290);
}

export function ImportBuiltinTemplates(): $CancellablePromise<string> {
    return $Call.ByID(3450196299);
}

export function ImportCustomTemplatesBulk(templateData: string, overwriteExisting: boolean, strictBuiltin: boolean): $CancellablePromise<string> {
    return $Call.ByID(2964429665, templateData, overwriteExisting, strictBuiltin);
}

export function SetDefaultTemplate(templateID: string): $CancellablePromise<void> {
    return $Call.ByID(1912273163, templateID);
}

export function UpdateCustomTemplate(templateID: string, request: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(3796979684, templateID, request);
}

// Private type creation functions
const $$createType0 = templates$0.TemplateExportResponse.createFrom;
var $$createType1 = (function $$initCreateType1(...args: any[]): any {
    if ($$createType1 === $$initCreateType1) {
        $$createType1 = $$createType2;
    }
    return $$createType1(...args);
});
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType1);
