// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as todo$0 from "../todo/models.js";

export function ActiveSummary(): $CancellablePromise<todo$0.TodoActiveSummary | null> {
    return $Call.ByID(3826956592).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateItem(input: todo$0.CreateTodoItemInput): $CancellablePromise<todo$0.TodoItem> {
    return $Call.ByID(3327674801, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateList(input: todo$0.CreateTodoListInput): $CancellablePromise<todo$0.TodoList> {
    return $Call.ByID(3210268950, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CreatePomodoroRecord(input: todo$0.CreatePomodoroInput): $CancellablePromise<todo$0.PomodoroRecord> {
    return $Call.ByID(353074700, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DeleteItem(itemID: string): $CancellablePromise<void> {
    return $Call.ByID(3925231586, itemID);
}

export function DeleteList(listID: string): $CancellablePromise<void> {
    return $Call.ByID(2469895157, listID);
}

export function EnsureInbox(): $CancellablePromise<todo$0.TodoList> {
    return $Call.ByID(2560353192).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetItem(itemID: string): $CancellablePromise<todo$0.TodoItem | null> {
    return $Call.ByID(1850393697, itemID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetList(listID: string): $CancellablePromise<todo$0.TodoList | null> {
    return $Call.ByID(3874175206, listID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetPomodoroRecord(recordID: string): $CancellablePromise<todo$0.PomodoroRecord | null> {
    return $Call.ByID(2759401756, recordID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListCompleted(listID: string | null): $CancellablePromise<todo$0.TodoItem[]> {
    return $Call.ByID(1071811327, listID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListItems(listID: string, includeCompleted: boolean): $CancellablePromise<todo$0.TodoItem[]> {
    return $Call.ByID(3333484278, listID, includeCompleted).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListLists(): $CancellablePromise<todo$0.TodoList[]> {
    return $Call.ByID(458620207).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListOverdue(includeCompleted: boolean): $CancellablePromise<todo$0.TodoItem[]> {
    return $Call.ByID(103205458, includeCompleted).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListPomodorosByTodo(todoItemID: string): $CancellablePromise<todo$0.PomodoroRecord[]> {
    return $Call.ByID(465974635, todoItemID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListToday(includeCompleted: boolean): $CancellablePromise<todo$0.TodoItem[]> {
    return $Call.ByID(4136704907, includeCompleted).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListTodayPomodoros(): $CancellablePromise<todo$0.PomodoroRecord[]> {
    return $Call.ByID(4091727813).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListUpcoming(days: number, includeCompleted: boolean): $CancellablePromise<todo$0.TodoItem[]> {
    return $Call.ByID(419866076, days, includeCompleted).then(($result: any) => {
        return $$createType8($result);
    });
}

export function PomodoroTodayStats(): $CancellablePromise<todo$0.PomodoroTodayStats> {
    return $Call.ByID(3667548913).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ReorderItems(input: todo$0.ReorderItemsInput): $CancellablePromise<void> {
    return $Call.ByID(2775021695, input);
}

export function Search(query: string): $CancellablePromise<todo$0.TodoItem[]> {
    return $Call.ByID(223603598, query).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ToggleItem(itemID: string): $CancellablePromise<todo$0.TodoItem> {
    return $Call.ByID(2403001253, itemID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ToggleListFavorite(listID: string): $CancellablePromise<todo$0.TodoList> {
    return $Call.ByID(1571287246, listID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateItem(input: todo$0.UpdateTodoItemInput): $CancellablePromise<todo$0.TodoItem> {
    return $Call.ByID(1531618592, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateList(input: todo$0.UpdateTodoListInput): $CancellablePromise<todo$0.TodoList> {
    return $Call.ByID(573148623, input).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = todo$0.TodoActiveSummary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = todo$0.TodoItem.createFrom;
const $$createType3 = todo$0.TodoList.createFrom;
const $$createType4 = todo$0.PomodoroRecord.createFrom;
const $$createType5 = $Create.Nullable($$createType2);
const $$createType6 = $Create.Nullable($$createType3);
const $$createType7 = $Create.Nullable($$createType4);
const $$createType8 = $Create.Array($$createType2);
const $$createType9 = $Create.Array($$createType3);
const $$createType10 = $Create.Array($$createType4);
const $$createType11 = todo$0.PomodoroTodayStats.createFrom;
