// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vfs$0 from "../vfs/models.js";

export function BatchIndexPending(batchSize: number): $CancellablePromise<vfs$0.BatchIndexResult> {
    return $Call.ByID(2746819464, batchSize).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CancelPdfProcessing(fileID: string): $CancellablePromise<boolean> {
    return $Call.ByID(414693352, fileID);
}

export function ClearResourceOcr(resourceID: string): $CancellablePromise<boolean> {
    return $Call.ByID(263239410, resourceID);
}

export function CreateMindMap(params: vfs$0.CreateMindMapInput): $CancellablePromise<vfs$0.VfsMindMap> {
    return $Call.ByID(2724821293, params).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateOrReuse(params: vfs$0.CreateResourceInput): $CancellablePromise<vfs$0.CreateResourceResult> {
    return $Call.ByID(1356685292, params).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DecrementRef(resourceID: string): $CancellablePromise<number> {
    return $Call.ByID(3588767131, resourceID);
}

export function DeleteFile(fileID: string): $CancellablePromise<void> {
    return $Call.ByID(4102280972, fileID);
}

export function DeleteMindMap(mindmapID: string): $CancellablePromise<void> {
    return $Call.ByID(3563874888, mindmapID);
}

export function DeleteResourceIndex(resourceID: string): $CancellablePromise<vfs$0.DeleteIndexResult> {
    return $Call.ByID(135957782, resourceID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetAllIndexStatus(input: vfs$0.GetIndexStatusInput): $CancellablePromise<vfs$0.ResourceIndexStatusSummary> {
    return $Call.ByID(3517417800, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetAttachment(attachmentID: string): $CancellablePromise<vfs$0.Attachment | null> {
    return $Call.ByID(2735609986, attachmentID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetAttachmentContent(attachmentID: string): $CancellablePromise<vfs$0.AttachmentContentResult> {
    return $Call.ByID(3076243867, attachmentID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetBatchPdfProcessingStatus(fileIDs: string[]): $CancellablePromise<{ [_ in string]?: vfs$0.PdfProcessingStatus }> {
    return $Call.ByID(2862795004, fileIDs).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetBlobBase64(blobHash: string): $CancellablePromise<vfs$0.VfsBlobBase64Result> {
    return $Call.ByID(3277761511, blobHash).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetFile(fileID: string): $CancellablePromise<vfs$0.VfsFile | null> {
    return $Call.ByID(1181348489, fileID).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetFileContent(fileID: string): $CancellablePromise<vfs$0.AttachmentContentResult> {
    return $Call.ByID(433183662, fileID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetMindMap(mindmapID: string): $CancellablePromise<vfs$0.VfsMindMap | null> {
    return $Call.ByID(3692934543, mindmapID).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetMindMapContent(mindmapID: string): $CancellablePromise<string | null> {
    return $Call.ByID(1382329144, mindmapID);
}

export function GetMindMapVersion(versionID: string): $CancellablePromise<vfs$0.VfsMindMapVersion | null> {
    return $Call.ByID(4111038001, versionID).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetMindMapVersionContent(versionID: string): $CancellablePromise<string | null> {
    return $Call.ByID(1850644374, versionID);
}

export function GetMindMapVersions(mindmapID: string): $CancellablePromise<vfs$0.VfsMindMapVersion[]> {
    return $Call.ByID(4293208550, mindmapID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetPdfPageImage(resourceID: string, pageIndex: number): $CancellablePromise<vfs$0.PdfPageImageResult> {
    return $Call.ByID(1653099617, resourceID, pageIndex).then(($result: any) => {
        return $$createType17($result);
    });
}

export function GetPdfProcessingStatus(fileID: string): $CancellablePromise<vfs$0.PdfProcessingStatus> {
    return $Call.ByID(64572422, fileID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetResource(resourceID: string): $CancellablePromise<vfs$0.Resource | null> {
    return $Call.ByID(3093193763, resourceID).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetResourceOcrInfo(resourceID: string): $CancellablePromise<vfs$0.ResourceOcrInfo> {
    return $Call.ByID(2641947605, resourceID).then(($result: any) => {
        return $$createType20($result);
    });
}

export function GetResourcePath(sourceID: string): $CancellablePromise<string | null> {
    return $Call.ByID(613372068, sourceID);
}

export function GetResourceRefCount(sourceID: string): $CancellablePromise<number> {
    return $Call.ByID(1958005859, sourceID);
}

export function GetResourceRefs(input: vfs$0.GetResourceRefsInput): $CancellablePromise<vfs$0.ContextRefData> {
    return $Call.ByID(3501177373, input).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetResourceTextChunks(resourceID: string): $CancellablePromise<vfs$0.TextChunkInfo[]> {
    return $Call.ByID(1579899790, resourceID).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetResourceUnits(resourceID: string): $CancellablePromise<vfs$0.UnitIndexStatus[]> {
    return $Call.ByID(2025151198, resourceID).then(($result: any) => {
        return $$createType25($result);
    });
}

export function IncrementRef(resourceID: string): $CancellablePromise<number> {
    return $Call.ByID(3958292591, resourceID);
}

export function ListDimensions(): $CancellablePromise<vfs$0.VfsEmbeddingDimension[]> {
    return $Call.ByID(3103528828).then(($result: any) => {
        return $$createType27($result);
    });
}

export function ListEmbeddingDims(): $CancellablePromise<vfs$0.EmbeddingDimInfo[]> {
    return $Call.ByID(1635631105).then(($result: any) => {
        return $$createType29($result);
    });
}

export function ListFiles(input: vfs$0.ListFilesInput): $CancellablePromise<vfs$0.VfsFile[]> {
    return $Call.ByID(3628958556, input).then(($result: any) => {
        return $$createType30($result);
    });
}

export function ListMindMaps(): $CancellablePromise<vfs$0.VfsMindMap[]> {
    return $Call.ByID(428642174).then(($result: any) => {
        return $$createType31($result);
    });
}

export function RagSearch(input: vfs$0.VfsRagSearchInput): $CancellablePromise<vfs$0.VfsRagSearchOutput> {
    return $Call.ByID(3689477085, input).then(($result: any) => {
        return $$createType32($result);
    });
}

export function ReindexResource(resourceID: string): $CancellablePromise<number> {
    return $Call.ByID(3039034864, resourceID);
}

export function ReindexUnit(unitID: string, mode: string): $CancellablePromise<boolean> {
    return $Call.ByID(132564690, unitID, mode);
}

export function ResolveResourceRefs(refs: vfs$0.ResourceRef[]): $CancellablePromise<vfs$0.ResolvedResource[]> {
    return $Call.ByID(4139636137, refs).then(($result: any) => {
        return $$createType34($result);
    });
}

export function ResourceCheckSyncNeeded(resourceType: string, sourceID: string, currentHash: string | null): $CancellablePromise<vfs$0.CheckSyncNeededResponse> {
    return $Call.ByID(194619077, resourceType, sourceID, currentHash).then(($result: any) => {
        return $$createType35($result);
    });
}

export function ResourceExists(resourceID: string): $CancellablePromise<boolean> {
    return $Call.ByID(731370541, resourceID);
}

export function ResourceSyncExam(sessionID: string): $CancellablePromise<vfs$0.ResourceSyncResult> {
    return $Call.ByID(1257111797, sessionID).then(($result: any) => {
        return $$createType36($result);
    });
}

export function ResourceSyncNote(noteID: string): $CancellablePromise<vfs$0.ResourceSyncResult> {
    return $Call.ByID(854791414, noteID).then(($result: any) => {
        return $$createType36($result);
    });
}

export function ResourceSyncTextbookPages(textbookID: string, pageRange: number[]): $CancellablePromise<vfs$0.ResourceSyncResult[]> {
    return $Call.ByID(2269772212, textbookID, pageRange).then(($result: any) => {
        return $$createType37($result);
    });
}

export function RetryPdfProcessing(fileID: string): $CancellablePromise<void> {
    return $Call.ByID(3104569410, fileID);
}

export function SetMindMapFavorite(mindmapID: string, isFavorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(1181036347, mindmapID, isFavorite);
}

export function StartPdfProcessing(fileID: string, startFromStage: string | null): $CancellablePromise<void> {
    return $Call.ByID(4280865348, fileID, startFromStage);
}

export function SyncResourceUnits(input: vfs$0.SyncResourceUnitsInput): $CancellablePromise<vfs$0.UnitIndexStatus[]> {
    return $Call.ByID(3552671525, input).then(($result: any) => {
        return $$createType25($result);
    });
}

export function UnifiedIndexStatus(): $CancellablePromise<vfs$0.IndexStatusSummary> {
    return $Call.ByID(1166743141).then(($result: any) => {
        return $$createType38($result);
    });
}

export function UpdateBookmarks(fileID: string, bookmarks: any[]): $CancellablePromise<boolean> {
    return $Call.ByID(398848493, fileID, bookmarks);
}

export function UpdateMindMap(mindmapID: string, params: vfs$0.UpdateMindMapInput): $CancellablePromise<vfs$0.VfsMindMap> {
    return $Call.ByID(1460151242, mindmapID, params).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdatePathCache(folderID: string): $CancellablePromise<number> {
    return $Call.ByID(4038919607, folderID);
}

export function UpdateResourceHash(sourceID: string, newHash: string): $CancellablePromise<boolean> {
    return $Call.ByID(3287089176, sourceID, newHash);
}

export function UploadAttachment(params: vfs$0.UploadAttachmentInput): $CancellablePromise<vfs$0.UploadAttachmentResult> {
    return $Call.ByID(3320191385, params).then(($result: any) => {
        return $$createType39($result);
    });
}

export function UploadFile(params: vfs$0.UploadFileInput): $CancellablePromise<vfs$0.UploadFileResult> {
    return $Call.ByID(3923809930, params).then(($result: any) => {
        return $$createType40($result);
    });
}

// Private type creation functions
const $$createType0 = vfs$0.BatchIndexResult.createFrom;
const $$createType1 = vfs$0.VfsMindMap.createFrom;
const $$createType2 = vfs$0.CreateResourceResult.createFrom;
const $$createType3 = vfs$0.DeleteIndexResult.createFrom;
const $$createType4 = vfs$0.ResourceIndexStatusSummary.createFrom;
const $$createType5 = vfs$0.Attachment.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = vfs$0.AttachmentContentResult.createFrom;
const $$createType8 = vfs$0.PdfProcessingStatus.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = vfs$0.VfsBlobBase64Result.createFrom;
const $$createType11 = vfs$0.VfsFile.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Nullable($$createType1);
const $$createType14 = vfs$0.VfsMindMapVersion.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType14);
const $$createType17 = vfs$0.PdfPageImageResult.createFrom;
const $$createType18 = vfs$0.Resource.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = vfs$0.ResourceOcrInfo.createFrom;
const $$createType21 = vfs$0.ContextRefData.createFrom;
const $$createType22 = vfs$0.TextChunkInfo.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = vfs$0.UnitIndexStatus.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = vfs$0.VfsEmbeddingDimension.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = vfs$0.EmbeddingDimInfo.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Array($$createType11);
const $$createType31 = $Create.Array($$createType1);
const $$createType32 = vfs$0.VfsRagSearchOutput.createFrom;
const $$createType33 = vfs$0.ResolvedResource.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = vfs$0.CheckSyncNeededResponse.createFrom;
const $$createType36 = vfs$0.ResourceSyncResult.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = vfs$0.IndexStatusSummary.createFrom;
const $$createType39 = vfs$0.UploadAttachmentResult.createFrom;
const $$createType40 = vfs$0.UploadFileResult.createFrom;
