// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Attachment {
    "id": string;
    "resourceId"?: string | null;
    "blobHash"?: string | null;
    "type": string;
    "name": string;
    "mimeType": string;
    "size": number;
    "contentHash": string;
    "isFavorite": boolean;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("contentHash" in $$source)) {
            this["contentHash"] = "";
        }
        if (!("isFavorite" in $$source)) {
            this["isFavorite"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}

export class AttachmentContentResult {
    "content"?: string | null;
    "found": boolean;
    "error"?: string | null;

    /** Creates a new AttachmentContentResult instance. */
    constructor($$source: Partial<AttachmentContentResult> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentContentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentContentResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentContentResult($$parsedSource as Partial<AttachmentContentResult>);
    }
}

export class BatchIndexResult {
    "successCount": number;
    "failCount": number;
    "total": number;

    /** Creates a new BatchIndexResult instance. */
    constructor($$source: Partial<BatchIndexResult> = {}) {
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failCount" in $$source)) {
            this["failCount"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchIndexResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchIndexResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchIndexResult($$parsedSource as Partial<BatchIndexResult>);
    }
}

export class CheckSyncNeededResponse {
    "needsSync": boolean;
    "existingResourceId"?: string | null;
    "existingHash"?: string | null;

    /** Creates a new CheckSyncNeededResponse instance. */
    constructor($$source: Partial<CheckSyncNeededResponse> = {}) {
        if (!("needsSync" in $$source)) {
            this["needsSync"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckSyncNeededResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckSyncNeededResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckSyncNeededResponse($$parsedSource as Partial<CheckSyncNeededResponse>);
    }
}

export class ContextRefData {
    "refs": ResourceRef[];
    "totalCount": number;
    "truncated": boolean;

    /** Creates a new ContextRefData instance. */
    constructor($$source: Partial<ContextRefData> = {}) {
        if (!("refs" in $$source)) {
            this["refs"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextRefData instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextRefData {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("refs" in $$parsedSource) {
            $$parsedSource["refs"] = $$createField0_0($$parsedSource["refs"]);
        }
        return new ContextRefData($$parsedSource as Partial<ContextRefData>);
    }
}

export class CreateMindMapInput {
    "title": string;
    "description"?: string | null;
    "content"?: string;
    "defaultView"?: string | null;
    "theme"?: string | null;
    "folderId"?: string | null;

    /** Creates a new CreateMindMapInput instance. */
    constructor($$source: Partial<CreateMindMapInput> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateMindMapInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateMindMapInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateMindMapInput($$parsedSource as Partial<CreateMindMapInput>);
    }
}

export class CreateResourceInput {
    "type": string;
    "data": string;
    "sourceId"?: string | null;
    "metadata"?: { [_ in string]?: any };
    "subject"?: string | null;

    /** Creates a new CreateResourceInput instance. */
    constructor($$source: Partial<CreateResourceInput> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateResourceInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateResourceInput {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField3_0($$parsedSource["metadata"]);
        }
        return new CreateResourceInput($$parsedSource as Partial<CreateResourceInput>);
    }
}

export class CreateResourceResult {
    "resourceId": string;
    "hash": string;
    "isNew": boolean;

    /** Creates a new CreateResourceResult instance. */
    constructor($$source: Partial<CreateResourceResult> = {}) {
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("isNew" in $$source)) {
            this["isNew"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateResourceResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateResourceResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateResourceResult($$parsedSource as Partial<CreateResourceResult>);
    }
}

export class DeleteIndexResult {
    "sqliteOk": boolean;
    "lanceTextOk": boolean;
    "lanceMmOk": boolean;
    "warnings": string[];
    "retryable": boolean;

    /** Creates a new DeleteIndexResult instance. */
    constructor($$source: Partial<DeleteIndexResult> = {}) {
        if (!("sqliteOk" in $$source)) {
            this["sqliteOk"] = false;
        }
        if (!("lanceTextOk" in $$source)) {
            this["lanceTextOk"] = false;
        }
        if (!("lanceMmOk" in $$source)) {
            this["lanceMmOk"] = false;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("retryable" in $$source)) {
            this["retryable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteIndexResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteIndexResult {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField3_0($$parsedSource["warnings"]);
        }
        return new DeleteIndexResult($$parsedSource as Partial<DeleteIndexResult>);
    }
}

export class DimensionStat {
    "dimension": number;
    "modality": string;
    "count": number;

    /** Creates a new DimensionStat instance. */
    constructor($$source: Partial<DimensionStat> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = 0;
        }
        if (!("modality" in $$source)) {
            this["modality"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DimensionStat instance from a string or object.
     */
    static createFrom($$source: any = {}): DimensionStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DimensionStat($$parsedSource as Partial<DimensionStat>);
    }
}

export class EmbeddingDimInfo {
    "dimension": number;
    "modality": string;
    "lanceTableName": string;
    "recordCount": number;

    /** Creates a new EmbeddingDimInfo instance. */
    constructor($$source: Partial<EmbeddingDimInfo> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = 0;
        }
        if (!("modality" in $$source)) {
            this["modality"] = "";
        }
        if (!("lanceTableName" in $$source)) {
            this["lanceTableName"] = "";
        }
        if (!("recordCount" in $$source)) {
            this["recordCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmbeddingDimInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): EmbeddingDimInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmbeddingDimInfo($$parsedSource as Partial<EmbeddingDimInfo>);
    }
}

export class GetIndexStatusInput {
    "folderId"?: string | null;
    "resourceType"?: string | null;
    "stateFilter"?: string | null;
    "includeImageIndex"?: boolean;
    "limit"?: number;
    "offset"?: number;

    /** Creates a new GetIndexStatusInput instance. */
    constructor($$source: Partial<GetIndexStatusInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetIndexStatusInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetIndexStatusInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetIndexStatusInput($$parsedSource as Partial<GetIndexStatusInput>);
    }
}

export class GetResourceRefsInput {
    "sourceIds": string[];
    "includeFolderContents"?: boolean;
    "maxItems"?: number;

    /** Creates a new GetResourceRefsInput instance. */
    constructor($$source: Partial<GetResourceRefsInput> = {}) {
        if (!("sourceIds" in $$source)) {
            this["sourceIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetResourceRefsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetResourceRefsInput {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceIds" in $$parsedSource) {
            $$parsedSource["sourceIds"] = $$createField0_0($$parsedSource["sourceIds"]);
        }
        return new GetResourceRefsInput($$parsedSource as Partial<GetResourceRefsInput>);
    }
}

export class IndexStatus {
    "queued": boolean;
    "unitsCreated": number;
    "message": string;

    /** Creates a new IndexStatus instance. */
    constructor($$source: Partial<IndexStatus> = {}) {
        if (!("queued" in $$source)) {
            this["queued"] = false;
        }
        if (!("unitsCreated" in $$source)) {
            this["unitsCreated"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexStatus($$parsedSource as Partial<IndexStatus>);
    }
}

export class IndexStatusSummary {
    "totalUnits": number;
    "textStats": StateStats;
    "mmStats": StateStats;
    "dimensions": DimensionStat[];

    /** Creates a new IndexStatusSummary instance. */
    constructor($$source: Partial<IndexStatusSummary> = {}) {
        if (!("totalUnits" in $$source)) {
            this["totalUnits"] = 0;
        }
        if (!("textStats" in $$source)) {
            this["textStats"] = (new StateStats());
        }
        if (!("mmStats" in $$source)) {
            this["mmStats"] = (new StateStats());
        }
        if (!("dimensions" in $$source)) {
            this["dimensions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexStatusSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexStatusSummary {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("textStats" in $$parsedSource) {
            $$parsedSource["textStats"] = $$createField1_0($$parsedSource["textStats"]);
        }
        if ("mmStats" in $$parsedSource) {
            $$parsedSource["mmStats"] = $$createField2_0($$parsedSource["mmStats"]);
        }
        if ("dimensions" in $$parsedSource) {
            $$parsedSource["dimensions"] = $$createField3_0($$parsedSource["dimensions"]);
        }
        return new IndexStatusSummary($$parsedSource as Partial<IndexStatusSummary>);
    }
}

export class ListFilesInput {
    "fileType"?: string;
    "limit"?: number;
    "offset"?: number;

    /** Creates a new ListFilesInput instance. */
    constructor($$source: Partial<ListFilesInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListFilesInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListFilesInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListFilesInput($$parsedSource as Partial<ListFilesInput>);
    }
}

export class MultimodalBlock {
    "type": string;
    "text"?: string | null;
    "mediaType"?: string | null;
    "base64"?: string | null;

    /** Creates a new MultimodalBlock instance. */
    constructor($$source: Partial<MultimodalBlock> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MultimodalBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): MultimodalBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MultimodalBlock($$parsedSource as Partial<MultimodalBlock>);
    }
}

export class OcrPageInfo {
    "pageIndex": number;
    "text": string;
    "charCount": number;
    "isFailed": boolean;

    /** Creates a new OcrPageInfo instance. */
    constructor($$source: Partial<OcrPageInfo> = {}) {
        if (!("pageIndex" in $$source)) {
            this["pageIndex"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("charCount" in $$source)) {
            this["charCount"] = 0;
        }
        if (!("isFailed" in $$source)) {
            this["isFailed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OcrPageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): OcrPageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OcrPageInfo($$parsedSource as Partial<OcrPageInfo>);
    }
}

export class OcrStatus {
    "performed": boolean;
    "skipReason"?: string | null;
    "successCount": number;
    "failedCount": number;
    "blobMissingCount": number;
    "totalPages": number;
    "allSuccess": boolean;
    "message": string;

    /** Creates a new OcrStatus instance. */
    constructor($$source: Partial<OcrStatus> = {}) {
        if (!("performed" in $$source)) {
            this["performed"] = false;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            this["failedCount"] = 0;
        }
        if (!("blobMissingCount" in $$source)) {
            this["blobMissingCount"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }
        if (!("allSuccess" in $$source)) {
            this["allSuccess"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OcrStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OcrStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OcrStatus($$parsedSource as Partial<OcrStatus>);
    }
}

export class PdfPageImageResult {
    "base64": string;
    "mimeType": string;
    "size": number;

    /** Creates a new PdfPageImageResult instance. */
    constructor($$source: Partial<PdfPageImageResult> = {}) {
        if (!("base64" in $$source)) {
            this["base64"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PdfPageImageResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PdfPageImageResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PdfPageImageResult($$parsedSource as Partial<PdfPageImageResult>);
    }
}

export class PdfProcessingFailedStage {
    "stage": string;
    "message": string;
    "retriable"?: boolean;

    /** Creates a new PdfProcessingFailedStage instance. */
    constructor($$source: Partial<PdfProcessingFailedStage> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PdfProcessingFailedStage instance from a string or object.
     */
    static createFrom($$source: any = {}): PdfProcessingFailedStage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PdfProcessingFailedStage($$parsedSource as Partial<PdfProcessingFailedStage>);
    }
}

export class PdfProcessingProgress {
    "stage": string;
    "currentPage"?: number | null;
    "totalPages"?: number | null;
    "percent": number;
    "readyModes": string[];
    "mediaType"?: string;
    "failedStages"?: PdfProcessingFailedStage[];

    /** Creates a new PdfProcessingProgress instance. */
    constructor($$source: Partial<PdfProcessingProgress> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("readyModes" in $$source)) {
            this["readyModes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PdfProcessingProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): PdfProcessingProgress {
        const $$createField4_0 = $$createType3;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("readyModes" in $$parsedSource) {
            $$parsedSource["readyModes"] = $$createField4_0($$parsedSource["readyModes"]);
        }
        if ("failedStages" in $$parsedSource) {
            $$parsedSource["failedStages"] = $$createField6_0($$parsedSource["failedStages"]);
        }
        return new PdfProcessingProgress($$parsedSource as Partial<PdfProcessingProgress>);
    }
}

export class PdfProcessingStatus {
    "fileId": string;
    "stage": string;
    "currentPage"?: number | null;
    "totalPages"?: number | null;
    "percent": number;
    "readyModes": string[];
    "mediaType"?: string;
    "error"?: string | null;
    "failedStages"?: PdfProcessingFailedStage[];
    "progress": PdfProcessingProgress;

    /** Creates a new PdfProcessingStatus instance. */
    constructor($$source: Partial<PdfProcessingStatus> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("readyModes" in $$source)) {
            this["readyModes"] = [];
        }
        if (!("progress" in $$source)) {
            this["progress"] = (new PdfProcessingProgress());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PdfProcessingStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PdfProcessingStatus {
        const $$createField5_0 = $$createType3;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("readyModes" in $$parsedSource) {
            $$parsedSource["readyModes"] = $$createField5_0($$parsedSource["readyModes"]);
        }
        if ("failedStages" in $$parsedSource) {
            $$parsedSource["failedStages"] = $$createField8_0($$parsedSource["failedStages"]);
        }
        if ("progress" in $$parsedSource) {
            $$parsedSource["progress"] = $$createField9_0($$parsedSource["progress"]);
        }
        return new PdfProcessingStatus($$parsedSource as Partial<PdfProcessingStatus>);
    }
}

export class ResolvedResource {
    "sourceId": string;
    "resourceHash": string;
    "type": string;
    "name": string;
    "path": string;
    "content"?: string | null;
    "byteSize"?: number | null;
    "found": boolean;
    "warning"?: string | null;
    "metadata"?: { [_ in string]?: any };
    "multimodalBlocks"?: MultimodalBlock[];

    /** Creates a new ResolvedResource instance. */
    constructor($$source: Partial<ResolvedResource> = {}) {
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("resourceHash" in $$source)) {
            this["resourceHash"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedResource instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolvedResource {
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField9_0($$parsedSource["metadata"]);
        }
        if ("multimodalBlocks" in $$parsedSource) {
            $$parsedSource["multimodalBlocks"] = $$createField10_0($$parsedSource["multimodalBlocks"]);
        }
        return new ResolvedResource($$parsedSource as Partial<ResolvedResource>);
    }
}

export class Resource {
    "id": string;
    "hash": string;
    "type": string;
    "sourceId"?: string | null;
    "sourceTable"?: string | null;
    "storageMode": string;
    "data"?: string | null;
    "externalHash"?: string | null;
    "externalPath"?: string | null;
    "originalPath"?: string | null;
    "metadata"?: { [_ in string]?: any };
    "refCount": number;
    "createdAt": number;
    "updatedAt": number;
    "contentEncoding"?: string;

    /** Creates a new Resource instance. */
    constructor($$source: Partial<Resource> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("storageMode" in $$source)) {
            this["storageMode"] = "";
        }
        if (!("refCount" in $$source)) {
            this["refCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Resource instance from a string or object.
     */
    static createFrom($$source: any = {}): Resource {
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField10_0($$parsedSource["metadata"]);
        }
        return new Resource($$parsedSource as Partial<Resource>);
    }
}

export class ResourceIndexStatus {
    "resourceId": string;
    "sourceId"?: string | null;
    "resourceType": string;
    "name": string;
    "hasOcr": boolean;
    "ocrCount": number;
    "textIndexState": string;
    "textIndexedAt"?: number | null;
    "textIndexError"?: string | null;
    "textChunkCount": number;
    "nativeTextChunkCount": number;
    "ocrTextChunkCount": number;
    "textEmbeddingDim"?: number | null;
    "textIndexSource"?: string | null;
    "textIndexRetryable": boolean;
    "mmIndexState": string;
    "mmIndexedPages": number;
    "mmEmbeddingDim"?: number | null;
    "mmIndexingMode"?: string | null;
    "mmIndexError"?: string | null;
    "displayIndexState": string;
    "embeddingDim"?: number | null;
    "modality"?: string | null;
    "updatedAt": number;
    "isStale": boolean;

    /** Creates a new ResourceIndexStatus instance. */
    constructor($$source: Partial<ResourceIndexStatus> = {}) {
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("resourceType" in $$source)) {
            this["resourceType"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hasOcr" in $$source)) {
            this["hasOcr"] = false;
        }
        if (!("ocrCount" in $$source)) {
            this["ocrCount"] = 0;
        }
        if (!("textIndexState" in $$source)) {
            this["textIndexState"] = "";
        }
        if (!("textChunkCount" in $$source)) {
            this["textChunkCount"] = 0;
        }
        if (!("nativeTextChunkCount" in $$source)) {
            this["nativeTextChunkCount"] = 0;
        }
        if (!("ocrTextChunkCount" in $$source)) {
            this["ocrTextChunkCount"] = 0;
        }
        if (!("textIndexRetryable" in $$source)) {
            this["textIndexRetryable"] = false;
        }
        if (!("mmIndexState" in $$source)) {
            this["mmIndexState"] = "";
        }
        if (!("mmIndexedPages" in $$source)) {
            this["mmIndexedPages"] = 0;
        }
        if (!("displayIndexState" in $$source)) {
            this["displayIndexState"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("isStale" in $$source)) {
            this["isStale"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceIndexStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceIndexStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceIndexStatus($$parsedSource as Partial<ResourceIndexStatus>);
    }
}

export class ResourceIndexStatusSummary {
    "totalResources": number;
    "indexedCount": number;
    "pendingCount": number;
    "indexingCount": number;
    "failedCount": number;
    "disabledCount": number;
    "staleCount": number;
    "textQueueCount": number;
    "textTotalResources": number;
    "textIndexedCount": number;
    "textPendingCount": number;
    "textIndexingCount": number;
    "textFailedCount": number;
    "textDisabledCount": number;
    "displayTotalResources": number;
    "displayIndexedCount": number;
    "displayPendingCount": number;
    "displayIndexingCount": number;
    "displayFailedCount": number;
    "displayDisabledCount": number;
    "mmTotalResources": number;
    "mmIndexedCount": number;
    "mmPendingCount": number;
    "mmIndexingCount": number;
    "mmFailedCount": number;
    "mmDisabledCount": number;
    "resources": ResourceIndexStatus[];

    /** Creates a new ResourceIndexStatusSummary instance. */
    constructor($$source: Partial<ResourceIndexStatusSummary> = {}) {
        if (!("totalResources" in $$source)) {
            this["totalResources"] = 0;
        }
        if (!("indexedCount" in $$source)) {
            this["indexedCount"] = 0;
        }
        if (!("pendingCount" in $$source)) {
            this["pendingCount"] = 0;
        }
        if (!("indexingCount" in $$source)) {
            this["indexingCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            this["failedCount"] = 0;
        }
        if (!("disabledCount" in $$source)) {
            this["disabledCount"] = 0;
        }
        if (!("staleCount" in $$source)) {
            this["staleCount"] = 0;
        }
        if (!("textQueueCount" in $$source)) {
            this["textQueueCount"] = 0;
        }
        if (!("textTotalResources" in $$source)) {
            this["textTotalResources"] = 0;
        }
        if (!("textIndexedCount" in $$source)) {
            this["textIndexedCount"] = 0;
        }
        if (!("textPendingCount" in $$source)) {
            this["textPendingCount"] = 0;
        }
        if (!("textIndexingCount" in $$source)) {
            this["textIndexingCount"] = 0;
        }
        if (!("textFailedCount" in $$source)) {
            this["textFailedCount"] = 0;
        }
        if (!("textDisabledCount" in $$source)) {
            this["textDisabledCount"] = 0;
        }
        if (!("displayTotalResources" in $$source)) {
            this["displayTotalResources"] = 0;
        }
        if (!("displayIndexedCount" in $$source)) {
            this["displayIndexedCount"] = 0;
        }
        if (!("displayPendingCount" in $$source)) {
            this["displayPendingCount"] = 0;
        }
        if (!("displayIndexingCount" in $$source)) {
            this["displayIndexingCount"] = 0;
        }
        if (!("displayFailedCount" in $$source)) {
            this["displayFailedCount"] = 0;
        }
        if (!("displayDisabledCount" in $$source)) {
            this["displayDisabledCount"] = 0;
        }
        if (!("mmTotalResources" in $$source)) {
            this["mmTotalResources"] = 0;
        }
        if (!("mmIndexedCount" in $$source)) {
            this["mmIndexedCount"] = 0;
        }
        if (!("mmPendingCount" in $$source)) {
            this["mmPendingCount"] = 0;
        }
        if (!("mmIndexingCount" in $$source)) {
            this["mmIndexingCount"] = 0;
        }
        if (!("mmFailedCount" in $$source)) {
            this["mmFailedCount"] = 0;
        }
        if (!("mmDisabledCount" in $$source)) {
            this["mmDisabledCount"] = 0;
        }
        if (!("resources" in $$source)) {
            this["resources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceIndexStatusSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceIndexStatusSummary {
        const $$createField26_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField26_0($$parsedSource["resources"]);
        }
        return new ResourceIndexStatusSummary($$parsedSource as Partial<ResourceIndexStatusSummary>);
    }
}

export class ResourceInjectModes {
    "image"?: string[];
    "pdf"?: string[];

    /** Creates a new ResourceInjectModes instance. */
    constructor($$source: Partial<ResourceInjectModes> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceInjectModes instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceInjectModes {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("image" in $$parsedSource) {
            $$parsedSource["image"] = $$createField0_0($$parsedSource["image"]);
        }
        if ("pdf" in $$parsedSource) {
            $$parsedSource["pdf"] = $$createField1_0($$parsedSource["pdf"]);
        }
        return new ResourceInjectModes($$parsedSource as Partial<ResourceInjectModes>);
    }
}

export class ResourceOcrInfo {
    "resourceId": string;
    "resourceType": string;
    "hasOcr": boolean;
    "ocrText": string | null;
    "ocrTextLength": number;
    "extractedText": string | null;
    "extractedTextLength": number;
    "activeSource": string;
    "ocrPages": OcrPageInfo[];

    /** Creates a new ResourceOcrInfo instance. */
    constructor($$source: Partial<ResourceOcrInfo> = {}) {
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("resourceType" in $$source)) {
            this["resourceType"] = "";
        }
        if (!("hasOcr" in $$source)) {
            this["hasOcr"] = false;
        }
        if (!("ocrText" in $$source)) {
            this["ocrText"] = null;
        }
        if (!("ocrTextLength" in $$source)) {
            this["ocrTextLength"] = 0;
        }
        if (!("extractedText" in $$source)) {
            this["extractedText"] = null;
        }
        if (!("extractedTextLength" in $$source)) {
            this["extractedTextLength"] = 0;
        }
        if (!("activeSource" in $$source)) {
            this["activeSource"] = "";
        }
        if (!("ocrPages" in $$source)) {
            this["ocrPages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceOcrInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceOcrInfo {
        const $$createField8_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ocrPages" in $$parsedSource) {
            $$parsedSource["ocrPages"] = $$createField8_0($$parsedSource["ocrPages"]);
        }
        return new ResourceOcrInfo($$parsedSource as Partial<ResourceOcrInfo>);
    }
}

export class ResourceRef {
    "sourceId": string;
    "resourceHash": string;
    "type": string;
    "name": string;
    "resourceId"?: string | null;
    "snippet"?: string | null;
    "injectModes"?: ResourceInjectModes | null;

    /** Creates a new ResourceRef instance. */
    constructor($$source: Partial<ResourceRef> = {}) {
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("resourceHash" in $$source)) {
            this["resourceHash"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceRef {
        const $$createField6_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("injectModes" in $$parsedSource) {
            $$parsedSource["injectModes"] = $$createField6_0($$parsedSource["injectModes"]);
        }
        return new ResourceRef($$parsedSource as Partial<ResourceRef>);
    }
}

export class ResourceSyncResult {
    "resourceId": string;
    "hash": string;
    "isNew": boolean;

    /** Creates a new ResourceSyncResult instance. */
    constructor($$source: Partial<ResourceSyncResult> = {}) {
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("isNew" in $$source)) {
            this["isNew"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceSyncResult($$parsedSource as Partial<ResourceSyncResult>);
    }
}

export class StateStats {
    "pending": number;
    "indexing": number;
    "indexed": number;
    "failed": number;
    "disabled": number;

    /** Creates a new StateStats instance. */
    constructor($$source: Partial<StateStats> = {}) {
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("indexing" in $$source)) {
            this["indexing"] = 0;
        }
        if (!("indexed" in $$source)) {
            this["indexed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StateStats instance from a string or object.
     */
    static createFrom($$source: any = {}): StateStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StateStats($$parsedSource as Partial<StateStats>);
    }
}

export class SyncResourceUnitsInput {
    "resourceId": string;
    "resourceType": string;
    "data"?: string | null;
    "ocrText"?: string | null;
    "ocrPagesJson"?: string | null;
    "blobHash"?: string | null;
    "pageCount"?: number | null;
    "extractedText"?: string | null;
    "previewJson"?: string | null;

    /** Creates a new SyncResourceUnitsInput instance. */
    constructor($$source: Partial<SyncResourceUnitsInput> = {}) {
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("resourceType" in $$source)) {
            this["resourceType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResourceUnitsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResourceUnitsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResourceUnitsInput($$parsedSource as Partial<SyncResourceUnitsInput>);
    }
}

export class TextChunkInfo {
    "unitId": string;
    "unitIndex": number;
    "textContent": string | null;
    "textSource": string | null;
    "textState": string;
    "textChunkCount": number;
    "charCount": number;

    /** Creates a new TextChunkInfo instance. */
    constructor($$source: Partial<TextChunkInfo> = {}) {
        if (!("unitId" in $$source)) {
            this["unitId"] = "";
        }
        if (!("unitIndex" in $$source)) {
            this["unitIndex"] = 0;
        }
        if (!("textContent" in $$source)) {
            this["textContent"] = null;
        }
        if (!("textSource" in $$source)) {
            this["textSource"] = null;
        }
        if (!("textState" in $$source)) {
            this["textState"] = "";
        }
        if (!("textChunkCount" in $$source)) {
            this["textChunkCount"] = 0;
        }
        if (!("charCount" in $$source)) {
            this["charCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextChunkInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TextChunkInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextChunkInfo($$parsedSource as Partial<TextChunkInfo>);
    }
}

export class UnitIndexStatus {
    "unitId": string;
    "resourceId": string;
    "unitIndex": number;
    "hasImage": boolean;
    "hasText": boolean;
    "textSource": string | null;
    "textRequired": boolean;
    "textState": string;
    "textError": string | null;
    "textChunkCount": number;
    "textEmbeddingDim": number | null;
    "mmRequired": boolean;
    "mmState": string;
    "mmError": string | null;
    "mmEmbeddingDim": number | null;
    "updatedAt": number;

    /** Creates a new UnitIndexStatus instance. */
    constructor($$source: Partial<UnitIndexStatus> = {}) {
        if (!("unitId" in $$source)) {
            this["unitId"] = "";
        }
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("unitIndex" in $$source)) {
            this["unitIndex"] = 0;
        }
        if (!("hasImage" in $$source)) {
            this["hasImage"] = false;
        }
        if (!("hasText" in $$source)) {
            this["hasText"] = false;
        }
        if (!("textSource" in $$source)) {
            this["textSource"] = null;
        }
        if (!("textRequired" in $$source)) {
            this["textRequired"] = false;
        }
        if (!("textState" in $$source)) {
            this["textState"] = "";
        }
        if (!("textError" in $$source)) {
            this["textError"] = null;
        }
        if (!("textChunkCount" in $$source)) {
            this["textChunkCount"] = 0;
        }
        if (!("textEmbeddingDim" in $$source)) {
            this["textEmbeddingDim"] = null;
        }
        if (!("mmRequired" in $$source)) {
            this["mmRequired"] = false;
        }
        if (!("mmState" in $$source)) {
            this["mmState"] = "";
        }
        if (!("mmError" in $$source)) {
            this["mmError"] = null;
        }
        if (!("mmEmbeddingDim" in $$source)) {
            this["mmEmbeddingDim"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnitIndexStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UnitIndexStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnitIndexStatus($$parsedSource as Partial<UnitIndexStatus>);
    }
}

export class UpdateMindMapInput {
    "title"?: string | null;
    "description"?: string | null;
    "content"?: string | null;
    "defaultView"?: string | null;
    "theme"?: string | null;
    "settings"?: { [_ in string]?: any };
    "expectedUpdatedAt"?: string | null;

    /** Creates a new UpdateMindMapInput instance. */
    constructor($$source: Partial<UpdateMindMapInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateMindMapInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateMindMapInput {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField5_0($$parsedSource["settings"]);
        }
        return new UpdateMindMapInput($$parsedSource as Partial<UpdateMindMapInput>);
    }
}

export class UploadAttachmentInput {
    "name": string;
    "mimeType": string;
    "base64Content": string;
    "attachmentType"?: string | null;
    "folderId"?: string | null;
    "sessionId"?: string | null;
    "groupId"?: string | null;

    /** Creates a new UploadAttachmentInput instance. */
    constructor($$source: Partial<UploadAttachmentInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("base64Content" in $$source)) {
            this["base64Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadAttachmentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadAttachmentInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadAttachmentInput($$parsedSource as Partial<UploadAttachmentInput>);
    }
}

export class UploadAttachmentResult {
    "sourceId": string;
    "resourceHash": string;
    "isNew": boolean;
    "attachment": Attachment;
    "processingStatus"?: string | null;
    "processingPercent"?: number | null;
    "readyModes"?: string[];

    /** Creates a new UploadAttachmentResult instance. */
    constructor($$source: Partial<UploadAttachmentResult> = {}) {
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("resourceHash" in $$source)) {
            this["resourceHash"] = "";
        }
        if (!("isNew" in $$source)) {
            this["isNew"] = false;
        }
        if (!("attachment" in $$source)) {
            this["attachment"] = (new Attachment());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadAttachmentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadAttachmentResult {
        const $$createField3_0 = $$createType18;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachment" in $$parsedSource) {
            $$parsedSource["attachment"] = $$createField3_0($$parsedSource["attachment"]);
        }
        if ("readyModes" in $$parsedSource) {
            $$parsedSource["readyModes"] = $$createField6_0($$parsedSource["readyModes"]);
        }
        return new UploadAttachmentResult($$parsedSource as Partial<UploadAttachmentResult>);
    }
}

export class UploadFileInput {
    "name": string;
    "mimeType": string;
    "base64Content": string;
    "fileType"?: string | null;
    "folderId"?: string | null;
    "metadata"?: { [_ in string]?: any };

    /** Creates a new UploadFileInput instance. */
    constructor($$source: Partial<UploadFileInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("base64Content" in $$source)) {
            this["base64Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadFileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadFileInput {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField5_0($$parsedSource["metadata"]);
        }
        return new UploadFileInput($$parsedSource as Partial<UploadFileInput>);
    }
}

export class UploadFileResult {
    "file": VfsFile;
    "sourceId": string;
    "resourceHash": string;
    "isNew": boolean;
    "ocrStatus"?: OcrStatus | null;
    "indexStatus"?: IndexStatus | null;

    /** Creates a new UploadFileResult instance. */
    constructor($$source: Partial<UploadFileResult> = {}) {
        if (!("file" in $$source)) {
            this["file"] = (new VfsFile());
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("resourceHash" in $$source)) {
            this["resourceHash"] = "";
        }
        if (!("isNew" in $$source)) {
            this["isNew"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadFileResult {
        const $$createField0_0 = $$createType19;
        const $$createField4_0 = $$createType21;
        const $$createField5_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("file" in $$parsedSource) {
            $$parsedSource["file"] = $$createField0_0($$parsedSource["file"]);
        }
        if ("ocrStatus" in $$parsedSource) {
            $$parsedSource["ocrStatus"] = $$createField4_0($$parsedSource["ocrStatus"]);
        }
        if ("indexStatus" in $$parsedSource) {
            $$parsedSource["indexStatus"] = $$createField5_0($$parsedSource["indexStatus"]);
        }
        return new UploadFileResult($$parsedSource as Partial<UploadFileResult>);
    }
}

export class VfsBlobBase64Result {
    "base64": string;
    "mimeType": string;
    "size": number;

    /** Creates a new VfsBlobBase64Result instance. */
    constructor($$source: Partial<VfsBlobBase64Result> = {}) {
        if (!("base64" in $$source)) {
            this["base64"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsBlobBase64Result instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsBlobBase64Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VfsBlobBase64Result($$parsedSource as Partial<VfsBlobBase64Result>);
    }
}

export class VfsEmbeddingDimension {
    "dimension": number;
    "modality": string;
    "modelConfigId"?: string | null;
    "modelName"?: string | null;
    "recordCount": number;
    "lanceTableName": string;
    "createdAt": number;
    "lastUsedAt": number;

    /** Creates a new VfsEmbeddingDimension instance. */
    constructor($$source: Partial<VfsEmbeddingDimension> = {}) {
        if (!("dimension" in $$source)) {
            this["dimension"] = 0;
        }
        if (!("modality" in $$source)) {
            this["modality"] = "";
        }
        if (!("recordCount" in $$source)) {
            this["recordCount"] = 0;
        }
        if (!("lanceTableName" in $$source)) {
            this["lanceTableName"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("lastUsedAt" in $$source)) {
            this["lastUsedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsEmbeddingDimension instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsEmbeddingDimension {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VfsEmbeddingDimension($$parsedSource as Partial<VfsEmbeddingDimension>);
    }
}

export class VfsFile {
    "id": string;
    "resourceId"?: string | null;
    "blobHash"?: string | null;
    "sha256": string;
    "fileName": string;
    "originalPath"?: string | null;
    "size": number;
    "pageCount"?: number | null;
    "fileType": string;
    "mimeType"?: string | null;
    "tags": string[];
    "isFavorite": boolean;
    "lastOpenedAt"?: string | null;
    "lastPage"?: number | null;
    "bookmarks": any[];
    "coverKey"?: string | null;
    "extractedText"?: string | null;
    "previewJson"?: string | null;
    "ocrPagesJson"?: string | null;
    "description"?: string | null;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
    "deletedAt"?: string | null;
    "metadata"?: { [_ in string]?: any };

    /** Creates a new VfsFile instance. */
    constructor($$source: Partial<VfsFile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("fileType" in $$source)) {
            this["fileType"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("isFavorite" in $$source)) {
            this["isFavorite"] = false;
        }
        if (!("bookmarks" in $$source)) {
            this["bookmarks"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsFile instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsFile {
        const $$createField10_0 = $$createType3;
        const $$createField14_0 = $$createType24;
        const $$createField24_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        if ("bookmarks" in $$parsedSource) {
            $$parsedSource["bookmarks"] = $$createField14_0($$parsedSource["bookmarks"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField24_0($$parsedSource["metadata"]);
        }
        return new VfsFile($$parsedSource as Partial<VfsFile>);
    }
}

export class VfsMindMap {
    "id": string;
    "resourceId": string;
    "title": string;
    "description"?: string | null;
    "isFavorite": boolean;
    "defaultView": string;
    "theme"?: string | null;
    "settings"?: { [_ in string]?: any };
    "createdAt": string;
    "updatedAt": string;
    "deletedAt"?: string | null;

    /** Creates a new VfsMindMap instance. */
    constructor($$source: Partial<VfsMindMap> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("isFavorite" in $$source)) {
            this["isFavorite"] = false;
        }
        if (!("defaultView" in $$source)) {
            this["defaultView"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsMindMap instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsMindMap {
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField7_0($$parsedSource["settings"]);
        }
        return new VfsMindMap($$parsedSource as Partial<VfsMindMap>);
    }
}

export class VfsMindMapVersion {
    "versionId": string;
    "mindmapId": string;
    "resourceId": string;
    "title": string;
    "label"?: string | null;
    "source"?: string | null;
    "createdAt": string;

    /** Creates a new VfsMindMapVersion instance. */
    constructor($$source: Partial<VfsMindMapVersion> = {}) {
        if (!("versionId" in $$source)) {
            this["versionId"] = "";
        }
        if (!("mindmapId" in $$source)) {
            this["mindmapId"] = "";
        }
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsMindMapVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsMindMapVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VfsMindMapVersion($$parsedSource as Partial<VfsMindMapVersion>);
    }
}

export class VfsRagSearchInput {
    "query": string;
    "folderIds"?: string[];
    "resourceTypes"?: string[];
    "topK"?: number;
    "enableReranking"?: boolean;
    "enableCrossDimension"?: boolean;
    "modality"?: string;

    /** Creates a new VfsRagSearchInput instance. */
    constructor($$source: Partial<VfsRagSearchInput> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsRagSearchInput instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsRagSearchInput {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folderIds" in $$parsedSource) {
            $$parsedSource["folderIds"] = $$createField1_0($$parsedSource["folderIds"]);
        }
        if ("resourceTypes" in $$parsedSource) {
            $$parsedSource["resourceTypes"] = $$createField2_0($$parsedSource["resourceTypes"]);
        }
        return new VfsRagSearchInput($$parsedSource as Partial<VfsRagSearchInput>);
    }
}

export class VfsRagSearchOutput {
    "results": VfsSearchResult[];
    "count": number;
    "elapsedMs": number;

    /** Creates a new VfsRagSearchOutput instance. */
    constructor($$source: Partial<VfsRagSearchOutput> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsRagSearchOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsRagSearchOutput {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new VfsRagSearchOutput($$parsedSource as Partial<VfsRagSearchOutput>);
    }
}

export class VfsSearchResult {
    "embeddingId": string;
    "resourceId": string;
    "chunkIndex": number;
    "chunkText": string;
    "score": number;
    "resourceTitle"?: string | null;
    "resourceType"?: string | null;
    "pageIndex"?: number | null;
    "sourceId"?: string | null;

    /** Creates a new VfsSearchResult instance. */
    constructor($$source: Partial<VfsSearchResult> = {}) {
        if (!("embeddingId" in $$source)) {
            this["embeddingId"] = "";
        }
        if (!("resourceId" in $$source)) {
            this["resourceId"] = "";
        }
        if (!("chunkIndex" in $$source)) {
            this["chunkIndex"] = 0;
        }
        if (!("chunkText" in $$source)) {
            this["chunkText"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VfsSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): VfsSearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VfsSearchResult($$parsedSource as Partial<VfsSearchResult>);
    }
}

// Private type creation functions
const $$createType0 = ResourceRef.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = StateStats.createFrom;
const $$createType5 = DimensionStat.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = PdfProcessingFailedStage.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = PdfProcessingProgress.createFrom;
const $$createType10 = MultimodalBlock.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ResourceIndexStatus.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = OcrPageInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ResourceInjectModes.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = Attachment.createFrom;
const $$createType19 = VfsFile.createFrom;
const $$createType20 = OcrStatus.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = IndexStatus.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Array($Create.Any);
const $$createType25 = VfsSearchResult.createFrom;
const $$createType26 = $Create.Array($$createType25);
