// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FrontendLogPayload {
    "level"?: string;
    "message": string;
    "stack"?: string;
    "component"?: string;
    "route"?: string;
    "url"?: string;
    "line"?: number | null;
    "column"?: number | null;
    "user_agent"?: string;
    "extra"?: { [_ in string]?: any };
    "kind"?: string;

    /** Creates a new FrontendLogPayload instance. */
    constructor($$source: Partial<FrontendLogPayload> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendLogPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): FrontendLogPayload {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField9_0($$parsedSource["extra"]);
        }
        return new FrontendLogPayload($$parsedSource as Partial<FrontendLogPayload>);
    }
}

export class SaveWebviewSettingsResult {
    "success": boolean;
    "path": string;
    "size": number;

    /** Creates a new SaveWebviewSettingsResult instance. */
    constructor($$source: Partial<SaveWebviewSettingsResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveWebviewSettingsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveWebviewSettingsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveWebviewSettingsResult($$parsedSource as Partial<SaveWebviewSettingsResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
