// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreatePomodoroInput {
    "todoItemId"?: string | null;
    "startTime": string;
    "endTime"?: string | null;
    "duration": number;
    "actualDuration": number;
    "type"?: string | null;
    "status"?: string | null;

    /** Creates a new CreatePomodoroInput instance. */
    constructor($$source: Partial<CreatePomodoroInput> = {}) {
        if (!("startTime" in $$source)) {
            this["startTime"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("actualDuration" in $$source)) {
            this["actualDuration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatePomodoroInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatePomodoroInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreatePomodoroInput($$parsedSource as Partial<CreatePomodoroInput>);
    }
}

export class CreateTodoItemInput {
    "todoListId": string;
    "title": string;
    "description"?: string | null;
    "priority"?: string | null;
    "dueDate"?: string | null;
    "dueTime"?: string | null;
    "tags"?: string[];
    "parentId"?: string | null;
    "attachments"?: string[];

    /** Creates a new CreateTodoItemInput instance. */
    constructor($$source: Partial<CreateTodoItemInput> = {}) {
        if (!("todoListId" in $$source)) {
            this["todoListId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTodoItemInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTodoItemInput {
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField8_0($$parsedSource["attachments"]);
        }
        return new CreateTodoItemInput($$parsedSource as Partial<CreateTodoItemInput>);
    }
}

export class CreateTodoListInput {
    "title": string;
    "description"?: string | null;
    "icon"?: string | null;
    "color"?: string | null;

    /** Creates a new CreateTodoListInput instance. */
    constructor($$source: Partial<CreateTodoListInput> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTodoListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTodoListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTodoListInput($$parsedSource as Partial<CreateTodoListInput>);
    }
}

export class PomodoroRecord {
    "id": string;
    "todoItemId"?: string | null;
    "startTime": string;
    "endTime"?: string | null;
    "duration": number;
    "actualDuration": number;
    "type": string;
    "status": string;
    "createdAt": string;

    /** Creates a new PomodoroRecord instance. */
    constructor($$source: Partial<PomodoroRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("actualDuration" in $$source)) {
            this["actualDuration"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PomodoroRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): PomodoroRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PomodoroRecord($$parsedSource as Partial<PomodoroRecord>);
    }
}

export class PomodoroTodayStats {
    "completedCount": number;
    "totalFocusSeconds": number;
    "interruptedCount": number;

    /** Creates a new PomodoroTodayStats instance. */
    constructor($$source: Partial<PomodoroTodayStats> = {}) {
        if (!("completedCount" in $$source)) {
            this["completedCount"] = 0;
        }
        if (!("totalFocusSeconds" in $$source)) {
            this["totalFocusSeconds"] = 0;
        }
        if (!("interruptedCount" in $$source)) {
            this["interruptedCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PomodoroTodayStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PomodoroTodayStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PomodoroTodayStats($$parsedSource as Partial<PomodoroTodayStats>);
    }
}

export class ReorderItemsInput {
    "listId": string;
    "itemIds": string[];

    /** Creates a new ReorderItemsInput instance. */
    constructor($$source: Partial<ReorderItemsInput> = {}) {
        if (!("listId" in $$source)) {
            this["listId"] = "";
        }
        if (!("itemIds" in $$source)) {
            this["itemIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReorderItemsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReorderItemsInput {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("itemIds" in $$parsedSource) {
            $$parsedSource["itemIds"] = $$createField1_0($$parsedSource["itemIds"]);
        }
        return new ReorderItemsInput($$parsedSource as Partial<ReorderItemsInput>);
    }
}

export class TodoActiveSummary {
    "todayItems": TodoSummaryItem[];
    "overdueItems": TodoSummaryItem[];
    "upcomingHighPriority": TodoSummaryItem[];
    "stats": TodoStats;

    /** Creates a new TodoActiveSummary instance. */
    constructor($$source: Partial<TodoActiveSummary> = {}) {
        if (!("todayItems" in $$source)) {
            this["todayItems"] = [];
        }
        if (!("overdueItems" in $$source)) {
            this["overdueItems"] = [];
        }
        if (!("upcomingHighPriority" in $$source)) {
            this["upcomingHighPriority"] = [];
        }
        if (!("stats" in $$source)) {
            this["stats"] = (new TodoStats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoActiveSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TodoActiveSummary {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("todayItems" in $$parsedSource) {
            $$parsedSource["todayItems"] = $$createField0_0($$parsedSource["todayItems"]);
        }
        if ("overdueItems" in $$parsedSource) {
            $$parsedSource["overdueItems"] = $$createField1_0($$parsedSource["overdueItems"]);
        }
        if ("upcomingHighPriority" in $$parsedSource) {
            $$parsedSource["upcomingHighPriority"] = $$createField2_0($$parsedSource["upcomingHighPriority"]);
        }
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField3_0($$parsedSource["stats"]);
        }
        return new TodoActiveSummary($$parsedSource as Partial<TodoActiveSummary>);
    }
}

export class TodoItem {
    "id": string;
    "todoListId": string;
    "title": string;
    "description"?: string | null;
    "status": string;
    "priority": string;
    "dueDate"?: string | null;
    "dueTime"?: string | null;
    "reminder"?: string | null;
    "tagsJson": string;
    "sortOrder": number;
    "parentId"?: string | null;
    "completedAt"?: string | null;
    "repeatJson"?: string | null;
    "attachmentsJson": string;
    "estimatedPomodoros"?: number | null;
    "completedPomodoros"?: number | null;
    "createdAt": string;
    "updatedAt": string;
    "deletedAt"?: string | null;

    /** Creates a new TodoItem instance. */
    constructor($$source: Partial<TodoItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("todoListId" in $$source)) {
            this["todoListId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("tagsJson" in $$source)) {
            this["tagsJson"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("attachmentsJson" in $$source)) {
            this["attachmentsJson"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TodoItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodoItem($$parsedSource as Partial<TodoItem>);
    }
}

export class TodoList {
    "id": string;
    "title": string;
    "description"?: string | null;
    "icon"?: string | null;
    "color"?: string | null;
    "sortOrder": number;
    "isDefault": boolean;
    "isFavorite": boolean;
    "createdAt": string;
    "updatedAt": string;
    "deletedAt"?: string | null;

    /** Creates a new TodoList instance. */
    constructor($$source: Partial<TodoList> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("isFavorite" in $$source)) {
            this["isFavorite"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoList instance from a string or object.
     */
    static createFrom($$source: any = {}): TodoList {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodoList($$parsedSource as Partial<TodoList>);
    }
}

export class TodoStats {
    "totalPending": number;
    "todayDue": number;
    "overdueCount": number;
    "todayCompleted": number;

    /** Creates a new TodoStats instance. */
    constructor($$source: Partial<TodoStats> = {}) {
        if (!("totalPending" in $$source)) {
            this["totalPending"] = 0;
        }
        if (!("todayDue" in $$source)) {
            this["todayDue"] = 0;
        }
        if (!("overdueCount" in $$source)) {
            this["overdueCount"] = 0;
        }
        if (!("todayCompleted" in $$source)) {
            this["todayCompleted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoStats instance from a string or object.
     */
    static createFrom($$source: any = {}): TodoStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodoStats($$parsedSource as Partial<TodoStats>);
    }
}

export class TodoSummaryItem {
    "id": string;
    "title": string;
    "priority": string;
    "dueDate"?: string | null;
    "dueTime"?: string | null;
    "listTitle": string;

    /** Creates a new TodoSummaryItem instance. */
    constructor($$source: Partial<TodoSummaryItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("listTitle" in $$source)) {
            this["listTitle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoSummaryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TodoSummaryItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodoSummaryItem($$parsedSource as Partial<TodoSummaryItem>);
    }
}

export class UpdateTodoItemInput {
    "id": string;
    "title"?: string | null;
    "description"?: string | null;
    "status"?: string | null;
    "priority"?: string | null;
    "dueDate"?: string | null;
    "dueTime"?: string | null;
    "reminder"?: string | null;
    "tags"?: string[];
    "parentId"?: string | null;
    "attachments"?: string[];
    "repeatJson"?: string | null;
    "estimatedPomodoros"?: number | null;
    "completedPomodoros"?: number | null;

    /** Creates a new UpdateTodoItemInput instance. */
    constructor($$source: Partial<UpdateTodoItemInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateTodoItemInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateTodoItemInput {
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField10_0($$parsedSource["attachments"]);
        }
        return new UpdateTodoItemInput($$parsedSource as Partial<UpdateTodoItemInput>);
    }
}

export class UpdateTodoListInput {
    "id": string;
    "title"?: string | null;
    "description"?: string | null;
    "icon"?: string | null;
    "color"?: string | null;

    /** Creates a new UpdateTodoListInput instance. */
    constructor($$source: Partial<UpdateTodoListInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateTodoListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateTodoListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateTodoListInput($$parsedSource as Partial<UpdateTodoListInput>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TodoSummaryItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = TodoStats.createFrom;
