// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AssetRef {
    "absolute_path": string;
    "relative_path": string;

    /** Creates a new AssetRef instance. */
    constructor($$source: Partial<AssetRef> = {}) {
        if (!("absolute_path" in $$source)) {
            this["absolute_path"] = "";
        }
        if (!("relative_path" in $$source)) {
            this["relative_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetRef instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetRef($$parsedSource as Partial<AssetRef>);
    }
}

export class DBStats {
    "db_path": string;
    "file_size_bytes": number;
    "total_notes": number;
    "total_versions": number;
    "total_assets": number;

    /** Creates a new DBStats instance. */
    constructor($$source: Partial<DBStats> = {}) {
        if (!("db_path" in $$source)) {
            this["db_path"] = "";
        }
        if (!("file_size_bytes" in $$source)) {
            this["file_size_bytes"] = 0;
        }
        if (!("total_notes" in $$source)) {
            this["total_notes"] = 0;
        }
        if (!("total_versions" in $$source)) {
            this["total_versions"] = 0;
        }
        if (!("total_assets" in $$source)) {
            this["total_assets"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBStats instance from a string or object.
     */
    static createFrom($$source: any = {}): DBStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBStats($$parsedSource as Partial<DBStats>);
    }
}

export class ExportRequest {
    "output_path"?: string | null;
    "include_versions"?: boolean | null;

    /** Creates a new ExportRequest instance. */
    constructor($$source: Partial<ExportRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRequest($$parsedSource as Partial<ExportRequest>);
    }
}

export class ExportResult {
    "output_path": string;
    "note_count": number;
    "attachment_count": number;

    /** Creates a new ExportResult instance. */
    constructor($$source: Partial<ExportResult> = {}) {
        if (!("output_path" in $$source)) {
            this["output_path"] = "";
        }
        if (!("note_count" in $$source)) {
            this["note_count"] = 0;
        }
        if (!("attachment_count" in $$source)) {
            this["attachment_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult($$parsedSource as Partial<ExportResult>);
    }
}

export class ExportSingleRequest {
    "note_id": string;
    "output_path"?: string | null;
    "include_versions"?: boolean | null;

    /** Creates a new ExportSingleRequest instance. */
    constructor($$source: Partial<ExportSingleRequest> = {}) {
        if (!("note_id" in $$source)) {
            this["note_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportSingleRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportSingleRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportSingleRequest($$parsedSource as Partial<ExportSingleRequest>);
    }
}

export class ImportRequest {
    "file_path": string;
    "conflict_strategy"?: string | null;

    /** Creates a new ImportRequest instance. */
    constructor($$source: Partial<ImportRequest> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportRequest($$parsedSource as Partial<ImportRequest>);
    }
}

export class ImportResult {
    "subject_count": number;
    "note_count": number;
    "attachment_count": number;
    "skipped_count": number;
    "overwritten_count": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("subject_count" in $$source)) {
            this["subject_count"] = 0;
        }
        if (!("note_count" in $$source)) {
            this["note_count"] = 0;
        }
        if (!("attachment_count" in $$source)) {
            this["attachment_count"] = 0;
        }
        if (!("skipped_count" in $$source)) {
            this["skipped_count"] = 0;
        }
        if (!("overwritten_count" in $$source)) {
            this["overwritten_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}
