// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export type Template = { [_ in string]?: any };

export class TemplateExportResponse {
    "template_data": string;

    /** Creates a new TemplateExportResponse instance. */
    constructor($$source: Partial<TemplateExportResponse> = {}) {
        if (!("template_data" in $$source)) {
            this["template_data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateExportResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateExportResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateExportResponse($$parsedSource as Partial<TemplateExportResponse>);
    }
}
